# --------------------
# Grocy
#   - Repo:           https://github.com/grocy/grocy
#   - Docs:           https://grocy.info/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
---
replicas: 1
image:
  repository: lscr.io/linuxserver/grocy
  tag: 4.3.1
ports:
  - containerPort: 80
    service: true

service:
  enabled: true

volumeMounts:
  - name: config
    mountPath: /config

volumes:
  - name: config
    mountPvc: true

pvc:
  storageClassName: longhorn-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
ingress:
  enabled: true
  authelia: true
  className: nginx
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: grocy.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
