# --------------------
# Grocy
#   - Repo:           https://github.com/grocy/grocy
#   - Docs:           https://grocy.info/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
---
replicas: 1
image:
  repository: lscr.io/linuxserver/grocy
  tag: v4.6.0-ls321
ports:
  - containerPort: 80
    service: true

service:
  enabled: true

volumeMounts:
  - name: config
    mountPath: /config

volumes:
  - name: config
    mountPvc: true

pvc:
  storageClassName: longhorn-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
ingress:
  enabled: true
  authelia: true
  className: nginx
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: grocy.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  tcpSocket:
    port: 80
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  tcpSocket:
    port: 80
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

startupProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 18
  timeoutSeconds: 5
