replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/wordpress
    tag: 6.8
    pullPolicy: Always
ports:
    - containerPort: 80
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        WORDPRESS_DATABASE_HOST: ENC[AES256_GCM,data:Dor8lBwi29Jmuq793kwI9x4Iw8Pa4hg0qNCHKXZZ1/cS67A=,iv:63c3KkHnhjIrUhzkIAOnA/pksQxa5aEj65aYISVrfTE=,tag:LST4C1rwlaSHddCdhW0ojw==,type:str]
        WORDPRESS_DATABASE_NAME: ENC[AES256_GCM,data:6hFGD8vPje8Qai17,iv:jnUcfBPlvE0B9sMS7Kd6hHeE9E+AhbTLMtI3UBl78x8=,tag:i+UQZVvt6BbkOIZryIy9PA==,type:str]
        WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:6MeW3ZXO07kxzpGgzSCan3k6jcA=,iv:XnJtKejsmtX8W2F/qe16/hmwQb60OSCnI4gWNYGu7c8=,tag:FHQH//gVPskrZYjE2W5eSg==,type:str]
        WORDPRESS_DATABASE_USER: ENC[AES256_GCM,data:p9r2JuKrPHi5TddP,iv:a+RhfZT5VjtPqZ0mGycrixZSrXUoPhdb2JBWo7Q2LIM=,tag:mVWSIIYGUJQWW+dO7c5L6g==,type:str]
configmap:
    mountEnv: true
    data:
        PHP_UPLOAD_MAX_FILESIZE: 5G
        PHP_POST_MAX_SIZE: 5G
        # PHP_MAX_EXECUTION_TIME: "1000000"
volumeMounts:
    - name: data
      mountPath: /var/www/html
volumes:
    - name: data
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
ingress:
    enabled: true
    authelia: false
    className: nginx
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 5G
        ingress.kubernetes.io/proxy-body-size: 5000m
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: mariana-afonso.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - mariadb
                topologyKey: kubernetes.io/hostname
sops:
    lastmodified: "2026-04-13T20:28:43Z"
    mac: ENC[AES256_GCM,data:Fr4/P2m6/59oInonH5d5DiMKD9Rs7eINj28FAI0QllIJZ29w3EeUWI3ZYS5DCrzShUdJM1Hlki84iXASRIfr5x43u14adjHr1caOMiNlOyTYY5f3zGgRzevxPK82Mhltk3eahyXHx5/c7cTY20NkFFubwoJpO6TwWukEPtzoYBo=,iv:eCZRF3lO7hnel/lmsmGCmECUy1aOYHiEcNhGIsbAqGs=,tag:2qb5qENyF1JAAyUtmUQ05Q==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/9GTtjSYd9O755VT6Haa/YXPcepnpUGJGosI0kfRmu6bHX
            EYIJpR+WWqDDoytx/LIr55H7iylV6RtdsgmpVcaNLsdhXt6IPko2qpXeTsPf6fwj
            bhcg2JhOklqwy6evL4/J4kKGOO38kIl0JDAPH8O6xvhC+wfa3daZ+vvutGCQybbG
            1WG8+RVufR9xrmKkYKbpSw8PSUcITxM6OmVbNwHAJCnwI1Bga3JU5uJFLH6X6CbU
            TiLA2GxjcLFhOt1qcUuQdtocJAqnzlPLPx+I4tQrybkT4t7Po54BpTfasVEOijc0
            yM3oqfyx4ZT2Rb+anylXQD3dTODC3/bowGmJUKSZZSOYPFoUNlY1P6UDdnC1Xk7A
            qv84sE98oBuq6OFbVVXPGsghsuW2d67WB87ravKzZ7qusx+LYcQ9BAlqtEfrIUa8
            3CLFoirzqu4I44whC98Oqp/j6rMKcAtb/3ppVkpbpiJ/n5N2hlXJUCj8bR5irC/D
            zQ44VN0lzJDGBtMG1HWtx5wNyUrmDU7Nqjb4oIC03LywcwMSDIva1RSdeZb2auTH
            g6Fwb91lGbPxIxav7NvyzDQt2nmbZY2tTfxPhO0vXDrTyKJmhV7Zcy4nJIUzxWKu
            8DYn73+JVm6cOXjlowFKoj4aReeAAKlxQPyAdUNkzfxonEv/UuVkni6XuvpKbyjU
            aAEJAhBmNXfn8/CLeeAXzAE79FVfOmWKzhXh9ICrWP5dMCWQT44AlXAuqK6K+qfl
            U4Mb0b3UsMWivIN6Q57ZbPU/+/A68ZNdpHG27r06EQ2vz6e2ZIhsGPbYO2UBmIF3
            p4ATNviWjlwq
            =S6DS
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
