# --------------------
# MariaDB
#   - Repo:           https://github.com/MariaDB/server
#   - Docs:           https://mariadb.org/documentation/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/database-svc/values.yaml
# --------------------
labels:
    tier: db
    # label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/mariadb
    tag: 13.0.2
#   pullPolicy: Always
command: {}
args: {}
ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
      service: true
    - containerPort: 9104
      name: metrics
      protocol: TCP
      service: true
service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: ENC[AES256_GCM,data:LRhePZf05WdTtic=,iv:/YVuCUebQTh+engYW2OSFo0ZpNyL0AgOU88mB0XgvHI=,tag:x6CecSkpDfcX7GmqF85ssg==,type:str]
    annotations:
        metallb.universe.tf/allow-shared-ip: db-svc
secret:
    stringData:
        MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:E1JB0960ta03h2n/HsUzoVfhvSw=,iv:GZgpXZp4PSuNHl3gLf130Jg502mfD/Bz43erkkQVJmI=,tag:DUq6o95iDx83LCuQkWSzGg==,type:str]
        MYSQLD_EXPORTER_PASSWORD: ENC[AES256_GCM,data:NqgOY2dfObO56vk84e9NMmfSmEQ=,iv:BqffRKHvATymvlIfp1+fPy+dauFRCJBXZybjVDt0JKg=,tag:j6M0m3z0RyrqmHpvBznVcw==,type:str]
configmap: {}
# config_1: abc
# config_2: def
volumeMounts:
    - name: data
      mountPath: /var/lib/mysql
volumeClaimTemplates:
    - name: data
      accessModes:
        - ReadWriteOnce
      storageClass: longhorn-persistent
      storage: 10Gi
livenessProbe:
    tcpSocket:
        port: 3306
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
readinessProbe:
    tcpSocket:
        port: 3306
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
startupProbe:
    tcpSocket:
        port: 3306
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
resources:
    limits:
        cpu: 1
        memory: 1Gi
    requests:
        cpu: 50m
        memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
extraContainers:
    - name: mysqld-exporter
      image: docker.io/prom/mysqld-exporter:v0.20.0
      ports:
        - containerPort: 9104
          name: metrics
          protocol: TCP
      env:
        - name: MYSQLD_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mariadb
                key: MYSQLD_EXPORTER_PASSWORD
      args:
        - --mysqld.address=localhost:3306
        - --mysqld.username=mysqld_exporter
        - --collect.global_status
        - --collect.global_variables
        - --collect.info_schema.innodb_metrics
        - --collect.info_schema.processlist
        - --collect.info_schema.tables
        - --collect.perf_schema.eventsstatements
        # - --collect.slave_status
        # - --collect.auto_increment.columns
        # - --collect.binlog_size
        # - --collect.perf_schema.tableiowaits
        # - --collect.perf_schema.tablelocks
      resources:
        requests:
            cpu: 5m
            memory: 16Mi
        limits:
            cpu: 5m
            memory: 16Mi
backup:
    enabled: true
    schedule: 0 3 * * *
    rootPasswordKey: MYSQL_ROOT_PASSWORD
    concurrencyPolicy: Forbid
    activeDeadlineSeconds: 3600
    backoffLimit: 0
    prometheusRule:
        enabled: true
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    # community edition: retention.within only supports minutes (129600m = 90d)
    configmap:
        data:
            db-backup.yml: ENC[AES256_GCM,data:DZNTchoS1pmF1ATRmw4cWVGI3bST4HTTEsH33Drdz3xD1bqiR7rJMKPpVxTUae/H9wkNXJSEfHtTHjfKQEQZoETc3crcNgy+dbDUEtwEXzVaz1rA4hXYOwVGFHKks8bAk0zr5yQm327cuQi3hjSjJeN3BhX3rAXdad3+/M/UXkYCzydRwyaYEEBJSB+8H89pI1LVO4dbUqkOIyaKr3xV/O3LACOe/lmJtH1LOt6t46YDZ3H6mx3m2KOJNxFpzT+rdA+p6bsp35/gA9QZtC0H4qXuZ2AiJ7zYYMOV1DbORZbtybq5TKyWfjwP5aVBPo0r6j/xYXYvPXL06J8d3++wxKcsa3oVXgOvzazjIX4RohlViuurOXThB0sHc78zrCFbeoaL3nu0DMMPOtNzvPCdtiUyReD+cYdJ88JHphiYAjhCV5CJGUHBiqHs6mx3zRtnnegQeHvH356cY0oCn0goK5RAqwD7DwgRu6sVlvgJJLqrqIHXmtFkKb4oa2fK4nc93Afw/ursErUM//6mzxwx8odoF1X7gvNte4snM1/e8RsAfmzyrhZ3vYhuG4UyG+561JPlr2eMEOCoSG/E3QRNdNyRiIjyoC66HXPuYYHosycrIjqtz9nCBJA2yBQhyt3x2JhmhVEd7a7B7RM/2b6cc4Xgk0/QwpVJ1SJIQmExAq5cAv3wn2BgMhrpVkemRG8K5KkbJl7Nl6FIpahIwQOyMeXUh8sa2OB2PjXLth9aTrSotMvjY9ZXPpYPLLPePpmyAp3rBeRovnS8eRBL4aWcIwrNYbsXCGxOV8Z2+ESYeZeAtTDpri1vZeZXjzUJd/zFThLk//bN12yjYbyqJ1v8xpKcph4B3poDFtprCfyopKzHTTiRjoLINDjq,iv:TdxDDKvOFhgPZ1V96Xn7bB4THXiLqwlJgNOY4zbfTls=,tag:hI3l6/FAl+OdpvJNY3QMBA==,type:str]
    affinity:
        podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                        - key: tier
                          operator: In
                          values:
                            - db
                  topologyKey: kubernetes.io/hostname
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
        limits:
            cpu: 100m
            memory: 256Mi
sops:
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    lastmodified: "2026-09-23T00:26:45Z"
    mac: ENC[AES256_GCM,data:SBGrsg6y/8NOaMZcUVfiLbNsIW2RdrFCc6FhOeaBCi0RSd3ArNeD0TS/Ql4j8iX8oSQSVOtQaqV2g5iosjYoqq9f/dJW+PQ9brPwkz77RqdUkXPV+AuBqPeZUMfwWSoxkxqwd9uE9zjYgiIHJ0RVS4o5ExNCk4rsiNVzFGFJi9M=,iv:1eUb2zn4c5TrUOcgV0ys2ZXa5DSfCSsaddSWlJZk2EQ=,tag:KhJUHoRZGnCLMoscU8X8CQ==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-09-23T00:26:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//dwE0MgkITEyNZaLr2KkoshfOsqhSdKJrvJwAdJ1TGcBi
            s4/FK2JVh7k+Z37qso5JeHeTDNKUYM6I0G4THYg9TR2GxCp0xbh1L2Qq/b0gul/a
            7sRqPF0mh2twwJUEN9tMOYaHmnnsP+16QdiStB/zfjdxUyBFNWXFt4jGKit3Y8YR
            0zVoTP617U/CgAzPmiKerazLJ1pOXs1D8Ih0VX0Ms9DxsL3SspK6YFfFebEPJ4CR
            AF+tihqGZsTNxV1k3zunERhVO1NfMv4605l6zBXsGvTAEvh+jsbiJJT9wLOyT0o4
            GJXRv3fXlzvM01zgXwTPhD+OjFiOH4x2s9eAF9hIhRGaAmZX4mkgUywfToqO5dCn
            etX2bOaNT+IS82DnAxU8XspveEMNo4BXU2ns1Ss1qg/MalYpCtACP8JWU59po3E0
            +BAkbr8z5sNFGncj3cRqhXN6u6D9ArKw7X7GcEDVubjkoa/7En6RP+e4QaSiZTK+
            0zHb+9nmfD11ClqX01WXkL0Mm+JfIgJp5gMpN/mmvvFfq0jwQClPR6pYRIJP6q2p
            YqNhRnzcIcZQWdtTMthbxTkksM/PVlxuBVXrwZL4GCHQ4+lbOOP/igT+Cam0kYe5
            6MiHl/8Ev6ohEBlehZnznce37IblJX3jPATiz0Esz+R5m14JEMljy9hxfZyS7TDU
            aAEJAhAt4qPocT3Xfw/s0Lz3SxZllbqh/EQ1g0AyIhmZLty+x8W3X21FxFj3KWah
            3ZfMT5Wp41oPLdQig858DoePuTpUL73HN50nsQJ4mxhWt39kAl2MDFt8Q/jBam+A
            QSQqXcnPtacS
            =uNLE
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
