labels:
    tier: db
    # label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/influxdb
    tag: 3.5-enterprise
comand:
    - influxdb3
args:
    - serve
    - --cluster-id=k3s-cluster
    - --node-id=$HOSTNAME
    - --object-store=file
    - --data-dir=/var/lib/influxdb3/data
    - --plugin-dir=/var/lib/influxdb3/plugins
ports:
    - containerPort: 8181
      name: influxdb
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    stringData:
        INFLUXDB3_ENTERPRISE_LICENSE_EMAIL: ENC[AES256_GCM,data:Q+RJsY6/FZs9PcUVY5BsJre+BLJfQTjb1ttInrvqLN/Olg==,iv:qsftmQApQu2bFd74wuZolYe8wcEpz+NMfX5W78B75+g=,tag:kek/LlJ5Y+MNmrxuPO0FhA==,type:str]
volumeMounts:
    - name: data
      mountPath: /var/lib/influxdb3
volumeClaimTemplates:
    - name: data
      accessModes:
        - ReadWriteOnce
      storageClass: longhorn-persistent
      storage: 5Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: {}
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: influxdb.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
# livenessProbe:
#   httpGet:
#     path: "/ping"
#     port: "{{ .Values.ports[0].containerPort }}"
#   initialDelaySeconds: 30
#   timeoutSeconds: 5
# readinessProbe:
#   httpGet:
#     path: "/ping"
#     port: "{{ .Values.ports[0].containerPort }}"
#   initialDelaySeconds: 5
#   timeoutSeconds: 1
resources:
    requests:
        memory: 128Mi
        cpu: 0.2
    limits:
        memory: 1Gi
        cpu: 1
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
backup:
    enabled: false
sops:
    lastmodified: "2026-04-13T20:28:41Z"
    mac: ENC[AES256_GCM,data:IIjMiLghPnhNdgGDykn0QCgqxyk0RLrVPP7WILW5yfhAcC3Pt+r+Y/jmSziMjpeXCC0buonC9UG9J1TGRLrVv8tOEv9svwpOuCGMx5a5LgLSQTXb7vSH31sqa25mS4ZsV8uMOgoZFYRfjEh9SjGDNhoUP9tQvMV1FUBFQGvSfC0=,iv:wZUlzGFf2rTc+zHlWXBnubTAe63kLyZ+qaAenqzEWw4=,tag:bzlhUJItz4fQGTIXV8vgjg==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//em+sj9gdASh5LrcjZzD/tLo/n1tw6qLB/4+dBUBf7F6P
            XoCtL79Ug513XhhoTe106tP9ZfA8AMc5DSNOA9R6HVG31HCpJwZzjhWupt3DkWFV
            914ARkw0XJDgJr3SaX6+0bCeQLgDmQb99Vup0D20KisQfQXfXijJJ99OVFK2eejg
            RiuL+c9jQNU6vy1ppW8VV0xS0MEgyBCnp0RuQPdhv9rNMPoRZuywYPKDCvovnpxn
            sq53ujafek+e1S64EyWh3f5YNGYbJ3gJc+fs/OhWLpDfPRlRodOp+FtLTn0QpVkH
            kfvJYUKdQJOYYsaiSN0CX2xRRHOGAzlOQO5LRwHFoBsNbTpdIpZgKzMyfJTMDsbu
            J68m25GvKRNS+LukhJQSyywWvc3oLFTidsMH9JTz9TwQWtu65qziR34AmGY4QwMV
            izaeFAY28h2sPxmJaeCdJINL7dxpW+/ZqRgO9FPNwfzjB/WKGNXZzI8j7eWDzB98
            YFowj+BATrGx3qGWWvHZ2b/biiRdfthGFnaaxD3D/h6bMv6qgfpHabZyWb22BPhJ
            BfZmQMhphJcnlcCzC1C0l69RyLQ7zWrrgJGeWlAX0dkiqKoQq70xC03N/uM3R2Hw
            v2kqd3KkIlnefShwn1aqNRHoT9/OTafzme7OYLnuWBtJd/l128umh21xGG/hTirU
            aAEJAhB40B4I4XkUTpg4snlj4De7N/rygJqKd7sqjWp4yvHumOxUjFUvkxcYeLqN
            cDROUZzEyvE5jQN46hCpcgHPkePGuxz3UJg+96n0i9wd+dOV4OUIZPuWyOVXBwgC
            /2qme9Gl6/cP
            =5xe6
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
