# --------------------
# cert-manager Resources
#   - Repo:           https://github.com/afonsoc12/homelab
#   - Docs:           https://cert-manager.io/docs/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/cert-manager-resources/values.yaml
# --------------------
issuers:
    - name: letsencrypt
      server: https://acme-v02.api.letsencrypt.org/directory
      # Name of a secret used to store the ACME account private key
      apiTokenSecretRef:
        name: cloudflare-api
        key: API_TOKEN
    - name: letsencrypt-stg
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      # Name of a secret used to store the ACME account private key
      apiTokenSecretRef:
        name: cloudflare-api
        key: API_TOKEN
secrets:
    - name: cloudflare-api
      stringData:
        API_TOKEN: ENC[AES256_GCM,data:ekm3kTZpYZvTlX4tX62wqMzp5tnx3dwEKhIRmmG0HYBhbVL/Z1LZSA==,iv:JoNvHvWvVQogV3seMicISUCp3g0EdrAD9uqX8ebL3Yc=,tag:0IrTjvTraTegjW/BXtzlhg==,type:str]
certificates:
    - name: auth
      dnsNames:
        - auth.{{ .Values.domain }}
      reflectNamespaces:
        - ingress
    - name: calibre
      dnsNames:
        - calibre.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: firefly
      dnsNames:
        - firefly.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: git
      dnsNames:
        - git.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: home
      dnsNames:
        - home.{{ .Values.domain }}
      reflectNamespaces:
        - automation
        - sandbox
    - name: local-wildcard
      dnsNames:
        - local.{{ .Values.domain }}
        - '*.local.{{ .Values.domain }}'
      reflectNamespaces:
        - addons
        - automation
        - databases
        - homelab
        - ingress
        - longhorn-system
        - monitoring
        - sandbox
        - wordpress
    - name: seerr
      dnsNames:
        - seerr.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: plex
      dnsNames:
        - plex.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - ingress
        - sandbox
    - name: rss
      dnsNames:
        - rss.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: srv-wildcard
      dnsNames:
        - '*.srv.{{ .Values.domain }}'
      reflectNamespaces:
        - homelab
        - sandbox
    - name: stocks
      dnsNames:
        - stocks.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: wallabag
      dnsNames:
        - wallabag.{{ .Values.domain }}
      reflectNamespaces:
        - homelab
        - sandbox
    - name: status
      dnsNames:
        - status.{{ .Values.domain }}
      reflectNamespaces:
        - monitoring
    - name: sso
      dnsNames:
        - sso.{{ .Values.domain }}
      reflectNamespaces:
        - sandbox
        - ingress
    - name: jrs
      dnsNames:
        - '{{ .Values.domain_jrs }}'
      reflectNamespaces:
        - clients
sops:
    lastmodified: "2026-05-02T19:51:49Z"
    mac: ENC[AES256_GCM,data:Pms1TURXGc++67jH9gHCBC4fXMM83qVPAYTOqu8AunfOUt4Fd0rv4caRy9kk9IzzRhpqBHRi3JHCAmDInZc4fbaukFejdN0IylXFPM5cJNA/TN6ynjDlOtqmG9Sjrhd0vrDiRC0i2p/yh91b/QeMu6JVhyfLg9r+RCLJMDuziH4=,iv:n2cDxr9KScToyBl3xv8c+VmEYu+ua4sVZomGGDzjp9Y=,tag:QD1ptKIOPP5Z9F4DeLrUXQ==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//YASLkwGbsSVkyYojZSTGItTLoW21qtgxMljunNi7qCgS
            Ow1oBDrcSqfGrAEd5U79Mqj5TiWlxAjnEx8UhYBczYbzHAPlEpK1px7sESpAvl+l
            7ZGS3IuoYWcxPOQTQiQCVITUrMMggXNGCZ2N1oc3Gkd1/A7CyuAtq5yJuuIGNB6M
            wNLDGP7yQDUGUKq91co2hbFv7Hmus1lBbt7xSqAfVeSADVrjpxdRZ1LsO2cmRw1K
            sOrSzR1Ed/Z+AF88kEh6j4d0a6gCQcJajP652rHT8BBp0c/mwataIj86y64wP2sD
            K51RxLTYeQKzfc+JkovOYWRb0wDqzLTP1J6LFeNtMF1yYZVv1KhW7RoEda+44Xl8
            ZzLsQfWmBmw1oUduy2ogy0Q2WRlaLAaAhz/sty8Rb7wWJUJzLBWNHEzZldTtO1Pw
            32/AtaaZMukvUvSoNshu94aUfHoFkWiU2aS5yv53jwsIPbwkbPJDCX/auIVJ1wRw
            zHohws8FKvgRZ1hDp+Qw9RRAx+8b0EB9s9Z7rskXnDHSW4dmA/rYpmwOCnRbTdXP
            6eDbk2aeo6zrSI7WOLsNmp+AEGTxdgdJzlRebd/j4Tx3k4FCdGDmJyUvGZdDYq9e
            /PLbIChKLZrFMAXcqFTn17ToaR51WU1NxtDivxaDYhB+8R32cd12UcsRLLsPQAbU
            aAEJAhC4jkjoBowfSk7eUVl66Lfay+qZnas5MxiDJI7OcHQh7VDjk+bf6W0SVnwA
            YdGyQ6yY1r9CKnNuOKjbnlyJVMfEIe5RkMnH6ijM0YeSJjgVmFPZg+sn1kPldqWm
            p2tajJGQVOtF
            =NxlC
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
