# --------------------
# Eclipse Mosquitto
#   - Repo:           https://github.com/eclipse/mosquitto
#   - Docs:           https://mosquitto.org/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
labels: {}
# label_1: abc
# label_2: def
replicas: 1
image:
    repository: docker.io/eclipse-mosquitto
    tag: 2.0.22
ports:
    - containerPort: 1883
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: ENC[AES256_GCM,data:+mj/ruOqx9zDHg8=,iv:rtUewbUK8257WXCebqLe2oj9LtHQghChnQY9Z9XBQuY=,tag:Of9PKhJypM70hsrlZRiZtw==,type:str]
secret:
    mountEnv: false
    stringData:
        pwfile: ENC[AES256_GCM,data:VCz5j1NyFyf/TR3dCq0fM6h/CFVGKqzZo+JfQGq/XSF55VIMYwe35e81SEQ/PlazvNEs2/4lrBV9k3GJ/5bMs7Cm2Elrp1zmcLEEF4YLwsyhZfu1lM+Jlq4THonmFgJcnb+Nczc1PEIh3/8Gg4qql1JyQUScsqM=,iv:148nNTFeGjgOsueNFiTR0K0SXo6AUx8iUQu5mYCTlJc=,tag:w7q1WfOtkUzIEoNjUCHB1w==,type:str]
configmap:
    mountEnv: false
    data:
        mosquitto.conf: |
            per_listener_settings true
            listener 1883
            persistence true
            persistence_location /mosquitto/data
            log_type error
            log_type warning
            log_type notice
            log_type information
            allow_anonymous false
            password_file /mosquitto/config/pwfile
volumeMounts:
    - name: config
      mountPath: /mosquitto/config/mosquitto.conf
      subPath: mosquitto.conf
    - name: pwfile
      mountPath: /mosquitto/config/pwfile
      subPath: pwfile
volumes:
    - name: config
      configMap:
        name: mosquitto
        items:
            - key: mosquitto.conf
              path: mosquitto.conf
    - name: pwfile
      secret:
        secretName: mosquitto
        items:
            - key: pwfile
              path: pwfile
sops:
    lastmodified: "2026-04-13T20:28:40Z"
    mac: ENC[AES256_GCM,data:uD1Qq9SX8k6dHB49VVDtyd+Dn5WhRq1aYwUjZ5oAmyvlCo7+lFz2jFq39xgB1EP85umYTiAzaCIsG8Q9zoL0XkCycDWeeJpO4PbMuL2MhrZrTV2xtmtgj/SFf/oczjGDyLMdGulQo8+BrbmqoThiHsYCs5Z9BDTcv5g1YuRnQNw=,iv:hp0egFLtfasl/gNPME0Puc7sJWCsrEAbGFZuIO37EtM=,tag:dIWII7qz6vsbI9fm0gQtBg==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//bpWEC5+8nbMXxT65R05Axc/KY6BHZEa3DKVt4Xu3S34j
            uiYSaOTOqHnk9mHFfJCG1a0Jexj7Q24WjlxZY/j8RuLhrG607jaM6yKbqZ7TLRLE
            wlIYwG0i6fl/lMqbfC3gPo0FMGSU7tuSKJLrHrzXbVGsb/9fAy21WB+xbkbqndwe
            y0CElcGAe9dijsMsV/ubZrcWDmaNXahD9HI34n1u+Ev/gvJqb3RPNaGZlUrmKk+s
            slggEZrZ5ZggvMJk0+LGP6/HAJZhgNhTrfQ3wGzfA2SiQ4n7/wdRngjWgl0TkRdN
            r4BQBRKeJRR4CkOvhCDYel4yA7jE3QaFqgy5gMmD/u8OUBJf7rMzKhmYi55PX1Sd
            mXS7ymjY2bFwwP2aryq1caZ2xVepyGfA00h2d1teaGTDZM8Svy8f8EUxf3m8OKZp
            fNf8fSb2VEX43ZUqxZqOj9+k0EXkc2lWFy1EJcrFf3yMcbsfpd6Dpak8je7vX4aG
            7BdLJ5wNGizAKOLug+01mq5oDs2y9fyIukjzschMV19VyjnNxylW151vUqRQIasS
            +fBwAWhmuNtyDJXutY0dU010KF89adjcAogrREZnpZg6h9Dv0viGBDfE8wtQpmqR
            HBWogi1IUvqRunQC5ha3D81kpt7EzdxStmVjZEV66uwPSvCXsW3pPgjBN8clYw/U
            aAEJAhBDlZubMWD3iiynLfaRhWCb5ahRbEbkN9i2qFHgP8nlmigdsOX5OPp5G8Ns
            ac4a5rw6PBsiLZ/aDh9kDHNIU1tGry41V7B8jd7xOWEm2YKGGLk9PA20QJnmWzzM
            UKX0W92AkJOZ
            =WIFx
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
