DOMAIN: ENC[AES256_GCM,data:a57nPkZqHx91XpLKwA==,iv:fEnL82qnqwzVAFaSUHU+babCZeDcF/0kh3gQgmvFVM0=,tag:6UZv17t16zuc+KH46XM4Mg==,type:str]
LOCAL_URL: ENC[AES256_GCM,data:Vhk36ZyKhK/eH3939NK3DhIHYZx667M=,iv:zExf5TrO6lpecdsa6Lk28PKWuKH6KiiOYC86boPYGbk=,tag:dU9m7gE5x9lfMYYyxAMzhQ==,type:str]
sops:
    lastmodified: "2026-08-19T23:44:12Z"
    mac: ENC[AES256_GCM,data:MgnNR54gS616pAft88Y8AjRSSIoFj+LoQASTkZJXoLGxtRQh8s193bh2sEONkgj7RkdnhLLjDW7a+/u9zbqpYuPvmAV/pBca4SxzDIXcC4oBdLfawgB0p+YLBiZAzlpccFdbrnVJ/PAKXSWmXzVA6HoB8glHe/d5T4fI6Kw/ZvQ=,iv:1WCbwH2h83w9fSJEdXbWRj20vkEKsXwa7GFuDlXN+qM=,tag:hs1egaAwDmHjFIDkfeVlRg==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-19T23:44:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//WeHmmGQrBz60yISbMkJavrEWaIqw+P/63cP9ZngUln9Q
            q6C6EvRpH3AZY5m2vfuAT3uoAf6szHrpbl7TVrkdLqdJejy8B+CIeOw3lqpFMLL5
            /HjTCvT+LUZoOhRW10Ts+v5QdEkASix9ZYQGUtI3UmRcIsj1FrG+Bre3IyqFUJTc
            4DxmgxxR/WbsuJ/YUCD7GgTAKoF2D8a9/9TeVYOrYnMiDrMohkSGEuu765QqWxCj
            8CXBG7tDc7VcwMDvw4TaxUnnaqft0fAK71+/LA0dF7tkaELcP53A1HvWHneO7MXc
            WZj0ypHdgHgCEW2RypDrzQe5B1alx65+WOF5AsLmbaIVKf3Jfl55/ECCfYyBtEfJ
            0x3xhZSrG/BdZcLaahSLNIsUqTt8yCJ98yLqAiPpvAc9jnsFK5C1fx/pKn/+hava
            BAjDl3CrjtVvKFQo+Os+PgCzvnvcKpQ5nVOB3f6g63GXmFThy/U4yvfGYr1P6/M7
            IJcnW1ZK26ZxAJXBSo0/LyOP8D6RU1C4zf8a34N/mtP3qx0tkDvuWqyLn61UEdNv
            54f5DZxlRM7lo2BkfpEKam87b+Fxn9EV6HPgqAPrOGj0F/CF/2RT+ctDCH5R38LK
            /ywAfCCXRKrbuf+rZL5nBwbhg+KAA8pw6mksULZspWde7oYwhfind2AxDvnbX4fU
            aAEJAhDgHbS5sR4hvsCdVG19jIdVTwG0VRxRe0kBHUsU8DUVohGl/bBMzMZJGei+
            notlU3XwgIzNmXGbqapvQ8MZ/hectCFiBHMyI3QptQ09YHjAxmqGK4HtOBhKvNTt
            9rzFctQdx6t4
            =8Uzb
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
