#ENC[AES256_GCM,data:EzfRQXQ7oy/HPxzk6p+RFdn3k926ywDTBjHuvfB7iFJhGZB2yMjID/LOxZjZncXyDI7V5Br5rU7lfB2TZ09ClI11aRyfFAXa,iv:z1WtDoG5KltUMdrcwwt+yiJS5JlFsFAO1hqKi+UiG+8=,tag:mR2PUj4leU6wsIaaD70JzA==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:SMeoid8n6b5Izm/TjoD9muc45dO2D7ZqW47EA1wNuvRrzvdbPqSJ6g==,iv:+Yn0aQmNtOQ1sCpq1qGNsC8vaYPX+DqpCxy/A4TkDjs=,tag:HaXDy6ctA6yH+BIMIc421A==,type:str]
DATABASE_PASSWORD: ENC[AES256_GCM,data:tvAVvMO484ixYc91x4Rw4ZqRjNY=,iv:a2bMbU06wOzQsl1DC+8DLW8C1K0zdG1PkfZ8k0ghONQ=,tag:6r4CmXQIha1Q2dpqZZH4BQ==,type:str]
DATABASE_USERNAME: ENC[AES256_GCM,data:mbqr2Taf9iE=,iv:26mhJyjcBCEQN5XASnWr/+og7cyjGljT+AoDiVvOB50=,tag:JFy66q1LTZWkLPJSZ+JbKQ==,type:str]
DOMAIN: ENC[AES256_GCM,data:eiOc4FSujhh+n9S+/g==,iv:en7//yM/GRCAQgVSVdMbFsE/NCCcX6pvhGPjLJfCg08=,tag:cCnBdQfs+cFSL9/UmuuBhg==,type:str]
sops:
    lastmodified: "2026-08-20T13:13:34Z"
    mac: ENC[AES256_GCM,data:NNQtH/3RKwG8BBb0SKDzQx3kE6iRSWc1D2W1/ot+ZOWjel+y248LrMi+UL82hQZiIiGJOvrAVNzeDGOaX0EndW6w7i9xdpv8y9JAZqtgwtA+I/8FXL/lQ4aOfcrKmGvfpzHGVsFHCdb7EBaw2o75i8Qar6j0KEkA7dEzyBSBXq4=,iv:nVHQgkq0rIJ7Re6jtwDX3dD9IMRiWtWO8JDYIvSBoRo=,tag:H0SJF6+InsPOXbJ1IcyxTw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAkkHvAA26CztYRY2ajsXdSlztqQpy4pCkLjWllPq30vg+
            CCo/z3cVm2jAHsE7OpQDuCaWV3vxvBAJxCpUays84JHXYYMAo7VgtgxzuzXnQUpJ
            Wbv5PPZ5arszLONtn0rtfsoUsdK8H44w92wEkrxfKyLUJ79eqysAASsU0p3e+I81
            Yry9706ZSadGVrQ4I7UeVljJWJSrvAnG11e+4godPkHXzvS/uN15SP81inGa2H/X
            MLY4yN1BzP5ppWAOI9VxWjmSzKb5lYpv8F8ydTJjEbkz5Hxt6LFrxrkiS/t0vexV
            WtN2pB9Qx92CMTD1ng4OQeNfbOa7Tf+oIPy4DbekqNmdwPzKbQ701lWlO9F08s5i
            jftEgnsrulsU4lusUorPTF6369tCstAaM2FOpr1DW9waGh6mDn0I7EoCZ+X0Imxt
            77BBQ/tj5cel3AFrK67lM8I17s8qvLjYrpmEASHVlcW7ZjoG3kyKJQ+jHlX45qyc
            TgMZQnU+09y/wwYTseZjZE1qJtP+31MO1XQbOulkR32RRjPfMrZ7Z/RQ+ZVG68if
            AsJi4I3fQRvB0VVBbnnaRZryTaBSti/AjLlbCHxVsf5c9j99JhPuVGTy2iUX1eAP
            BWf6UA7/EgtD3zy6dS0wLVIYJQOJ8qiOFMeOxLohoet6gL46VVFUKVjkV6vQqMzU
            aAEJAhA3X2UpT6dnsddiWCu9JKkQJJem5D4FtlQWOqPX2psQ0Km/TV5ZaHLDaGXe
            nQPU5Y5lyRJw9boSnqCTCZspogQ2ZupLSdp/6N/HIIUr/S677UuR8LIv89B7l2dI
            j0gSUbJSzlT7
            =dHwo
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
