gitea:
    admin:
        username: ENC[AES256_GCM,data:+n9j5t0CBJWS,iv:aynaS2LnMr3uxypjnRhPnn/qjvyGqAhspLpo4dhJRvI=,tag:6PDyS+jzKCYewvp0tvzH5A==,type:str]
        password: ENC[AES256_GCM,data:TRpg/Ld37XQ43hD8i4zhfn9KXzn3OrP2,iv:P7foSZKcaHYD/AzeNiDcVdcb5FNv0c3YZ43Ekp/CiVE=,tag:eNCTZOwVQ5mN/GpGYb5cxg==,type:str]
        email: ENC[AES256_GCM,data:4Ce1frDqJgNHzc1MePK6T5zvW6QHKUxGGgQfl0k=,iv:nBJtS9AQ7Xp6A5juKPdcuI7qXVHlOaOYucCbiS+PGuk=,tag:LBQtTy1Ot4iVX4kQtbSaQg==,type:str]
        passwordMode: keepUpdated
    metrics:
        enabled: false
    config:
        APP_NAME: Forgejo
        RUN_MODE: prod
        server:
            DOMAIN: ENC[AES256_GCM,data:iP6kw3uGvhqBKsYTJcGxrKmcQgeGJKs=,iv:VAPsban+87pPwo6SESIwhvIDwXXFzT93qfQOBpLZVFQ=,tag:krmlRltN6ghmHIARrysNCQ==,type:str]
            ROOT_URL: ENC[AES256_GCM,data:GyqjNEVN778IFCDWi9hGnkhB+cn+qHsf7RsvfWG4MbA=,iv:Y03iQGSikuFxe67fP0yrkLCgCwpPEq/7nwy+GXBEcVI=,tag:gQ6l7Lwogeh7WI+EspxsBg==,type:str]
            SSH_PORT: 22
            SSH_LISTEN_PORT: 2222
        database:
            DB_TYPE: postgres
            HOST: postgres.databases.svc.cluster.local:5432
            NAME: forgejo
            USER: forgejo
            PASSWD: ENC[AES256_GCM,data:t6Ddt1LgmlkQzi+m+G+68+ILcfM=,iv:XzekhOt6dZZnwKiS4ze37/nJwu7pPzCUkQf5M9zIMe4=,tag:yDYj4lk5RVnKJxRNknwmYQ==,type:str]
        actions:
            ENABLED: true
persistence:
    enabled: true
    size: 10Gi
ingress:
    enabled: true
    className: nginx
    annotations: {}
    hosts:
        - host: ENC[AES256_GCM,data:oaENyo8T+GZ7yuxHWcB8Xfk8OaZDZLk=,iv:vFVlJyeqYyTwhzU3fz3X2MudTDMfoGUqv5+tzgZSYXc=,tag:O0RvC8wiCFd+FgS3vWP9Ww==,type:str]
          paths:
            - path: /
              pathType: Prefix
              port: http
        - host: ENC[AES256_GCM,data:nHhtPajDNMX/IGfgLaRyIr9egM6y5Q==,iv:ERt1P7a/d6jyQaRERkeVwd4KrnMu43AvFV9IgyJGebI=,tag:7N4bgIcQayAGQHeTUBfcLg==,type:str]
          paths:
            - path: /api/v1/repos/afonsoc12/homelab/mirror-sync
              pathType: Exact
              port: http
    tls:
        - secretName: local-wildcard-cert
resources:
    requests:
        cpu: 100m
        memory: 256Mi
    limits:
        cpu: 1000m
        memory: 1Gi
sops:
    encrypted_regex: ^(password|PASSWD|DOMAIN|ROOT_URL|host|username|email)$
    lastmodified: "2026-08-18T21:19:25Z"
    mac: ENC[AES256_GCM,data:2wdm4GFLvUmKEbkDrw3tolDQBgj05DKVaQnUNDw6bHmdklTZKqLcawYTimlYS+pihXgahUUJgGeB/rNKb/2kdb4bJSlfP+QlC0Rl8Z0ozsOnG8SiQPEuIhAoI/+l/CAC4PGnpUK8G+w9/MSWpO0ZF0lQG5vxEiKn2tB0SNFnQjs=,iv:iMoxgY4zScZhEHV6xrnvxuLOoAWI8Y8cF2Hh6SRbzcg=,tag:1kkrJhutAypP67ZIwWFF+g==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-18T21:19:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//VSGsuF3MU95S4TiE+J6FbyWM3oO+HAcuNCeBOhX6dXGj
            A0Hem4ZI+CDmoFEPkGvubDjY0ddrI+mYGcM8pmeIHOAeiyE+9AheIn+/4KDtoA7X
            PGlVFSF99srx6FqrCrM9YmiWDOWAkr1xC4x1cq1kE3RoK98CY+upOLDqxifLY9Lx
            A4hIegpihS1GmOEPIck0JUvTB3dCKHTZ0dwF3fHdEY/xRGQNmGKigoxTjoygJakp
            fn1zFq5/uV2KauvTH4/LqVyTmqBi34pO/HZxiYyf+WIfOW342td5Eq9dzmsSv8BR
            0ftO0Fww5fqGjeT/37Evo8nvu5PK2Vbc6d4isuxMDE1Bs5n/Kq+LvUXUp1AarGtz
            yLPsJz9o9WJoqg9hgs0fecGEbuSMAPImhlyytG1XAeO0S3qvwX6ScOXoAx1e3NIG
            2LU9nJ6w3TURO/7LuL3h0FUldcKGmz4hSF3vFqYW1kuMffZlqknwXDlEPQ0CHy+6
            w/EVtYUUmUpFhSdzdRWHIamo53bCYxKdTLcD2h/39Hl7xWEyoAgrgxB6kBsuctr6
            LvNVFQIA7JaDK7o1bfsyuxRnnyV+zwGwqgZWiB6rjsmN5wAt2Ul/cm8HhMa1PYZH
            5t7OQIMSxHF8jW2G+rD6qluekg8vLmNL/Qlnhj9U2WBLEqxmrmnWGAIhvCpdMZbU
            aAEJAhDASoKIT6FoZq/p+fNB+X1mlCifcdFsLhUGHf71DhFsSFzns6GHYfy5wA0C
            roKlkJrtmFTLJWRifnPxlW1pT+W/QGgEhVUo3hTxwi/1ODCsk+fiuTg0F6i19zxf
            3aAZ99Bb0zG0
            =8KYz
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
