gitea:
    admin:
        username: afonsoc12
        password: uuiLykVw5Di5AHW86cE=_DoJ
        email: afonsoc1997+forgejo@gmail.com
        passwordMode: keepUpdated
    metrics:
        enabled: false
    config:
        APP_NAME: Forgejo
        RUN_MODE: prod
        server:
            DOMAIN: git.local.mydata247.top
            ROOT_URL: https://git.local.mydata247.top/
            SSH_PORT: 22
            SSH_LISTEN_PORT: 2222
        database:
            DB_TYPE: postgres
            HOST: postgres.databases.svc.cluster.local:5432
            NAME: forgejo
            USER: forgejo
            PASSWD: vb.AKEqXPTP_b6A^<LRb
        actions:
            ENABLED: true
persistence:
    enabled: true
    size: 10Gi
ingress:
    enabled: true
    className: nginx
    annotations: {}
    hosts:
        - host: git.local.mydata247.top
          paths:
            - path: /
              pathType: Prefix
              port: http
        - host: git-hook.mydata247.top
          paths:
            - path: /api/v1/repos/afonsoc12/homelab/mirror-sync
              pathType: Exact
              port: http
    tls:
        - secretName: local-wildcard-cert
resources:
    requests:
        cpu: 100m
        memory: 256Mi
    limits:
        cpu: 1000m
        memory: 1Gi
sops:
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    lastmodified: "2026-08-18T20:57:10Z"
    mac: ENC[AES256_GCM,data:x2yGxrAiKqcXxuX4F052e0Md/LNQ51DwwUC4J0WtOTOZRbXtpLvvGHQ8CTWQCkrJoEfVtUArXznfTq8e2dQtmcdnO6jBe9O1LcBWWj4AAm/Mz6swoCrlA8lu8poDechDX8+vY93mWkR4FsWXmuDPLyKCuxGQZZTUS1kTYgUQySs=,iv:o4QNLKOpZHQqSL0NJGJSkKF7HknHlN198cmaLhOlZr8=,tag:FIi1QMb13NepwyTxcPGWNA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-18T20:57:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAo/KGpFlNGot7N05+TcQYBqXsdCSJbppHPDrH0P6uTSKR
            +A6kUsZ9JMTCCp4thZi/78XYDZ2vwqq7gsTVztD+A0bA6aDW/cj40ds1tUFAnKKJ
            9j1L5JR89ZpuOruzy4I44Ay5B+RjB0K9q/70G25qkXYSH2ceGOquc3H+xEIO/eyx
            +lM18rmpZ3ZSTbut7jxFMPnxbLY7Xbme3YgJaSWLAVHlPA63WxdQ/7dppnfGtHnC
            EBceGIL38dHNTEEoQgvCIymj2ZK0ywSnxRHnYgoYVxTswGJh5X0MNYDJcqIjq0yJ
            AlsKX1ynMIXZXI1I9YeaIckk0fgibin//oJIM6/BZ6EgeM7mJrZxh45GvHkiRMJV
            EdzhhttfCRR8bXNWzPf6+QCpWb5PQ1RXWohj0k2fhN5E/rrytgn8dak0YQMHavVU
            zYkoTSBMfpVsg8yify3GCK2g3vNeyRkkcxgkvZPj1Wr5N776EgHpFHCJs5U4Mc7q
            ZtBjZh5IuWrS4CAwy+EqUTeN/+LekpivX+6n4UjSfMbzZIulNrVYArRw8umC4XFj
            FTALyV7Ma8Vst3I2id8eMb8M/uuil5OBP9mvItm/1PwStZ1/hlMiO8SXTAnGAnMr
            BUDZNsgOT9Kn37Ts+0oZ4pHLXZz+jijuT7i8R2FJbiWf1S13M0EZHndC0ieOmnrU
            aAEJAhBgP15BNYlgkfLaqdJxLTWH2ZOCntHEZ8I2RrMz4Cbb2nQ24prcI/gEUzf5
            4NBu3HJDE+ovuA4e/LnEaPV0VIYTL0N6lvCB5/v7GsA/bgje66WswPxeZa7SUnte
            g/B9N5IC6fHp
            =6333
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
