# --------------------
# Paperless-ngx
#   - Repo:           https://github.com/paperless-ngx/paperless-ngx
#   - Docs:           https://docs.paperless-ngx.com/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
secret:
    mountEnv: true
    stringData:
        PAPERLESS_DBUSER: ENC[AES256_GCM,data:XhxcJHmHGgK4,iv:2LL+R+bH1+1oOUOBWYYaL/CSnYsX/q+s1kwKVPL6GgA=,tag:TZmin8sMVj8eOU3rK8rGAA==,type:str]
        PAPERLESS_DBPASS: ENC[AES256_GCM,data:7VNtikzv1eMHawmg0pmWQJUVvYA=,iv:NLGl4p0yAr9KvI56zyfpurGnVa70u/9M+4EAHmnGsXk=,tag:WuEcKe3IOleK1o21SpFbjQ==,type:str]
        PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:mwCz4LTATThlC/7awXNAtORo7QQibMu5pO1vBKspQTvoPCOpvzuYVfekv7oZF+o9z+bwOy5CcJ/tMvEUXcT3HQ==,iv:s+w/Wn8rWPv5wRWlkTqaOwdWjQVACFeYLNjWgbpZoPI=,tag:HCYt4HP8ElQi/a0/sFMiTg==,type:str]
        PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:W0WBa/FY,iv:KyrtD2McuPutkGJ0YYPDMI7yrOKtiQPGRIOU2svWdxQ=,tag:XDhMVdtURl3RhGYD+eCqkA==,type:str]
        PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:QxYiCWI5lJJCkQ3oESr4eQyP1FTrDzU4,iv:DuNspets5IW8xhTIUz7aJbIhu0FKcA/zsiwXXXSHd28=,tag:CSsgKwDkzsETaawtWOvIhg==,type:str]
        PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:9siJGxNZcDZWA9r2PLbp7oSuncL9bUThO2w=,iv:c5eFb4QKhB7l1albX+jL/aJGplhwEYzcGtLPfVEuePY=,tag:TMPZ8y5FLune7hEkQc2Buw==,type:str]
nameOverride: ""
fullnameOverride: ""
labels: {}
podAnnotations: {}
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 3.0.5
    pullPolicy: Always
ports:
    - containerPort: 8000
      name: http
      protocol: TCP
      service: true
service:
    enabled: true
configmap:
    mountEnv: true
    data:
        PAPERLESS_URL: https://paperless.local.{{ .Values.domain }}
        PAPERLESS_DBHOST: postgres.databases
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: paperless
        PAPERLESS_REDIS: redis://redis.databases:6379
        PAPERLESS_TIME_ZONE: '{{ .Values.tz }}'
        PAPERLESS_OCR_LANGUAGE: eng
        PAPERLESS_TIKA_ENABLED: "1"
        PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
        PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
        PAPERLESS_CONSUMER_RECURSIVE: "true"
additionalContainers:
    - name: gotenberg
      image: docker.io/gotenberg/gotenberg:8
      command:
        - gotenberg
        - --chromium-disable-javascript=true
        - --chromium-allow-list=file:///tmp/.*
      resources:
        requests:
            cpu: 10m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi
    - name: tika
      image: docker.io/apache/tika:latest-full
      ports:
        - containerPort: 9998
          name: tika
          protocol: TCP
      resources:
        requests:
            cpu: 10m
            memory: 256Mi
        limits:
            cpu: 500m
            memory: 1Gi
volumeMounts:
    - mountPath: /usr/src/paperless/data
      name: paperless
      subPath: data
    - mountPath: /usr/src/paperless/media
      name: paperless
      subPath: media
    - mountPath: /usr/src/paperless/export
      name: paperless
      subPath: export
    - mountPath: /usr/src/paperless/consume
      name: paperless
      subPath: consume
volumes:
    - name: paperless
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    tls:
        - secretName: local-wildcard-cert
    hosts:
        - host: paperless.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - postgres
                topologyKey: kubernetes.io/hostname
resources:
    limits:
        cpu: 1000m
        memory: 1Gi
    requests:
        cpu: 100m
        memory: 512Mi
livenessProbe:
    httpGet:
        path: /
        port: 8000
    periodSeconds: 30
    failureThreshold: 3
    timeoutSeconds: 5
readinessProbe:
    httpGet:
        path: /
        port: 8000
    periodSeconds: 30
    failureThreshold: 3
    timeoutSeconds: 5
startupProbe:
    httpGet:
        path: /
        port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
sops:
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    lastmodified: "2026-08-20T20:33:03Z"
    mac: ENC[AES256_GCM,data:MP4+2vdS3pabqUHOXSjWocVMH9n63U5VE5I9tyF83iLgtdLM5egmMiN+ztal27pmPd2FbBpgKB3+BoqWxe6JbZ0YhUua2Ue7YsuIFs+REtnA7Gc8fjuNdq7d0bvtFad7XkKklbXID7nRM7SQAEr6RX7L0wvZnLkUAWPhS/IFxic=,iv:JBugUpMA3h1QOLYPLsLtFryTiJ8OGPHd/Z8CJltMgr0=,tag:vUGG7HomCBTDRehccJpPIg==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T20:33:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//Yve/mX4uwDfRKzumt3jU/Xi4c1hQp3ktbAyOR0i0nsA3
            jV0ObmsF/TSuExtH0cl+yWwaB9XqHkhUzemnoX99iBfmOMQJaEGTwxZpQR6StfF5
            6iLXdH3oLIx2nzLbpIUgdXWKi/4dhefwna2aIlWMgjup5oQWqeYsV/X79Xwy9lJl
            CODSJpDgzlhSuy2oC6PTPm55MkDtAp9XDoEII43stEsa8be/Gc6rRaF81vNYySzV
            fU1YmS1kgFZiTJfpEXpdJCD9Fzfi+BwDV5zqAk8v7c8ltZ6P561jbd00FKi/Aacc
            xH89slbT/bAg93bkWUjHjj0s/Axp0cnvFxB7JMpMoipvJumOmK/ZYBVbEzWidw/Z
            aoijHF59kvwHODBYrtDSnRkjqSqZC8oggpkV+TFq7ZM4agUuwz6uFTFuIi/MXSD0
            nnVJst7ZiFB15N1QxsydcqLHOoOIiV/qmvg3CruzHze6C5Z81V6ACcZWmOOA8/5j
            1Y/SmODJkL8KLSgPyGt37dJJubBF7JslbUjy+VCov0Qf5GaenaV/gHRWug4T2G5+
            ysk9QaJpZ0P8iX0lFs00qMpH7jmyqZgk/1h9ao3Q2Haf6vkN5u1DiE5pvdAvZ4QR
            svObsy4caAQfl6yq+g7YDwZhUfskFIE65pXjSLSiS/zJLZeTke3jNPHoMgptr7zU
            aAEJAhCYxptI5d6Eck9+dwP6GP48jcm3uHFKpGwdkCM2L/Zz65eQYSimV6cmSEwv
            SilG+DnfWXpc2oKu/Y67mWBRrJMvsDM9KDv6xVrS9940RKUmplQ/FWU/KyIPZDPT
            90QdXfaBCCWU
            =lfaM
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
