# --------------------
# Paperless-ngx
#   - Repo:           https://github.com/paperless-ngx/paperless-ngx
#   - Docs:           https://docs.paperless-ngx.com/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 3.1.3
    pullPolicy: Always
ports:
    - containerPort: 8000
      name: http
      protocol: TCP
      service: true
additionalContainers:
    - name: gotenberg
      image: docker.io/gotenberg/gotenberg:8.36.0
      command:
        - gotenberg
        - --chromium-disable-javascript=true
        - --chromium-allow-list=file:///tmp/.*
      resources:
        requests:
            cpu: 10m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi
    - name: tika
      image: docker.io/apache/tika:3.3.1.0-full
      ports:
        - containerPort: 9998
          name: tika
          protocol: TCP
      resources:
        requests:
            cpu: 10m
            memory: 256Mi
        limits:
            cpu: 500m
            memory: 1Gi
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        PAPERLESS_DBUSER: ENC[AES256_GCM,data:DFWydHKEXFc4,iv:XjpzI4HP3HC34xllqeg8lYcM1PRRik/tldS8cn9Gqbo=,tag:2wCQHsyno0VpuGyrZ1wrLA==,type:str]
        PAPERLESS_DBPASS: ENC[AES256_GCM,data:oh6J/tYiDw/11jTa3kl+0Jt2wpE=,iv:SRKNvPOTlFprZZyRaWE8PlQAgRbMMkIaxhHzMWOhb7Q=,tag:5xmp3rYjdQSgmOkiAp9/Cw==,type:str]
        PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:pAGFdg8mMA116ZLQX53xiEZI2Kks5q2BG8iczwevtDo/qdbYUtRB4tVj2DbMWfuS6T+rddy/hNvQAY6Syx5KYQ==,iv:d7bAnig2FXaRst0Gyc0D4i+iBHluos6HEzXfxt+rq0w=,tag:Lrh+3ct6o7yKKI4jxKljIg==,type:str]
        PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:9VL8Z6Oh,iv:fFTMC3+RrY3fi/IjIXg0G0DOsPifa4YIKYvvUUJeQ4M=,tag:rUUOXwKv8aWY6qm1DgMHPA==,type:str]
        PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:JmAr24jAlM4CfjS81OfOIaILuYY1FWFf,iv:qSgTDBB2Hk8DyVHK1wAfl0uKcrDIAXnsUF+d0vw3rGI=,tag:Ub4UcVh4h5vL/XiW3bQSpA==,type:str]
        PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:ale4O+LXAJw4WmRCgdK//C0pmyiGH9RJ81c=,iv:Iq7Z7oeqXdOnx1U3dchFnuXEC7HyGD6Xx6kjZdgRsWw=,tag:mzPtXddnGbULIOGJyVPNBA==,type:str]
configmap:
    mountEnv: true
    data:
        PAPERLESS_URL: https://paperless.local.{{ .Values.domain }}
        PAPERLESS_DBHOST: postgres.databases
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: paperless
        PAPERLESS_REDIS: redis://redis.databases:6379
        PAPERLESS_TIME_ZONE: '{{ .Values.tz }}'
        PAPERLESS_OCR_LANGUAGE: eng
        PAPERLESS_TIKA_ENABLED: "1"
        PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
        PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
        PAPERLESS_CONSUMER_RECURSIVE: "true"
volumeMounts:
    - mountPath: /usr/src/paperless/data
      name: paperless
      subPath: data
    - mountPath: /usr/src/paperless/media
      name: paperless
      subPath: media
    - mountPath: /usr/src/paperless/export
      name: paperless
      subPath: export
    - mountPath: /usr/src/paperless/consume
      name: paperless
      subPath: consume
volumes:
    - name: paperless
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    tls:
        - secretName: local-wildcard-cert
    hosts:
        - host: paperless.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - postgres
                topologyKey: kubernetes.io/hostname
resources:
    limits:
        cpu: 1000m
        memory: 1Gi
    requests:
        cpu: 100m
        memory: 512Mi
livenessProbe:
    httpGet:
        path: /
        port: 8000
    periodSeconds: 30
    failureThreshold: 3
    timeoutSeconds: 5
readinessProbe:
    httpGet:
        path: /
        port: 8000
    periodSeconds: 30
    failureThreshold: 3
    timeoutSeconds: 5
startupProbe:
    httpGet:
        path: /
        port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
sops:
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    lastmodified: "2026-08-20T21:26:58Z"
    mac: ENC[AES256_GCM,data:pbqoj/R0pIVH2fvy5to6IUjaVadZMfHqHTct9B1MtViHCLdCCaAZ2HZ6/gwF7SqLX/MKPpkJ4wNb6dyAMDgYe7RUFZOrvFmrywKbevClkHEdurknbWJOoIFjDFR94KDqKZxcvtKoQ9b4BJdUx6+rxK4Fohx+o9NnuW7V01rO8x4=,iv:t5+9rknWBHloCl8mU4pscWNw98frfDx5AkGezCA93VM=,tag:ZcmSoKpHLT/l60+o+pKQgA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T21:26:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+K2zg6BrEKVNR22bxbIsiRo1MjloExJhF8UpXNMowV2DW
            +HxzMpbhYRw5YZw7v26/a+XQmst1RvzbOc5mTCDSMTbme9Y/eCXU1p2tcKbAaezS
            bZjAwQ7Eydp1OLzKz4QNzK3mhrdzj7L/VjKqLLmcUhGbDkwmPUMUkwHdnOdwbeK3
            /J3V+UuD8RvwL6KKyzqFmuY8QQLqFpfMz3ZXICCvPjvzh60SW0nj4Wd9FXF3/jtV
            6hhVYCW+VyjUsY+wcEhWHw4uQL0y3cTo88SUWDgF6ipsKgfhk39pU7ehXUXwzNzq
            CbCjgmZKPNewwUFSTrv3X7Uo9RpXe8OO7d/HofKwrhvvFj2JqgMXCDSkPMzsMbVi
            c/eyP3Rw7JAfOg/aZMvh+pujxWl+2PNwvmTx5pi9MLVQSbVxfDEcw/bRrMFNmi6m
            MIwDMHnjh6UMV9niEacAh4NT2CojGeJL05jUXlriPqx4kAWdJTL9zDGhZwxJAAuq
            NRPNmXbtvGL8JwoJvB4dwzwzH0q4WYHzaBGSx+Kg1wTAASsh2gKfY5w8c0DTddZJ
            UxON2fNYe5pjTrPgiKoN2MRAqFMGXV7UMW/xr4K+EH2xPTRACQMJ5X/ZZUNqsNgR
            beXulgbsnP/NF8GvsWyaeXdkdF4ukYXhypDDYCJ0EcSHUAyyHPCAoi5VhDOg6GDU
            ZgEJAhDv6FGGQPlkLzIYACWaEh4b4uaz/4lyFi4JqzYBfUkwqaXGmeHYP6uHoDDG
            F+AUPGMy264l7rLU1GNAn67+JYzluBtzGRkeYew6mIYf28BFQQvq6SCTfkw1bZgT
            +GwcUgm7ew==
            =E2Eq
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
