# --------------------
# Paperless-ngx
#   - Repo:           https://github.com/paperless-ngx/paperless-ngx
#   - Docs:           https://docs.paperless-ngx.com/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
nameOverride: ""
fullnameOverride: ""
labels: {}
podAnnotations: {}
replicas: 1
revisionHistoryLimit: 0
strategy:
  type: Recreate
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: "3.0.5"
  pullPolicy: Always
ports:
  - containerPort: 8000
    name: http
    protocol: TCP
    service: true
service:
  enabled: true

configmap:
  mountEnv: true
  data:
    PAPERLESS_URL: https://paperless.local.{{ .Values.domain }}
    PAPERLESS_DBHOST: postgres.databases
    PAPERLESS_DBPORT: "5432"
    PAPERLESS_DBNAME: paperless
    PAPERLESS_REDIS: redis://redis.databases:6379
    PAPERLESS_TIME_ZONE: "{{ .Values.tz }}"
    PAPERLESS_OCR_LANGUAGE: eng
    PAPERLESS_TIKA_ENABLED: "1"
    PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
    PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
    PAPERLESS_CONSUMER_RECURSIVE: "true"

additionalContainers:
  - name: gotenberg
    image: docker.io/gotenberg/gotenberg:8
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  - name: tika
    image: docker.io/apache/tika:latest-full
    ports:
      - containerPort: 9998
        name: tika
        protocol: TCP
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

volumeMounts:
  - mountPath: /usr/src/paperless/data
    name: paperless
    subPath: data
  - mountPath: /usr/src/paperless/media
    name: paperless
    subPath: media
  - mountPath: /usr/src/paperless/export
    name: paperless
    subPath: export
  - mountPath: /usr/src/paperless/consume
    name: paperless
    subPath: consume
volumes:
  - name: paperless
    mountPvc: "yes"
pvc:
  storageClassName: longhorn-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

ingress:
  enabled: true
  authelia: true
  className: nginx
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: paperless.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: ImplementationSpecific

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          namespaceSelector: {}
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - postgres
          topologyKey: kubernetes.io/hostname

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: 8000
  periodSeconds: 30
  failureThreshold: 3
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 8000
  periodSeconds: 30
  failureThreshold: 3
  timeoutSeconds: 5
startupProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 30
  timeoutSeconds: 5
