# ==================================================
# Connection defaults (all hosts)
# ==================================================
ansible_user: ENC[AES256_GCM,data:9FisGriv,iv:bbLPjZA9X63UVHHmPL36EHQu3+7n7E6A0if4XuwmFA0=,tag:0WEKY7CmnJSvJKciNOoN3Q==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:KkoBnrFBrnKqTg9lXvGK/AQSMg==,iv:rDSRTxCcCVCq62l20W+PFudH9o3EnbkyQkU37nvc0a0=,tag:3gZCDIs5sdTrp+PRQI5bmg==,type:str]
# ==================================================
# Role: tailscale
# ==================================================
tailscale_authkey: ENC[AES256_GCM,data:GG1tW0EXk86nWg/jX6hXIb0hP5zHStHj/8mkk60x3DYfruj6LY4slHbxhX/v/ua64nHi7vbsw5VKUYpqCN8=,iv:VyI1gGdTnrmvxsfWOAGztpklgzTbe6P7KUNwd5dRir8=,tag:49afwdcUZOSXC0kejGiYyg==,type:str]
tailscale_version: 1.96.4
tailscale_args: --ssh
# ==================================================
# Role: maintenance
# ==================================================
maintenance_base_apt_packages:
    - dnsutils
    - wget
    - python3-pip
    - nano
    - cron
    - inetutils-ping
    - iperf3
    - net-tools
    - rsync
maintenance_base_pip_packages: []
sops:
    lastmodified: "2026-04-29T21:29:19Z"
    mac: ENC[AES256_GCM,data:mJSc0xI/v3e0AzDIalEd7RmtSd44Nc0FYONrrdDuJjqHxi29lDkpalGNy9ptl0yRDMUwbCNMXmiuslj33Rx5ZtE0r2sz/WC7QHWxY1Ctw+RHR7M6q6xjgZtG5tbePg6c1Eqm2yPJpgYP7X9T6ZwYEttkRIzgeFaWcXI+W7IR3jU=,iv:t/a+Cv1QGjwyQwonGC4gLUeq+mK/7MsPcYr2wrGKI/I=,tag:zW4gBlnFyiFZMNGSC+NJZw==,type:str]
    pgp:
        - created_at: "2026-04-29T21:29:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//UfdyW8V2GAZontQg9W4qzYX0WuaeV04jY8SMfbuXcKSi
            4a1yktid0Kz69fAv1InVctKX1D8Z2FYaoLnOcvMgmB+aKX5K1PTi8lRS3jQFZhjb
            whPaEXO7/zDzRHUffGg0ks4FnXrlEyV342kc7dBfmXUrt2hAdDENnjgs6/ZnNx4d
            cRZg2uF5nyhkR0GF4sROmQCwxDpXIBrbJsgYH9nKc4URGKNzzYdisC1W2/Brjqmo
            MWOgHwGzVdjKXq4yjyV+0ZyvGC9ZztF1O1iCfTpUwP5ABXOlp5tG2zQi6DEEHjmP
            bz5CX1aznW5vyr4JTlY9bLpbchJe7wedO1dLooKBFvDf9XfpmPeL/641TmABiw+G
            q03ezjODVFxPIQ/3yp9f0ITdQKc15+1EQr6gRw7EszYIhJUFxUXO4LX3y2iydoS9
            Qykftym6md/YNQLoPCkVua5UY0CGNHJciTteFovtlKWhUYh38gjvBRmYLKd5xMOf
            e+mNsIuD9hfeYtsjdnKmAQ6p9RxDcIGGYxwyiDm2LwZZG7d/Ttn8N4NB47Gst7d9
            wOAXz1i6hjxPm549noBNOSimv7YwipQs2nLc3/TmB2YPafc0DHKQRmt0FmdlY2fa
            89r3x6wTpLBHUaUwE3a7/wrp9vFjoZhJhJbL4C85/yd/q1dMXOYxdzHAGqzwcs7U
            aAEJAhAlyxjyzOKReQu7Nd0/y+uxrR2RKfOs4qKK3V0uMW+kct9XKVL446NHY712
            K20MIvwVVmLRBA5dSV+u5GwX6aIhQAg88pSaAXdvJBnATAtc8PkEwgKmorIG+C7j
            EKOLhGqeKuNv
            =mQ7M
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(token|api_endpoint|tailscale_authkey|ansible_host|ansible_user|ansible_ssh_private_key_file)$
    mac_only_encrypted: true
    version: 3.12.2
