# --------------------
# Longhorn Resources
#   - Repo:           https://github.com/afonsoc12/homelab
#   - Docs:           https://longhorn.io/docs/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/adhoc-resources/values.yaml
# --------------------
secrets:
    - name: longhorn-minio-secret
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7x8Z6ksQDrTK2liaCw7LShiGi7w=,iv:LtyxaFTNxp5wUGg5w1KthZciPD8ksqpkzqsQdsj0hFA=,tag:16MyKIjc1zCY/Wvje/2QoQ==,type:str]
        AWS_ENDPOINTS: ENC[AES256_GCM,data:BXxUZB04dF0o4sapaGoihdv1OyjD6Fl6rQ==,iv:fzL+ZRWRIvon3ERG3sQbzhe29lUK4VSDw2B9LicTJHA=,tag:/VOhTwxRSZAUTJoi5iqpqw==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qnnOEOlv7/lVLbeYQKYJ3rY7u9B3ASngtsU3PpQC+PVUVSCKWtxWsA==,iv:Vip6Ea6WzBfSzPjGUfWP7f4sMKjlppf8zxwZtLZJhOY=,tag:WoM5V5d55MV/sj/pp6ljmQ==,type:str]
    - name: longhorn-backblaze-secret
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:akRv8qJwmkLfuswtEDvL945BsGZH5ubKiw==,iv:1O0/dwz6XCRdT1ONtuuQWLEvIC7ds9YNZav168qQ/80=,tag:pzyYWo86mzpAvAxenzZcFQ==,type:str]
        AWS_ENDPOINTS: ENC[AES256_GCM,data:YIWNPbjE/0FhfNxZd3aoDUdfRLSVwUtUQJG0y4yHQJc0a95yJh3Ji3A=,iv:3uFkimG2LjwxJt0HDvKDGqsdhRUh3ah367NF6w4gQjU=,tag:c2zUd8sqXkXBpsTBX0sqaQ==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Mr6O0sxAkxStNqgVVhKVREs4hPCgdPm0QXKnFTK85w==,iv:sNSO72nbY5b7/9yPlC2m3ZYD5nyzQlkw01oHrYijanw=,tag:NjclRGxEb6wil02CAhXyfw==,type:str]
resources:
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn-persistent
      allowVolumeExpansion: true
      provisioner: driver.longhorn.io
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      parameters:
        dataLocality: disabled
        fromBackup: ""
        fsType: ext4
        numberOfReplicas: "1"
        # staleReplicaTimeout: "30"
        recurringJobSelector: '[ { "name":"bidaily-snapshot", "isGroup":false }, { "name":"weekly-backup", "isGroup":false } ]'
    - apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: bidaily-snapshot
      spec:
        name: bidaily-snapshot
        cron: 0 */12 * * *
        task: snapshot
        retain: 14
        concurrency: 3
    - apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: weekly-backup
      spec:
        cron: 30 21 * * 6
        task: backup
        # groups:
        retain: 4
        concurrency: 4
    - apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: daily-backup
      spec:
        cron: 0 4 * * *
        task: backup
        # groups:
        retain: 4
        concurrency: 4
sops:
    lastmodified: "2026-04-13T20:28:44Z"
    mac: ENC[AES256_GCM,data:vB0OQV3pvONJfOzB9L2O7RxUSaaTxlXBAS6K2Av3HZgdJtIpZ+YpaH8U6oa4zCRYa5cCKzND0LhGgUP6bdXFYqDeF0hkyPbum0MWpV1XNmWrJDOpoYlW/RnG4vDIN/YBEEQt3DDwXW3tc74QWXlAO65RvD8exDlqgMAoIq0wDH8=,iv:SQmBmt5AeNNxcMiz9BT22XWAETSQqhwfZqNLAh6y2Jw=,tag:QF0HzZK/ICCyKiYkI54F9g==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//UovQGlYWG5LqKM1SsOoaCBrJv3HYGnK7JXImWvufZMEf
            LFFpESFGIbZ9DBApoUZ+eUocxR3ZMiQOOH0v3ckhsmgnOhqUXxi+V/eun0kELvv7
            z2q2+EILM+tT3xP+AHEirD/ToYKvkH6Mp3beYduK+cQ1ey0T/gvl6KhfumLaB3IX
            lvWyqsNFOgpxtv15aznbwNNamZVvC0GnpZJalMTWtj0Tt5+dnKZ4sCxmlglSdb9F
            hTitgr5VQomF0uh/l/0a4nRgxB0iXsIzkrAGisglPmpKneg0vBKwHpH4icBRAvKD
            fR5ey/SG4faiTWriCU1ddYXLWvmWbDhOY48AYa5CYqjf9d71tITTHBdREPVSarat
            95d8yi2RwD/ixVmHtKS1qhMXkDUDiMJqyRDwU2IDrhL/SAY3Ziv8nPMoKlbXx94m
            doSvFxLo1fSo495iTQKqZE2SqXmIOmEZ9DY0dl2DaAyWFYY8Hah4wx4hSTAeWRQ5
            LA89XZsn4ct9LNRJ6J+fVNIQSlSeevbVqqrIo8ehR3FbmPpUHPcbIO80lF7m02ew
            FMaZGBom8gGeFCOuhYwdxi4lpf3W3oidQfbQlZLVNOOm1VZgK92cbKPu/B+FJZws
            2avM2YLDPKUWITCgyApdST/0PvBUompcw5tREdQ030S74KMp7ri5VcAoF8boFknU
            aAEJAhCvJpWlJmxVoNZl91h6G9S46WqKC0khQ+8uUdr2TFq2Wvy7oH+bRcFdn0D4
            neVESYJq2m6M+CGCEKEFt39yn3y3HEKqvx5d9kZxNo0tZ3hzoWpcKAOb/UWGQra4
            74o8ojtfxE12
            =4BMz
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
