# --------------------
# Longhorn Resources
#   - Repo:           https://github.com/afonsoc12/homelab
#   - Docs:           https://longhorn.io/docs/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/adhoc-resources/values.yaml
# --------------------
secrets:
    - name: longhorn-backblaze-secret
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mbHEqw906e89Ll7zAlDYyQd2HEdThdX3Qw==,iv:t70nYBaiq2R4KbWHSAvvVrztK2ueNmih76igxArQTqU=,tag:7xuScTf9iZP46RCtZQ9fJQ==,type:str]
        AWS_ENDPOINTS: ENC[AES256_GCM,data:YIWNPbjE/0FhfNxZd3aoDUdfRLSVwUtUQJG0y4yHQJc0a95yJh3Ji3A=,iv:3uFkimG2LjwxJt0HDvKDGqsdhRUh3ah367NF6w4gQjU=,tag:c2zUd8sqXkXBpsTBX0sqaQ==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6vlzbEzQA0y3YdQ4xmtm4ALJwRKD8kuq2qy/XnycIg==,iv:IDJGqvZgNT1YEZq64ATsElrkFjtyntoH66NxfmYzZH4=,tag:luwqvEYMxDToFj7CzO7CPw==,type:str]
resources:
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn-persistent
      allowVolumeExpansion: true
      provisioner: driver.longhorn.io
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      parameters:
        dataLocality: disabled
        fromBackup: ""
        fsType: ext4
        numberOfReplicas: "1"
        # staleReplicaTimeout: "30"
        recurringJobSelector: '[ { "name":"bidaily-snapshot", "isGroup":false }, { "name":"weekly-backup", "isGroup":false } ]'
    - apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: bidaily-snapshot
      spec:
        name: bidaily-snapshot
        cron: 0 */12 * * *
        task: snapshot
        retain: 14
        concurrency: 3
    - apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: weekly-backup
      spec:
        cron: 30 21 * * 6
        task: backup
        # groups:
        retain: 4
        concurrency: 4
    - apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: daily-backup
      spec:
        cron: 0 4 * * *
        task: backup
        # groups:
        retain: 4
        concurrency: 4
sops:
    lastmodified: "2026-04-20T20:06:54Z"
    mac: ENC[AES256_GCM,data:ovRiyYs5BSRg9kduoT6TCUcYZODFYKBojXE3ONjpj6Pu+Q5B6daQDp6UnfvD/RWldiXzuxQzcywu4/Em46LM109h7chYXwVIcPzOomEbx3K+GcECF3/k/cn9itc9NasxkbDYBlS52g/cFkkIylgFeZjclbNtaU463aFzyxyhto4=,iv:K3SwGx8swFGiGAzysdrFJ/FZ3fmYXZfqHytQTM1dYJg=,tag:3F6VkYH48Bnb50ip4h2m+w==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//UovQGlYWG5LqKM1SsOoaCBrJv3HYGnK7JXImWvufZMEf
            LFFpESFGIbZ9DBApoUZ+eUocxR3ZMiQOOH0v3ckhsmgnOhqUXxi+V/eun0kELvv7
            z2q2+EILM+tT3xP+AHEirD/ToYKvkH6Mp3beYduK+cQ1ey0T/gvl6KhfumLaB3IX
            lvWyqsNFOgpxtv15aznbwNNamZVvC0GnpZJalMTWtj0Tt5+dnKZ4sCxmlglSdb9F
            hTitgr5VQomF0uh/l/0a4nRgxB0iXsIzkrAGisglPmpKneg0vBKwHpH4icBRAvKD
            fR5ey/SG4faiTWriCU1ddYXLWvmWbDhOY48AYa5CYqjf9d71tITTHBdREPVSarat
            95d8yi2RwD/ixVmHtKS1qhMXkDUDiMJqyRDwU2IDrhL/SAY3Ziv8nPMoKlbXx94m
            doSvFxLo1fSo495iTQKqZE2SqXmIOmEZ9DY0dl2DaAyWFYY8Hah4wx4hSTAeWRQ5
            LA89XZsn4ct9LNRJ6J+fVNIQSlSeevbVqqrIo8ehR3FbmPpUHPcbIO80lF7m02ew
            FMaZGBom8gGeFCOuhYwdxi4lpf3W3oidQfbQlZLVNOOm1VZgK92cbKPu/B+FJZws
            2avM2YLDPKUWITCgyApdST/0PvBUompcw5tREdQ030S74KMp7ri5VcAoF8boFknU
            aAEJAhCvJpWlJmxVoNZl91h6G9S46WqKC0khQ+8uUdr2TFq2Wvy7oH+bRcFdn0D4
            neVESYJq2m6M+CGCEKEFt39yn3y3HEKqvx5d9kZxNo0tZ3hzoWpcKAOb/UWGQra4
            74o8ojtfxE12
            =4BMz
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
