# --------------------
# UnPoller
#   - Repo:           https://github.com/unpoller/unpoller
#   - Docs:           https://unpoller.com/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
labels: {}
# label_1: abc
# label_2: def
replicas: 1
image:
    repository: ghcr.io/unpoller/unpoller
    tag: v2.39.0
ports:
    - name: metrics
      containerPort: 9130
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
    port: 9130
secret:
    mountEnv: true
    stringData:
        UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:L7D8+b2aA77SLTlwguAMw9+a35c=,iv:HaE2UlHxEOnAAaiD0ecQ5dmrxROZxZO11P3beZOs3QE=,tag:/LerMSuuKB8DIiSNiG96LQ==,type:str]
        UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:TWzQmjlCVmA=,iv:M1j4SqKm9PlHsq4raeL1IndWdQ0Gy+pVeoxOkCYHG10=,tag:aFxlXMOT9u8Ww9IFFpy4sw==,type:str]
configmap:
    mountEnv: true
    data:
        UP_POLLER_DEBUG: false
        UP_POLLER_QUIET: false
        UP_UNIFI_DEFAULT_URL: https://{{ .Values.ips.unifi }}
        UP_UNIFI_DEFAULT_SAVE_SITES: true
        UP_UNIFI_DEFAULT_SAVE_IDS: true
        UP_UNIFI_DEFAULT_SAVE_EVENTS: true
        UP_UNIFI_DEFAULT_SAVE_ALARMS: true
        UP_UNIFI_DEFAULT_SAVE_ANOMALIES: true
        UP_UNIFI_DEFAULT_SAVE_DPI: true
        UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:9130
        UP_INFLUXDB_DISABLE: true
        UP_LOKI_URL: http://loki:3100
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 10m
        memory: 32Mi
nodeSelector:
    kubernetes.io/hostname: k3s-m1
serviceMonitor:
    enabled: true
    endpoints:
        - port: metrics
          interval: 30s
sops:
    lastmodified: "2026-04-13T20:28:46Z"
    mac: ENC[AES256_GCM,data:PXyYCve6A4A7xQh82fsbc6ACu/D41nN5vQsH8U5aav1el6Vdum+MFRdAOp2VxIDELxiXYnpE4yoU8nwXVqGLL2ON9k64C3xrUHkDbbI9fGLXyMQ+OLGWpfNhaJPIiUATXZuNmH6nhDJsm/aMhQBdRQGNfxIO6iVUJrFG3HONX8g=,iv:Y56oiiV32749kyjh555akfrKkcBkF6cUmS5lTZ8ochg=,tag:UbC8FSa6rx6QM9dhqirZ8w==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+LZGbEqcZRM1Dbiaw1jKUpiEx+TDnmPI4ekbJ/UwgPoyt
            CQHVFtv3lUIs0BROXu7wIwTBZNdO6a2dFI91LpvESHddto2mhN9MnWvjJT0Nsc0S
            6zXom+j2BlYQklHRUsNBcUhVolL3vG2PB2CfzKtn1o8wLfQQyqf52SVyKZjJjvvr
            FLYpoCKZ9nidv1oNLC7IWxNQ6IWOyGW7H7SZrQydy+kZ4TfACxm2pvnjFQEGP+hv
            TR2fClYOnrl/ECOjucE3VVzlKI+T1vwgW5YOz2+dq2rRM+N8NP5F2nyZWWa7CRhy
            MY4J/rgpivkZoGgcHnyPia1ppAV+5XDWJmFD/068N7a55tvFRo+bi6GI6fhg1/n0
            /xsK8DH23llNwIYdUGXG88lWoaLtFpqsaI785uj0TSBVFS3U1/NRwH2H46vgF5gJ
            VYLdVFMfORxtdOeTnwyesBcvVkqIfU+FvjIwLL7F3E1LVSRf1S++K5Jn4zYkcvKG
            +g5GjNMN605BGlaYTKU0Jd4orRwdw1Xti3FsZHnvPXuggwK9iubnHZ/9o+AKKmuz
            qj4faG8NC0zpW7BMuLtSqGGakjcaf+0jZ1cF+daS7x4AUr67FuZ1LOZlzEmcoP1/
            ByjnlnaIbmM4Selq7ZA7ZDs8nAxFishq+p8aXXp7Vzaut/U0Jiba2IB7o5byDZvU
            aAEJAhBMFinDiYrhMGE7cjvfQdsRtAJq1TMVNIavn/B/zyRgdgMZr1RPfybf/18x
            +ughyrH6Chx3J9VTilLZ3G1y6sbng/ZBYYWew9OHN3e6NF2mW+kD/BQoucw9VvyI
            8tIzcESKwfrD
            =K06D
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
