---
- name: Find stacks for host
  ansible.builtin.find:
    paths: "{{ docker_compose_stacks_src }}/{{ inventory_hostname }}"
    file_type: directory
  delegate_to: localhost
  register: _docker_stacks

- name: Ensure base directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}"
    state: directory
    mode: "0750"

- name: Ensure volume directories exist
  ansible.builtin.file:
    path: "{{ docker_compose_volumes_dir }}/{{ item.path | basename }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0750"
  become: true
  loop: "{{ _docker_stacks.files }}"

- name: Sync stack directories to host
  ansible.posix.synchronize:
    src: "{{ item.path }}/"
    dest: "{{ docker_compose_base_dir }}/{{ item.path | basename }}"
    rsync_opts:
      - "--exclude=secrets.sops.yaml"
      - "--exclude=.env"
    delete: true
  loop: "{{ _docker_stacks.files }}"

- name: Check for secrets files
  ansible.builtin.stat:
    path: "{{ item.path }}/secrets.sops.yaml"
  delegate_to: localhost
  register: _secrets_stat
  loop: "{{ _docker_stacks.files }}"

- name: Decrypt secrets to dotenv
  ansible.builtin.command:
    cmd: "sops --decrypt --output-type dotenv {{ item.item.path }}/secrets.sops.yaml"
  delegate_to: localhost
  register: _env_contents
  no_log: true
  loop: "{{ _secrets_stat.results }}"
  when: item.stat.exists

- name: Write .env files on host
  ansible.builtin.copy:
    content: "{{ item.stdout }}"
    dest: "{{ docker_compose_base_dir }}/{{ item.item.item.path | basename }}/.env"
    mode: "0600"
  no_log: true
  loop: "{{ _env_contents.results }}"
  when: item.stdout is defined

- name: Create docker networks
  community.docker.docker_network:
    name: "{{ item.key }}"
    driver: "{{ item.value.driver }}"
    ipam_config: "{{ item.value.ipam_config | default(omit) }}"
    attachable: "{{ item.value.attachable | default(omit) }}"
  with_dict: "{{ docker_compose_networks if docker_compose_networks is iterable else {} }}"

- name: Deploy stacks
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_base_dir }}/{{ item.path | basename }}"
    pull: always
    build: never
    recreate: "{{ docker_compose_recreate_policy }}"
    remove_orphans: true
  loop: "{{ _docker_stacks.files }}"
  loop_control:
    pause: 5

- name: Prune unused resources
  community.docker.docker_prune:
    timeout: 180
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
