# --------------------
# Cluster Heartbeat
#   - Repo:           https://github.com/healthchecks/healthchecks
#   - Docs:           https://healthchecks.io/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/cronjob/values.yaml
# --------------------
secret:
    stringData:
        PING_KEY: ENC[AES256_GCM,data:JzLDMUV18iroWZYOtY5WFPUa9foCxw==,iv:sF6nhVU0Pt5O8uRrYNgckfHIl08WhUgtfW2SBSxETeo=,tag:kgJ3hAWOiJSCuMnJ4xAMag==,type:str]
cronjobs:
    - name: cluster-heartbeat
      schedule: '* * * * *'
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      backoffLimit: 0
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
      restartPolicy: Never
      image:
        repository: docker.io/curlimages/curl
        tag: 8.20.0
      command:
        - sh
        - -c
      args:
        - |
          sleep 2
          curl -vfsS \
          --data-raw=${NODE_NAME} \
          https://hc-ping.com/${PING_KEY}/k3s-cluster
sops:
    lastmodified: "2026-04-13T20:28:44Z"
    mac: ENC[AES256_GCM,data:qUK7qJnw2WyDbvk48nBeTLS+rHb/XnJBWEldCMg1isjeEKL5Ajp/Y7z/XjFZbVKDlmkhQibPyP/SmGv2VkDNk/eiZt94prk/Jsh1uXmKzUajt1fz5xGYrNrU2cZc3eBaGhFYIxiJaT38yUx6/dqnjrjrQ5mBNNMKdHx8Uo/nfL4=,iv:KmHXMwshe/t/u0Sw6dOng75ppy2e/w20+Xn86rdCTxo=,tag:kuQj9iP1vvmOqNMPYXqtyA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAjigp2GHqVpZBT2nta3XLmjezOxKdRqv0WhNj8NmYtYV2
            /lPmocTPDs2BjodXZ/iCqGySMDsZAlhONtZMAMHLfQEKaMowJbBh8/gbPzZ9QC6g
            XaLsDWGsX3/WEqVdIbCnQw/H7ARsMqFOZGK4UdldwTHVaR9x9BKuSP2j9j4yEAkT
            e2E2iLJTgZin3bYxbJghtc2L4CMKMe52N23nW87nnlZa6zzfY4JWUPsrXNdOnv+N
            +HXRzkPKKNx9E7d0ovtz1cDuUbs3cTsQ2wCR18JpmQtN8fNXR4oHUYPv8xCYs38S
            tnVa9p0EIqb0KXXEDRH4AHGhhx6UnHDsBh6VwjLjxLDU9/F9/RIIbw8mRgJxHz8x
            DXHFQGn/koGr73icJ01OMZyqD6KehnUCqx7xUacylRfvvyBV6pLRRFsYAKi5DDpB
            qw2Gtt6WGrxb49LTBpzWFIb/CG1FIqODNcjo63EmqEpNAC9Jl9su1eAKnsbtAjyH
            p0bwoiTWo4obbj6NlSpFlCbkOjaVQPFdLwalX1ieLvY2aoYK9Q18HchsJB4OV/J0
            CsrygrjkQc0nhVpw9S5CKNqMcpRJBNHf8bE6/+9LjsPisNQPdpdptEmoMoOYp3MY
            lqMZpDRECPbdknKC3z7AbGzz4bTXyOS/Y42JTPsl8vIYSTE/yM2uzRLVbGvccGbU
            aAEJAhCcglDU9kU27Wnp0xESxJ6e+ndnPlztTdzroA8Q6zDcTbvzJ3/jp0mLnGl0
            On6LILLvS2NW2Fjtv6e/jfE6vRwkioaPgIwrJ3yxXQ2gWIOzV1qqp4yTSJeJPzr9
            VBP7FOqKHe1X
            =N7Ev
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
