ansible_host: ENC[AES256_GCM,data:D1nVENgnASBB+bs=,iv:CJ4CuceTNVEq9pBVpFjYVzdIk6qz4XqVReCOjGUjySU=,tag:RFkfguCAuAbLOgv12+vSUQ==,type:str]
ansible_user: ENC[AES256_GCM,data:f/97Xg==,iv:GvrxRmcAm1f7xhFrLLo76dYxtc8VzPbkCQZgap8X7zc=,tag:tFLVnoYO6dF90Ljr7NhKFg==,type:str]
sops:
    lastmodified: "2026-04-29T21:29:19Z"
    mac: ENC[AES256_GCM,data:O4Sji5V8jDEb8kgNDlsbhtAP1vHTovtPJ3uGva8nyZJCaxRe+aaB9u754gUQoTAl6AqbrNUwOduOLW6gMRX6+WgeMjwYQj8pwOyK1mundpyxU5BUbJPX/oM91HxW0rdTZTriR0bcJo7uajhlEjxzncfEgGwCexdeK0ClSoz9dAI=,iv:GObCxgxpm3VBCfbIjlNBRMX8Zz0w+4CpYQqmUird718=,tag:Y6dschjUoWHX5h239BVrwA==,type:str]
    pgp:
        - created_at: "2026-04-29T21:29:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAlMphpdO1b8eguTONO2/URUwN6CcPE4S94i5i1vtTz3Go
            I67n/S+f56Dw4dA9037sbkelXw3OAVUxV7By/r8oDf8EsDzYvNGLI45DWhEspnoo
            8Tnmw88HhyllXNEWTN17/FPofYD8w63PNLFbqWirGPxwo+hxrR7q4VHYmAzX3ngr
            6xJbGysAl/k5kbZsHntHbr/6am+1EBpnKgKi8cnD2I9cHmDAWx/ac4Ait4DNoPST
            pqOzctta7mj0OVWIiAOOOEjsX2IFWOBKNifqZLXNewNX1f2puTRDAoqPcCC4kjD0
            Y/rPjNYHLhjKY7B6wPTD873CE64hDV4/yh8/ypoxPf8j+KD/dWcoBwEiZaVbMtuC
            dtgnsaubP3OZjrahwuybRBdlySeG6xTHwK0Aikq8NXayZ5pUjX1aRez/3gpzV1+r
            8oz4lboCmZ2fhhfj+5CAUp3t+dX9KVh2rh2jORGb96Cvy4U2o1nCiNehCNUfOFTr
            dKFuep4JzB5/AllxHJ0JWwnRfiNzDzPJASYvrKY4SI95lpcDvta7WYXnoKsMcfwi
            uvbgs+4Lx7zzplZmyWdbzfnFVWyQ73qRl/W51lh7dxas15Q0SKumV25jXDPg5fz1
            EWRCvCSz6PB4WwabSNjMLwQNgHD/FrFZ4hdmRVry9vntBiYFb3IlYaJyBl5KJ2jU
            aAEJAhDuU781Jg1svZa27Bo5yVuCi23t04HAuK7ykCEGJumw4gjKNacFFoLFPJcN
            q9kZxFvK3Jd4HDZ0cmHHoseSxc8m38/i3MARwegWqyyeIR2h/7JHY/uo+AiuzXsy
            ttR7U5KqNBnO
            =XoHz
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(token|api_endpoint|tailscale_authkey|ansible_host|ansible_user|ansible_ssh_private_key_file)$
    mac_only_encrypted: true
    version: 3.12.2
