ansible_host: ENC[AES256_GCM,data:wgF1I/skIXUk5W+N,iv:7DYRca+F4Fu7mF0lRS2cWm81Z2oDx+repMTxlHxVhxY=,tag:nHag1W4KvaEC8ET3ha6oTQ==,type:str]
tailscale_args: --ssh --advertise-exit-node
sops:
    lastmodified: "2026-04-29T21:29:19Z"
    mac: ENC[AES256_GCM,data:k8l2puReT+O6WeHFlgq8tIrfOTdNwNfxgq5yvIRHTjKCEP+VqBgGlF8nmQbPnbR2qvMqGMF4ojQrhX9WFA6AwAafErGff4EsdTBdwKZRLsb3vEkIWEJG9Hhvur2mt/HhRohF4UjoBg51PD/mbXAMWaVVbpnmehZBU7vJIuNhTOo=,iv:2EnMDOmQVgk+OzTfHX0yaouAV2+1qwgPSUMGRYB8JKY=,tag:ichNBQToUXkgjM1s2BNdmA==,type:str]
    pgp:
        - created_at: "2026-04-29T21:29:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+I4VE8Pm5+oYoWwyWqHaCEeY9GpmQ5mbutL2PtZyWQeqs
            JfPsFgp6nn6a4rh8K1ORu1Z0Xg2ndQ5C6JfMCxbymTlkDJECIiDy/jBrcW65XYCM
            yGNgUp78mj2l/s8AtQwm+eeVy1KZdyiTZakXPseSNQrs2qJjbzDYxkgcXebQim92
            iebHZmSaehQCYIEoERhYleBxgfFsLX0jndn/+O5WqX8voT6D0QdBSol/o4k+/HfC
            SCJkk7acxsx77GcZzWmBkcB33XqLc/ZN75o1X8KRoAD4FNqIcIueZR/KMMgoADQ5
            fnbr5qXm+S3HuKnLaduJcJYH9z9TlKd8lZV7qJjzP3E+MuesI+WpB0xay8nME+58
            xD9YR73scgKDwy4lgk34tXreptDtuk33L3PqEr4oH+6wnKlXcMpfc7LBY0cvHkD1
            NBeaae52+ia9uaIkyQR/7Vo1IPtnVRxmZpGR3iIRf87acWJtxePBzG4n0U7NAoOz
            eSWRaYDqSy83ZdoOfWpDvFQvbITgI0QS0gomZwCyKb3b7y7gMK5hMunx4oNRGW0k
            3EhgZ4MHInTWFbE1gDShB+Vvp7OigP6fJpXVGxWii/e2Ik9x4BEgLEPFDSqVXF2r
            eBE/y5PZLgBPXfUsYcoH06zw44h4HV1I+phSPctNLuJc1bJxEJh/XnIkLT3ubKjU
            aAEJAhA05Zrq6F/FUdAC17KE08OGzmpy5/T3ZamAAgswVONQDBNZPPl5K/USXIUs
            o8Ql18AB3V+0V547YbJW0bw2EOxbkToy75kTYhu+MeFqLxAIgrA/XRHwBl/BfO3b
            k8PTJYw+QGB/
            =HWBV
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(token|api_endpoint|tailscale_authkey|ansible_host|ansible_user|ansible_ssh_private_key_file)$
    mac_only_encrypted: true
    version: 3.12.2
