ansible_host: ENC[AES256_GCM,data:An9WZnnuTJLbFEg=,iv:h6KLNoNBW8U159DMpnZ/LDf2/PoTcZse3XMWc7vIczs=,tag:iiETbzDuSJmeaHfJTRaYVQ==,type:str]
tailscale_args: --ssh --advertise-routes=10.0.10.0/24
sops:
    lastmodified: "2026-04-29T21:29:19Z"
    mac: ENC[AES256_GCM,data:ZlSte+V8gXuGfzBQM3QRHxHV1VOI2iR3/FKReXl7afcy1pIDAruLi5artXDP6nGi/L3EThFuG9YX02++m+LKa8ILW74/GTxooGb6D4YdgRm2xC45j6UTgAmyb2BDYu3Ydzo0TTcLpV42TJvgsnZLMNbkloKzKpzSRA4VglV1P+M=,iv:9yODcleyHGfsnUomBu4UeOW7c/KXQmm7fHTF/WCoG2c=,tag:9wx+OwshP1vwRxYCo3+MLA==,type:str]
    pgp:
        - created_at: "2026-04-29T21:29:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/9HMnKMs5g7b1Z4+0FCauc5z69FEZa/931Qz5UbC8GvbG3
            DVGq+qORExLcN4MsIfoa0C1vh3dHTR77JuIBcftC9WALykQGR6mBdj5B+ejeT+4j
            htKDRIeToHaJ3LONM0f1hfZDINcrxb8vqc9Sh95e+GuAADAZ1mfhJnZtuZuv4GP0
            M9KpQE7vqsTGkDeuGsyuo+sYYIeAHgf96JxyOc4hji+MlPUarsNtaiMCDxOko3jo
            PIJGjED7ZRm41zs8zejSKBZBccDehcVu3GhleYbxg+XkvVJOhws+JA2pvRoZMMz+
            xqQaByZQwQT7vTHeFT4JLFKRSuEiii4om9PcXy5ut3qRAO10binaQWdIj54CcodJ
            H5zDwSAhh+RZ2yX1HvHc2KcCp5cxty0GmOaRePy+xOmx79J+lS/DbXVemP+M2YkN
            HOcHlbVgbUXvvn78Ety5dLeD4QqRGLoPSQlnQAxDqpU1PsJw+ep2dwTXsrcWGJzk
            Xv0PORZGARc4YtqTKn0fCUV1lHMTXanQU5PN4++wuwffYEoyTgP9yqP4g211EQtj
            IDx6ksLksHQXo8on+hr0/PnEtH/Yw1A95acwoWZItKyXcpOXUKw1+SUEnZjqYtVF
            fWP+fLJahRg6Or8AUCwCAdisBId4YiraKEwHvppr4zzzcolhe5Y4M62QpqFafFHU
            aAEJAhDygDvJAXXdm2TCdbDbvRTV2PxeqNkV5CGdgumbTfWudCGWgPGd6lfAqxVF
            MYycToSf79Bjg5JMq8Oa8SPFoPlflWDtvyo7XZxTo+cGGvc2gi/LgonYZecqoSwt
            pxVkCMxzEWAF
            =ARbm
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(token|api_endpoint|tailscale_authkey|ansible_host|ansible_user|ansible_ssh_private_key_file)$
    mac_only_encrypted: true
    version: 3.12.2
