ansible_host: ENC[AES256_GCM,data:X9yeSAiOgpQuDA==,iv:DCLmBq5Fya0YrvA8AZ6yZJfm49x1Va/FSdgKQVGPt0E=,tag:HoAooNYmu0Fqlgioxo0X0Q==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:nfrAbwOF/VGSx6vgqHJxBZJZYA==,iv:m0mDWjkLOpmA+rkJwsldvKjBjl7X09QD/POrAPOqJgM=,tag:VWB6npR1+ppqnjjw9cWUMA==,type:str]
sops:
    lastmodified: "2026-04-29T21:29:19Z"
    mac: ENC[AES256_GCM,data:fk0rZfXmoxUrC3ceSAtaG3ZncDRXlBEAU9Tvfs4PNPqpW45NIf5dGt/Q4luuAWs5ZERsddKmRZc+DsMSMztwQTSEp5qf85+ZPcEclrjbAI8Sfsqs09IfcNa+qy8v5m4433s7mnTZfnOhsr4nVIGZ2DMpwdDzXompW0jJIc+bmLU=,iv:KUzhw2qGpdctwm6IbHsWDPsw5RzKZ9xUWMwUK1GdZxE=,tag:xWn/79z70s8PJg/n+H7N9Q==,type:str]
    pgp:
        - created_at: "2026-04-29T21:29:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//TPpjEeCSr09i+eef6PAiod/MVJe5kPIZk2B1ZSGR1veY
            w2v+Z9m+SqCBFD8XbvYA8BVG9QA1rXp+mgXqkTqpvqTR/sSxkOr3Wud2tZxs3vy9
            0y2YojVAkOye1GCxX4Y/8yRBLZUNfaSfpugMcK++GmeOkMiRL7yEq6l/+k/mh5mJ
            RJojnMIYU7e5ejoC62cy5lKdnU5hWuwdxBxGc3kwKsMYn87J/2GZYxU/jQX7aurg
            wBTzUTusafPESVVf2VSntsCw6voDZewX1GqztZ20mdg947OWFNAteCEE0SAk4i+I
            sw722VMTOgElpl+TuiUy8/w9RxmLSFtMtwTqb5XO2EiQu7yK0o/xakQYqRN/yjSp
            CFz2wXr06MrLD1YLPutwsvtPltlurRh35l+6Dn4DXz6LEg45oc4da5B6mEhS2+x/
            OhbmiCrN9ZKIU4LWmQ+sNP3PHarlseyn0YLKJQ1SiKAzuX/zqv8LFShQCk90EM1I
            tNpkFUFOuNyNml01YhIReo+N/43MDrF2FPUA79WLr70kyd9USJcLgF9N1PAJrk1a
            DMQ/ACicjAxdhsZT4SP+E87wxPTLXwi/KciDM9WG8BFzAiFn+P229rJ4P2hMR3rg
            7T0dkhHDs/s3yKvGHAYfqUlcpRJOiA1t0aPp+HKHwzTox78To4hD4InLczxDswjU
            aAEJAhAsVHcin8mDnOR7s3pxJukUmL2/Y60TQafUmbC6vn2qwxMcXsQhZCNai64X
            ujmFb3Z2RQKWrW7vvpBkIBQRck0s8YQQqf8H2xtG64teVmgq+N5RAFB+5AU9z45A
            2rxHStCjEE95
            =Dc0P
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(token|api_endpoint|tailscale_authkey|ansible_host|ansible_user|ansible_ssh_private_key_file)$
    mac_only_encrypted: true
    version: 3.12.2
