---
ansible_host: ENC[AES256_GCM,data:hWg0bmoVpXEwbEg=,iv:xl3wDKxGhy3SVujWVINUkIHx16VaBKzGvF2qmlCNrXk=,tag:lONK7tiVkiCZZV6MysEZGA==,type:str]
ansible_ssh_private_key_file:
  ENC[AES256_GCM,data:Aoh+slWKzgcIf3Anps7IJ6PF,iv:KhvZ4mha/dcmVzcoFXjJ1mDW/4A89mwb+v7I32RD9hc=,tag:3VACh1Bwr/u94W2aTXLIKQ==,type:str]
sops:
  lastmodified: "2026-04-16T19:43:43Z"
  mac:
    ENC[AES256_GCM,data:5nn6E6j2VQQMAtH/nYjp8XC/i8E1YCfy6tQHEgnZvm+fH+gWdMALDkqCOkX2ciX7MVH1DsvKdG2dV+WkmENdP2fHgDxwUcydV0LwVwpO4Ke+IWLFMIPZHJ2iNtKJFX14l1O/OZsItdTrsIZos5oP2MOV/hJssmeu/O5a1xM91nA=,iv:gV0gCt/Jkpht2lob9LxYgflJzi+RbEYzKwnboUbN3dI=,tag:PG/2jLtgxTWTsSitnHTVLQ==,type:str]
  pgp:
    - created_at: "2026-04-15T21:34:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5NT/LvuRqeGAQ/9Fn9TRy/Un9jsOyXpXSrFKu9OZd3+kPBSRei8CVTNLPHn
        fBjfZzvzAPQ7+sUATiOiMtHFyg5ChOAkJNgXU+UTuYNltJkFpXI1L8kqK1jsXwhT
        OugVN0eywSDs8oi/dRe+rK3vjLEF+iCA2Eis9SBPZY9akkXtLh7Qb4Z+S3gPkV0N
        9hLn5mT1OpjKWqpZ9EbcYFxgIn31oYKoRq0de8NRlZ3Mx4Vv8TdrZ0ZSVsaFrYsc
        yIEFrGjYLwF8rIO2SjkOPORtp01G9qJO82L5J/FqV0hxKIfQVtHfaBawYHCDfTsl
        CmPFqxWFqmezpODdeQrYolaZYitiDJWEhWsjo9JUiJ8BJbI+S1kJqJfHJj4lngYn
        pIJegr3Y0HUGNzZWc4MFDnam2Mw20R+4z+CvUGFGrHoh/JNhigHlSHRmVTi5bk1V
        A3RvPlzrV3qqb/Glr+c3D0mNtMVc32Gm+s0WeSm8gDEuDa8EqSJAOtRxDtAesEWc
        1CWySmRd9Mf9vQMDFIzSjb3/KVuri4Tdgkcn4RqfTydHMEwAWZI/8WCjksn6rZGP
        U8uX5CrHXwyYYpqkEWSU6qZhiQqNV53KOALvrGCtGesTDh0GOOAI6h0Jptj6iwfx
        LF0QFaRK6mt/7fMGt2NCMwiAW/u5HU/yf0LQBhNYj1YS/5V1ERP1fK2KNF/XEhHU
        ZgEJAhCy8NOcYpKu6u6aOp3ht9j/BJ7o7O9mm+XJhJSBgfRA6pk1XRlr/MuyjaJY
        kCtdbkJFxNtOH+27/VIGjEUTD8LrbuIQKVRzqut58Bx+/FKekuhR4HUGiUssIK/T
        e9pdIHIqWg==
        =CpIv
        -----END PGP MESSAGE-----
      fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
  encrypted_regex: ^(token|api_endpoint|tailscale_auth_key|ansible_host|ansible_user|ansible_ssh_private_key_file)$
  mac_only_encrypted: true
  version: 3.12.2
