apiVersion: v1
kind: Secret
metadata:
    name: homelab-repo
    namespace: addons
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    project: ENC[AES256_GCM,data:k7SvQ0iwRQ==,iv:JDecEnSfCzyleTK5Zyj0osycoasA3botHvfkte4+fqk=,tag:vToabOPtNX4uj6KZBvZfOA==,type:str]
    name: ENC[AES256_GCM,data:jg4Vjj9eKw==,iv:AghTjQBWamt+M8r4J1DLeaKGiPI2xamtp/QO9k88DL8=,tag:1HOR9ok+QNRttqjsyFyBYg==,type:str]
    url: ENC[AES256_GCM,data:altX9HoL0/SwqyhwsjbZfn5xxkdiPWl7IdEs95hMCMQRXGsP,iv:x33grGAjOVapp9nKUSaqCPg4lW0KKQjqnO0FJst/ZCM=,tag:W7XN9/LV4lmui3TFG1F7lQ==,type:str]
    type: ENC[AES256_GCM,data:n91P,iv:kv1ruQMie9WPLozUNBTvVmCIQQhP0kCn7ufsHIxtJjc=,tag:E40IuaZETSQo11QqJWUCBw==,type:str]
    #ENC[AES256_GCM,data:c5foenQMWJrVslY8Qs6GDDS2KfD10Jkg6onquti8,iv:XtYo+RcE9sEOhf+kY1/OSjLd9uVOxubX7lrrgZ6zv78=,tag:tkpmv3FOmRdCWJ+JmAoatA==,type:comment]
    sshPrivateKey: ENC[AES256_GCM,data:kEEI+02hRDFMMzXTEkjy1UOWQDh3bD8xCjwLKYOAAt14HPbvC5G72YLDIxadHcAwfYzSzUZ7ms9/S5/5dZiEjbQYoyhMNgzyM7kIAg7MAOO0wBuZa8RR8J3nQJsFuQOlft1rXKd33qzfF2phcvNQ2gqZ3G+vN4LH2S5Ax4NOWr/KvilgoxhdlDNUjHc6zYwxKcYcXYUgVrU2wRZRSYyFSB3uzmAAPz628fgMopMBwOMtNt9mhiuJSzzG/hyfXnJs/GphfwNaq/9Nzvqc1gxv4onHoePbCrGhn+ifQEkV9XXSQwhI5qgNhmbnE+Mzs5dX+Nv37f5ntFxE3Ia12Q+IWUL2ul+RYlsk/82tbv/vDRA/t9v3S7UIq2HsILyP7nURRtMgfsExvTdontPfRsIa+53cDK2qv7GlYsgvjobnDAS9JA2G2mtoatOM53zXUxVtY9/pgYffWJ9Lr51r9/2sQPtQ3CuB8TZi0t9nGzfDVcNbI9IrHBrKOYD0WscTMIXruhcroiE4TC8rTK44HGMOcE6SSt0myETPzLxu,iv:RhbSfeI4EwKMq6ngnntsD+VLh3sGgd6iuZn5gdQ9uyo=,tag:/4QMJ7X3oA/ZxbEEqwAJ7Q==,type:str]
sops:
    lastmodified: "2026-04-13T20:28:40Z"
    mac: ENC[AES256_GCM,data:Ux7P8hpeoQjsfoSnklIzQ39NOlC8AtOlmJS0DOvLBku7dq2I3qisl/6VwAOAFfAYZONnwtSto8U2wzdoKnb/l0HR3b/KQrGkpEEln5NQABlQkPKVzm9zpzTT9rX5k6To+sKIiLAGvYxcT7SXeuhDK8+GrDlv/t16LzPMw1RYFCo=,iv:ZpJJy4Qwv1/PUE5pxfD0v/GLHSm0PBymElNOJry8N/g=,tag:jW8kLjZJZNr+H9nKDcfbmw==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAjXJpFmf4nFpCRcdaqRWvSjLw1TkxcUDsEoaPqu9IZJZ8
            Gn5sphCW5xjVIi1rgfUkOuiFWYQYow9ucSynyWVijtejOe5vi9ljGYXjz3eSbYSS
            Pst7dl8O/vzgKhMnoIo7MquD4TjYhhQ9D1hu20QhpoZkTi9Xw1ow6X0/DsCbTuss
            Uqnh8n8GsZIVrTOCxVoMQppvKpQKot59XosYs0qOe0h0KiDeo2QfCO3lw1Nlrun3
            DcaFiWLa6/CsAgmMY/kYkYd5CrGjpTUTSRavGlgeFUTzq/sQvyzSg1+wMWvFG3pe
            XbcwUQrEgku1rkgm9DaAp6Jg6c0cJBu6jH8KYu560FBhXXe9wsf8F6MWvW/WIvTp
            1EuDqoTgHnm68IsB5JOjnXa6XVd9HhvObixccWB4/lexZ1I+LM4X2P5VDQwqll1+
            sxF7iazr9jOeM5xbRG0l/6UF5U+8cE+/3ZpPSLctVVSmaw8MHD7woeB69dfhyGg5
            b4sLICRt0Soc34k4Big7RF6rXRYzzmm+D4HJO6NCIrCfP+9Q6Hjc1Gw2nHZb/cNG
            C6LdHyPAXUk8+en+X7kdvaQ4LPW09ZtYkRhtokpqV1swwHi7EIuI1kdUsJY6N90B
            CLRgdZg7p1GiXuA0tbXaLjtjU+KyAyK206ohNVc7UDVMKakHKKQc3avDI1M7ei/U
            aAEJAhAj8mLlspUhG9tiidDoKqHKXZLofocMP2cAL8PAh8tHqTvXj93B9+0Wwx3L
            fVR2ddbVnZC1a5V+X7W3qzBlq2RxO22Qht+jvXQFDsMcSgvBd317QgJb4w8ZLUL9
            +xsPfzBqmR7Z
            =KgpE
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
