## Argo CD configuration
## Ref: https://github.com/argoproj/argo-cd
##
# -- Provide a name in place of `argocd`
nameOverride: argocd
## Custom resource configuration
crds:
    # -- Install and upgrade CRDs
    install: true
    # -- Keep CRDs on chart uninstall
    keep: true
## Globally shared configuration
global:
    # -- Default domain used by all components
    ## Used for ingresses, certificates, SSO, notifications, etc.
    domain: ENC[AES256_GCM,data:Y1oFD9jucFKz83aB3TXtlpvL5SEQwViH/Fw=,iv:XXXU4Z4Pc0hlL3+oWols36oH+OAvodVw1yNU33P7A8c=,tag:fThCXY/WJ3UzIZdMnby9Rg==,type:str]
    # -- Common labels for the all resources
    additionalLabels: {}
    # app: argo-cd
    # -- Number of old deployment ReplicaSets to retain. The rest will be garbage collected.
    revisionHistoryLimit: 3
    # Default logging options used by all components
    logging:
        # -- Set the global logging format. Either: `text` or `json`
        format: text
        # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
        level: info
## Argo Configs
configs:
    # General Argo CD configuration
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    cm:
        # -- Create the argocd-cm configmap for [declarative setup]
        create: true
        helm.valuesFileSchemes: secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import, secrets+age-import-kubernetes, secrets,secrets+literal, https
        admin.enabled: "false"
        oidc.config: ENC[AES256_GCM,data:ZI6MTrYsnG5t4y+JQA6nAfJB3K4kDpBAM9APR+y7Br+rs0HYzb1lVr5iZkVuFldLqP+HzdpmPaaktsY5gWcjHhAm03dAOM7a4NEUJcagLTiABMWs5yDOL3zXf8bb836uYVyPZNhPojaCYF9kSQScqz1SWu/+jgJbbaogV3JeDUjACTS9XGUsr8bcYMQ1oivW3uJmBGFrfXHKcK5+3YztMHAQvrN80Cjetlgh7l/a9LGUfbEVYwYbgSphjmhYzEy76Fn6nMMyTWONgVsk+PyQbHZZ7Xt1vHk8ByMC3UqZkjy5XtXojTDWXMc=,iv:oGcrZK+6l4mVy0rQCB4yhK1WRDUDCGag7LU1gnYq5WM=,tag:pMtoiVKF20J++llLxzyTvw==,type:str]
        oidc.tls.insecure.skip.verify: "true"
        # Ignore metallb service changes
        resource.customizations.ignoreDifferences.Service: |
            jqPathExpressions:
            - '.spec.clusterIP'
        resource.exclusions: |
            ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
            - apiGroups:
              - ''
              - discovery.k8s.io
              kinds:
              - Endpoints
            #  - EndpointSlice
            ### Internal Kubernetes resources excluded reduce the number of watched events
            - apiGroups:
              - coordination.k8s.io
              kinds:
              - Lease
            ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
            - apiGroups:
              - authentication.k8s.io
              - authorization.k8s.io
              kinds:
              - SelfSubjectReview
              - TokenReview
              - LocalSubjectAccessReview
              - SelfSubjectAccessReview
              - SelfSubjectRulesReview
              - SubjectAccessReview
            ### Intermediate Certificate Request excluded reduce the number of watched events
            - apiGroups:
              - certificates.k8s.io
              kinds:
              - CertificateSigningRequest
            - apiGroups:
              - cert-manager.io
              kinds:
              - CertificateRequest
            ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
            - apiGroups:
              - cilium.io
              kinds:
              - CiliumIdentity
              - CiliumEndpoint
              - CiliumEndpointSlice
            ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
            - apiGroups:
              - kyverno.io
              - reports.kyverno.io
              - wgpolicyk8s.io
              kinds:
              - PolicyReport
              - ClusterPolicyReport
              - EphemeralReport
              - ClusterEphemeralReport
              - AdmissionReport
              - ClusterAdmissionReport
              - BackgroundScanReport
              - ClusterBackgroundScanReport
              - UpdateRequest
    # Argo CD configuration parameters
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
    params:
        # -- Create the argocd-cmd-params-cm configmap
        # If false, it is expected the configmap will be created by something else.
        create: true
        ## Server properties
        # -- Run server without TLS
        ## NOTE: This value should be set when you generate params by other means as it changes ports used by ingress template.
        server.insecure: false
        # -- Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from /
        # server.basehref: /argocd
        # -- Used if Argo CD is running behind reverse proxy under subpath different from /
        # server.rootpath: /argocd
    # ConfigMap for Config Management Plugins
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/
    cmp:
        # -- Create the argocd-cmp-cm configmap
        create: true
        # -- Annotations to be added to argocd-cmp-cm configmap
        annotations: {}
        # -- Plugin yaml files to be added to argocd-cmp-cm
        plugins: {}
        # https://community.ops.io/jilgue/secrets-in-argocd-with-sops-pa6
        # sops:
        #   init:
        #     command: ["/bin/sh", "-c"]
        #     args: ["if [ -f 'values.sops.yaml' ]; then echo '---' > values.yaml && sops -d --input-type yaml --output-type yaml values.sops.yaml >> values.yaml; fi"]
        #   generate:
        #     command: ["/bin/sh", "-c"]
        #     args: ["cat *.yaml | yq"]
    secret:
        createSecret: ENC[AES256_GCM,data:zhJopg==,iv:HbMBROma+IQptJB5fzMbyYiceFVtdTdnIxhjnOM6ibo=,tag:XicfJ/NXXUl4t9nZTjJdAg==,type:bool]
        oidc.authentik.clientId: ENC[AES256_GCM,data:ZUkeEz1E9b/ANKJ1hxfsPlgPWW0gC8dYnSGQo5/FZ3GCis00T+PDIg==,iv:V1s5VbxNOxALUuHAdaiyuJNuJJfvyq6XCQ8+qTOTGpY=,tag:7cDmtw5i9aZoH5jczKokPQ==,type:str]
        oidc.authentik.secret: ENC[AES256_GCM,data:a3Yg73/x12Mjxe3yIp1sYTJIcR5Yhfeoe6hzSr8lmPDUi8957fJ7sfMBQvX5P8tJijYkj13a4HW3ZTOIm9hL6F+VQExEhYdD9ujBGUeulV3SfSOTfMQC7BWDVXNv1LV5gPyXoiZQNfXJ+WY7ktBv2rJ+NORk63BD3PbOZM6r5XI=,iv:tKWLTKXpBy76VYOVf5q49IZ2q6DwLMmn+8IqIpCrCRA=,tag:0LgXbs1gsM/XYsdDNMG6Aw==,type:str]
    rbac:
        # -- Create the argocd-rbac-cm configmap with ([Argo CD RBAC policy]) definitions.
        # If false, it is expected the configmap will be created by something else.
        # Argo CD will not work if there is no configmap created with the name above.
        create: true
        policy.csv: |
            g, authentik_admins, role:admin
# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates
extraObjects: []
# - apiVersion: secrets-store.csi.x-k8s.io/v1
#   kind: SecretProviderClass
#   metadata:
#     name: argocd-secrets-store
#   spec:
#     provider: aws
#     parameters:
#       objects: |
#         - objectName: "argocd"
#           objectType: "secretsmanager"
#           jmesPath:
#               - path: "client_id"
#                 objectAlias: "client_id"
#               - path: "client_secret"
#                 objectAlias: "client_secret"
#     secretObjects:
#     - data:
#       - key: client_id
#         objectName: client_id
#       - key: client_secret
#         objectName: client_secret
#       secretName: argocd-secrets-store
#       type: Opaque
#       labels:
#         app.kubernetes.io/part-of: argocd
## Application controller
controller:
    # -- Application controller name string
    name: application-controller
    # -- The number of application controller pods to run.
    # Additional replicas will cause sharding of managed clusters across number of replicas.
    replicas: 1
## Dex
dex:
    # -- Enable dex
    enabled: false
    # -- Dex name
    name: dex-server
## Redis
redis:
    # -- Enable redis
    enabled: true
    # -- Redis name
    name: redis
    # External Redis parameters
    # externalRedis:
    #   # -- External Redis server host
# host: "redis.databases"
#   # -- External Redis username
#   username: ""
#   # -- External Redis password
#   password: ""
#   # -- External Redis server port
# port: 6379
#   # -- The name of an existing secret with Redis credentials (must contain key `redis-password`).
#   # When it's set, the `externalRedis.password` parameter is ignored
#   existingSecret: ""
#   # -- External Redis Secret annotations
#   secretAnnotations: {}
## Server
server:
    # -- Argo CD server name
    name: server
    # -- The number of server pods to run
    replicas: 1
    ingress:
        enabled: true
        annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        ingressClassName: nginx
        path: /
        pathType: Prefix
        tls: false
        extraTls:
            - secretName: local-wildcard-cert
## Repo Server
repoServer:
    # -- Repo server name
    name: repo-server
    # -- The number of repo server pods to run
    replicas: 1
    # -- Environment variables to pass to repo server
    env:
        - name: HELM_PLUGINS
          value: /gitops-tools/helm-plugins/
        - name: HELM_SECRETS_CURL_PATH
          value: /gitops-tools/curl
        - name: HELM_SECRETS_SOPS_PATH
          value: /gitops-tools/sops
        - name: HELM_SECRETS_VALS_PATH
          value: /gitops-tools/vals
        - name: HELM_SECRETS_KUBECTL_PATH
          value: /gitops-tools/kubectl
        - name: HELM_SECRETS_BACKEND
          value: sops
        # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
        - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
          value: "false"
        - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
          value: "true"
        - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
          value: "true"
        - name: HELM_SECRETS_WRAPPER_ENABLED
          value: "true"
        - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
          value: "true"
        - name: HELM_SECRETS_HELM_PATH
          value: /usr/local/bin/helm
        - name: HELM_SECRETS_LOAD_GPG_KEYS
          # Multiple keys can be separated by space
          value: /homelab-sops-gpg/sops.asc
    # -- Init containers to add to the repo server pods
    initContainers:
        - name: download-tools
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -ec
          env:
            - name: HELM_SECRETS_VERSION
              value: 4.6.10
            - name: KUBECTL_VERSION
              value: 1.34.1
            - name: VALS_VERSION
              value: 0.42.4
            - name: SOPS_VERSION
              value: 3.11.0
          args:
            - |
              mkdir -p /gitops-tools/helm-plugins

              GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/')
              wget -qO /gitops-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-${GO_ARCH}

              GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/') && \
              wget -qO /gitops-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${GO_ARCH}/kubectl
              wget -qO /gitops-tools/sops https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.${GO_ARCH}
              wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_${GO_ARCH}.tar.gz | tar zxv -C /gitops-tools vals
              wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /gitops-tools/helm-plugins -xzf-

              chmod +x /gitops-tools/*
              cp /gitops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /gitops-tools/helm
          volumeMounts:
            - mountPath: /gitops-tools
              name: gitops-tools
    # -- Additional volumeMounts to the repo server main container
    volumeMounts:
        - mountPath: /gitops-tools
          name: gitops-tools
        - mountPath: /usr/local/sbin/helm
          subPath: helm
          name: gitops-tools
        - mountPath: /homelab-sops-gpg/
          name: homelab-sops-gpg
    # -- Additional volumes to the repo server pod
    volumes:
        - name: gitops-tools
          emptyDir: {}
        # kubectl create secret generic homelab-sops-gpg --from-file=sops.asc=assets/gpg/private2.gpg
        - name: homelab-sops-gpg
          secret:
            secretName: ENC[AES256_GCM,data:QctXOcnrE7+Mtn2NBc9BhA==,iv:vsQFI2MLPlHFnujGS63nYdxlpdAioXnic/zDaWNfuO4=,tag:RWyf596Gi5DDoBqrOIE3KA==,type:str]
## ApplicationSet controller
applicationSet:
    # -- Enable ApplicationSet controller
    enabled: true
    # -- ApplicationSet controller name string
    name: applicationset-controller
## Notifications controller
notifications:
    # -- Enable notifications controller
    enabled: true
    # -- Notifications controller name string
    name: notifications-controller
sops:
    lastmodified: "2026-04-13T20:28:40Z"
    mac: ENC[AES256_GCM,data:oHrw0nrSo3fLNnlnT5ueF2zgdk1M1LJqjUgn/mB8Jcz9BDLfTza6HzC4Yvu3JbViy87m2L2L4wnhzQaukM4sjLkwafmypg53fKCtxJX2PZGg8vLiINMyY0hMXjNO3h2CruUy8QiIA3HkkDcKvezjMb8Cn+rhEF2rEakH0cIrOE8=,iv:sbshVjTyyzQLPFnQsL5sziDZYQZl5ZNdXkjuMeWdP/E=,tag:hC4C1rgev3hV8Te5OaRq5Q==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAsUjDhwxQlR+uUsVMWPUYmDltUJJg+Gpq8Lcscnl3SjeI
            uGyjzOYz03G2LitpHcMaPsnuR8OhDdsRNhh3UpONkTd7PzGrw3eb1lNS+l6KeRHd
            UrXeXDlrvwvMSiTEMuFDmwW81Gyd4GQyQ/A746RHDE7CYZd2+D4IcyOe9Byo7+Iz
            7eQisbz/uj9TSFVGG9fTrMQ7/oQRHluESQ7SZWihyOpK0+jWymRqcab+218YYCxX
            2vUKpE25g1sDUg31p6//Cmj+/6lXtpXe3cgGN6d5ktlyJAjz0KX+hq5XjvhqVni9
            SIpiwUVmoCAxfa9q0WZ2O0Dn1VWVsIBFB+b1imxpyMAFS9ZXeR1jw1kjeATrMEuP
            UCqP15upMrW3AICG4hReVNMme0Dr7m/PnTGsGqzCpqta0KWoachaOoRO4nrTycFd
            uSMDyvvwSUqY1sNnUJsOWQjsgLtnbGJrw+mkM+y1FdOgD5UTWmYFNiwEKiqhXEOy
            s5FRlVUmlRRjTYTMLz4fPGuloSc8n6vKA7Zu1ibSYy475nqPtmY7BI4HYUkSyWLd
            rcSarLhmf/TbxfQq4AawiRM8Ok0kkmvUTvcZyyIsSges7msZF0eXLwJlp5I2ievb
            G2Emf2j9GKAbhUcXx7k8iAZQLUGGPXWwmeTgdsVEYFOCJfuhv98a0dU05JZQQPDU
            aAEJAhDJqcDWKrvN7KcMK/cr29pX6JHACknzZMsq/lcW8FLy54EEgiFsQi0eF/h3
            NIdHZssO+sifgvMZeYq3Kjjo7CAbaQD06FvR8DUo80tpZDG0d0vQcfh/rlMN3kdW
            V/7fpycG2VVd
            =npjI
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin|oidc.config|secret|domain)$
    mac_only_encrypted: true
    version: 3.12.2
