# --------------------
# Speedtest Exporter
#   - Repo:           https://github.com/afonsoc12/speedtest-telegraf
#   - Docs:           https://github.com/afonsoc12/speedtest-telegraf
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
image:
    repository: ghcr.io/afonsoc12/telegraf
    tag: 1.37.1-dev
    pullPolicy: Always
ports:
    - containerPort: 9273
      name: metrics
      protocol: TCP
      service: true
service:
    enabled: true
serviceMonitor:
    enabled: true
    endpoints:
        - port: metrics
          interval: 5m
configmap:
    mountEnv: false
    data:
        telegraf.conf: |
            [agent]
              debug = false

            [[inputs.exec]]
              ## Commands array
              commands = [
                '''sh -c "speedtest --accept-license --accept-gdpr --format=json --server-id $(speedtest --servers -f json | jq -r \".servers | map(select(.name != \\\"Hyperoptic Limited\\\")) | .[:5] | .[(now*1000|floor)%length].id\")"'''
              ]
              interval = "10m"

              timeout = "60s"
              name_prefix = "speedtest_"
              tag_keys = [
                "isp",
                "interface_externalIp",
                "server_*"
              ]
              data_format = "json"

            [[outputs.prometheus_client]]
              listen = ":9273"
              metric_version = 1
              path = "/metrics"
              expiration_interval = "5m"
              collectors_exclude = ["gocollector", "process"]
volumeMounts:
    - name: config
      mountPath: /etc/telegraf
volumes:
    - name: config
      configMap:
        name: speedtest-exporter
resources:
    limits:
        cpu: 25m
        memory: 256Mi
    requests:
        cpu: 10m
        memory: 50Mi
livenessProbe:
    httpGet:
        path: /metrics
        port: 9273
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
readinessProbe:
    httpGet:
        path: /metrics
        port: 9273
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
startupProbe:
    httpGet:
        path: /metrics
        port: 9273
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 18
    timeoutSeconds: 5
nodeSelector:
    kubernetes.io/hostname: k3s-m1
prometheusRule:
    enabled: true
    groups:
        - name: Speedtest
          rules:
            - alert: SpeedtestDownloadCritical
              expr: max by (hostname) (max_over_time(speedtest_exec_download_bandwidth{hostname="k3s-m1"}[30m])) * 8 * 1e-6 < 50
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Speedtest download critical on `{{ $labels.hostname }}`
                description: 'Download bandwidth has been below 50 Mbps for the last 30 minutes. Current value: {{ $value }} Mbps.'
                dashboard: ENC[AES256_GCM,data:8MWMChW53SV8nNdlS+tO7GijaJT7PlBTsk+PzO9fFdhI2PaqeX5JyZfsSCBmJkEuTvbfm/doxbmDbrO4cW8mmq/ef5JCi9swbeX+CYX4ciDqLsr7Fw==,iv:eyA96X/Q1K8L9bXpHlsshJZaJFCFMH45NDqrK2tVA3E=,tag:6jkMV/YnSiA84yqN2MmGsg==,type:str]
            - alert: SpeedtestDownloadLow
              expr: max by (hostname) (max_over_time(speedtest_exec_download_bandwidth{hostname="k3s-m1"}[30m])) * 8 * 1e-6 < 400
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Speedtest download low on `{{ $labels.hostname }}`
                description: 'Download bandwidth has been below 400 Mbps for the last 30 minutes. Current value: {{ $value }} Mbps.'
                dashboard: ENC[AES256_GCM,data:8MWMChW53SV8nNdlS+tO7GijaJT7PlBTsk+PzO9fFdhI2PaqeX5JyZfsSCBmJkEuTvbfm/doxbmDbrO4cW8mmq/ef5JCi9swbeX+CYX4ciDqLsr7Fw==,iv:eyA96X/Q1K8L9bXpHlsshJZaJFCFMH45NDqrK2tVA3E=,tag:6jkMV/YnSiA84yqN2MmGsg==,type:str]
            - alert: SpeedtestUploadCritical
              expr: max by (hostname) (max_over_time(speedtest_exec_upload_bandwidth{hostname="k3s-m1"}[30m])) * 8 * 1e-6 < 50
              for: 0m
              labels:
                severity: critical
              annotations:
                summary: Speedtest upload critical on `{{ $labels.hostname }}`
                description: 'Upload bandwidth has been below 50 Mbps for the last 30 minutes. Current value: {{ $value }} Mbps.'
                dashboard: ENC[AES256_GCM,data:8MWMChW53SV8nNdlS+tO7GijaJT7PlBTsk+PzO9fFdhI2PaqeX5JyZfsSCBmJkEuTvbfm/doxbmDbrO4cW8mmq/ef5JCi9swbeX+CYX4ciDqLsr7Fw==,iv:eyA96X/Q1K8L9bXpHlsshJZaJFCFMH45NDqrK2tVA3E=,tag:6jkMV/YnSiA84yqN2MmGsg==,type:str]
            - alert: SpeedtestUploadLow
              expr: max by (hostname) (max_over_time(speedtest_exec_upload_bandwidth{hostname="k3s-m1"}[30m])) * 8 * 1e-6 < 400
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Speedtest upload low on `{{ $labels.hostname }}`
                description: 'Upload bandwidth has been below 100 Mbps for the last 30 minutes. Current value: {{ $value }} Mbps.'
                dashboard: ENC[AES256_GCM,data:8MWMChW53SV8nNdlS+tO7GijaJT7PlBTsk+PzO9fFdhI2PaqeX5JyZfsSCBmJkEuTvbfm/doxbmDbrO4cW8mmq/ef5JCi9swbeX+CYX4ciDqLsr7Fw==,iv:eyA96X/Q1K8L9bXpHlsshJZaJFCFMH45NDqrK2tVA3E=,tag:6jkMV/YnSiA84yqN2MmGsg==,type:str]
            - alert: SpeedtestLatencyHigh
              expr: max by (hostname) (max_over_time(speedtest_exec_ping_latency{hostname="k3s-m1"}[30m])) > 50
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: Speedtest latency high on `{{ $labels.hostname }}`
                description: 'Latency has exceeded 50 ms for the last 30 minutes. Current value: {{ $value }} ms.'
                dashboard: ENC[AES256_GCM,data:8MWMChW53SV8nNdlS+tO7GijaJT7PlBTsk+PzO9fFdhI2PaqeX5JyZfsSCBmJkEuTvbfm/doxbmDbrO4cW8mmq/ef5JCi9swbeX+CYX4ciDqLsr7Fw==,iv:eyA96X/Q1K8L9bXpHlsshJZaJFCFMH45NDqrK2tVA3E=,tag:6jkMV/YnSiA84yqN2MmGsg==,type:str]
            - alert: SpeedtestNoRecentData
              expr: sum by (hostname) (changes(speedtest_exec_download_bandwidth{hostname="k3s-m1"}[30m])) == 0
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: No recent speedtest results on `{{ $labels.hostname }}`
                description: No new speedtest download result has been recorded in the last 30 minutes.
                dashboard: ENC[AES256_GCM,data:8MWMChW53SV8nNdlS+tO7GijaJT7PlBTsk+PzO9fFdhI2PaqeX5JyZfsSCBmJkEuTvbfm/doxbmDbrO4cW8mmq/ef5JCi9swbeX+CYX4ciDqLsr7Fw==,iv:eyA96X/Q1K8L9bXpHlsshJZaJFCFMH45NDqrK2tVA3E=,tag:6jkMV/YnSiA84yqN2MmGsg==,type:str]
sops:
    encrypted_regex: ^(dashboard)$
    lastmodified: "2026-08-21T13:56:35Z"
    mac: ENC[AES256_GCM,data:45peAEed2+1bipJSM3YcyjV658vX9xigKtv66/5qzriXo+jJzbFPIh2LUpxh3x9lTAoLbHcKRc/UShWRoMBfoaMos3ewO2PtSptg4lrOeIsvL5U+GRK87RcrI1lBXHjA0tFo/xqVfXmzxjdAN/8iteGaIUKfq5ELbhfZQV+KhZ0=,iv:84llGBd7Tir5euQ+xfff8Z6NVXnpok20d/dO+efr2ec=,tag:dmC+4q2V+QekZ+QL0G0QRw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-04-13T20:28:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+Lf7dC99mY+wgq5NoXi2fMM54khsbXmJpHnAA3INHAqI8
            zRW+q4aQk9YNokMmyIbQFXbfCnOIZ1LFxUaljWNu/KEYTbPkMQZNw7ippZifCq/O
            c0Phau2Ry2/050ZQKyqLne4gnox5bWcCEXWVBraXLmzwP50cb/FqnLQMdOYlL+Lg
            ZW350OHw/hpsDtSirhCKmS5/aY+TLAnmbVXduajjTpnNRrxfIKvj3WodR0vBpBEv
            9LAqjxa0CeMjO0xWzL+sldqT8q3j17Abf81a6FQfaSSHNd91cFKX7s2r6Nu26Gru
            FL/Yb0bS/sLKSs73NvV32Nkb7HJQ2HueLftPpiSdcSVywog0du4hJocb+ob5F+tf
            D9bgtQWsn6tC6D/KBL36bujidKLnCViOpe9eRtVOHmRT8W4Ih+tGnGAfcFUWQZ6s
            aeJ5w5m5L5h6hVaLFSdI4P9rclmQQe0DE39i/Jgu9uuQvlG/Xlp+2bspdtfAnFYP
            wtnqmdGIYTr4JeGAcgJJ878+Q0IfU1rOZJCIM9dIlm79Ae53m+EasM90NWAtNjH2
            URRl90KTvo90aQabsypa37ZNvhnZrCj1Sl0Win1BKVmYJeoRRbOZQFCYqGrlgDru
            DsgUQxPRvkrtF2duMHgRJuReBahNX15MILFVskq7/ZDTdcZpIh49aA6MsCtoB/nU
            aAEJAhC3cKiOon0acbmGCndSDecRYzXbvhELhnsFXAGzfj4Nf0ARxz/vqwDn2Rh+
            C55tWK2XT5rtc8HmfI7PPbrlUc1vkE6/v1F7OWSGGmcu+DMUBHpl6IEMc3z3rI6I
            tM+5Rl0plG43
            =GvhM
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
