# --------------------
# Bambuddy
#   - Repo:           https://github.com/maziggy/bambuddy
#   - Docs:           https://wiki.bambuddy.cool/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
nameOverride: ""
fullnameOverride: ""
labels: {}
podAnnotations: {}
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: ghcr.io/maziggy/bambuddy
    tag: v0.2.4.8
    pullPolicy: Always
hostNetwork: true
ports:
    - containerPort: 8000
      name: http
      protocol: TCP
      service: true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        DATABASE_URL: ENC[AES256_GCM,data:aGL8ftxt12HSTFsRF+ibXjmW0Cp2yJunItvUUTRXwsxC4OW2tjnb+zAWBHKBg/57DUzbn+aNkoQdFjMiWJfa8l6gAKtlcExSOMSZEYPgkp5NrE8CF5gnsZKImg==,iv:cs8u8VrWWzvoRD/44aZiDroS3IexjbJeBIgLUkxhbJw=,tag:7Fq/u0Zv9B066kYPWN3iyw==,type:str]
configmap: {}
volumeMounts:
    - mountPath: /app/data
      subPath: data
      name: data
    - mountPath: /app/logs
      subPath: logs
      name: data
volumes:
    - name: data
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    tls:
        - secretName: local-wildcard-cert
    hosts:
        - host: bambuddy.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
resources:
    limits:
        cpu: 500m
        memory: 512Mi
    requests:
        cpu: 50m
        memory: 256Mi
sops:
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    lastmodified: "2026-07-04T17:39:34Z"
    mac: ENC[AES256_GCM,data:PheVUk5Pa/mxVQ3q09XEMkAJ4u06POVLe+VSJGeHfizmv49gAjtMIn2qIZfegUViXq6Lden1F4USS9hXb/kXaIrTk4xmgQf0qpnSUJy4xjs/YKZoaQDDv8UzYlMipm19XoSWmYqlIwWm3HA1RXItlQ+rDaqXrHoSnIVezI9qZjk=,iv:cnb5KuAzvMLdXakHs+ATmJPdDngo6fYF/HciAa7AAz8=,tag:5Z4XoB8+q6Y1+NYpu7TT1A==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-07-04T17:39:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAl+XLRxaWkeEqQVFuQTkpbUH8yvEeoUQ2ifzLD0gotJpi
            xTwBC7H6SmnCPMKO75wP8NnxwK5M3vFWVthfZqLv6ZAJEPvPiwygtCAD5wLSEUsc
            vuexv8odfVwEJgA2lMsTyVnCI6wMerbFsedMZwAkKNV5Qh4p9spF6zA5vNimoLQw
            dvnVzapjy9XFxRJXngIvOr4+51IOGbfD6SSPKtorCimJ2p0tpzBmx3ccBlS9/H6g
            d+AqfX8CNBLmjloTL+bfzxO1FmwQCCRhYAelWyWUMZkOD/feRtTE3GOAeLNy79g8
            wbLeZAeLWbZySWu38ky1wrua31OTyTQRY8xWvZywLrW39f7X0a6LyWgzKKc1RglJ
            srmP9FteerkHFafWphB7NhEKY4fujj/Ba8DlBJFrhTx1KML1pq5XpoTKNMMVyvbN
            s1PLgzUiWzUIpIsFCYC4+trBJaJJCD/Vr9Mmfv3rxWLKYCcler/Yyp2jwgj5dTHK
            N9Uc6FK6/OEKFhtiJp7nvwrdE4nUSa7/K3m9SwswGSnEbNVrUrStCherSI8rP0pG
            Jo2XH03UWyMNjp3KEBgJwOPh/wBxZBEwihX1Ma2E0z7mFGBH1d2n4h1+wZmad78W
            fJjJKrXMZFoiVpadYLfoWXALcJUwohblBRz4dAiDOFtR3ShJ51LziFyumx8kqSTU
            aAEJAhCK52TAXRwO1ZWUOlfv+tK+MagBGjKO7QHaflDtw1yutK7vq2CVjK8C2V8E
            Gp2jlqYDNzexsyaIvtmU2VyTokLQEcc0Q2gK3AdKYU42s9z2VuRhCAgT0MVogaqS
            lv8J3f8A4F4w
            =Ghgi
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
