# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
    #TODO: REMOVE MEMCACHED< USE REDIS INSTEAD
    imageRegistry: ""
    ## E.g.
    ## imagePullSecrets:
    ##   - myRegistryKeySecretName
    ##
    imagePullSecrets: []
    storageClass: longhorn-persistent
## @param replicaCount number of replicas for the statefulset
replicaCount: 1
## @section Service
service:
    http:
        type: ClusterIP
        port: 3000
    ssh:
        type: ClusterIP
        port: 22
ingress:
    enabled: true
    className: nginx
    annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.ingress.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:Psj7XnVeLo0wx/H6BOPi36c0ZRtaZo5612DPB9GnxCET9T7zmPYSYmujGWQU,iv:vOMtrO2ZoNnCKZOSowMKagmCTmwwIzEyZXq96/dvTw4=,tag:6t/5zNhJs2uXyzaRckbYAg==,type:str]
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
    hosts:
        - host: ENC[AES256_GCM,data:g8qKE3P0NTs9u0kq28Y7V7k=,iv:7BaSk0KdNC2QbTzJXyWYHQ1d4kjA6Z2LGKbRlwfun0I=,tag:vxRp/JT0O3nFTMywuaMlxA==,type:str]
          paths:
            - path: /
              pathType: Prefix
    tls:
        - secretName: git-cert
persistence:
    enabled: true
    size: 10Gi
    accessModes:
        - ReadWriteOnce
    storageClass: longhorn-persistent
gitea:
    ## @param gitea.config  Configuration for the Gitea server,ref: [config-cheat-sheet](https://docs.gitea.io/en-us/config-cheat-sheet/)
    config:
        database:
            DB_TYPE: mysql
            HOST: mariadb.databases
            NAME: gitea
            USER: gitea
            PASSWD: ENC[AES256_GCM,data:jzD7VNm1o6/hEoldlwn/DhTYH08=,iv:krASRbNl3sC9SlOP1qJ2AbNddjp15laQrHwFwv4XPL8=,tag:la4tNK/r3/YMz3tLOov2Cg==,type:str]
        task:
            QUEUE_TYPE: channel
            #  APP_NAME: "Gitea: Git with a cup of tea"
            #  RUN_MODE: dev
            #
        server:
            SSH_DOMAIN: ENC[AES256_GCM,data:XFfbGNQv/794PZdw7ZMGqCikwm5G,iv:0qYI+eQk2KnJbReOw2QfiHSRyynZn2maytGWRZK7Mkg=,tag:CSfg0hmVbfvphYnloIsbJA==,type:str]
            # rootful image
            SSH_PORT: 22
            # rootless image
            SSH_LISTEN_PORT: 2222
            #
            #  security:
            #    PASSWORD_COMPLEXITY: spec
        service:
            DISABLE_REGISTRATION: true
    livenessProbe:
        enabled: true
        tcpSocket:
            port: http
        initialDelaySeconds: 200
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10
    readinessProbe:
        enabled: true
        tcpSocket:
            port: http
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
memcached:
    enabled: true
    service:
        port: 11211
postgresql-ha:
    enabled: false
redis-cluster:
    enabled: false
sops:
    lastmodified: "2026-04-13T20:28:42Z"
    mac: ENC[AES256_GCM,data:91ZU30ClSFwqAx111Cw2qQs78f+rmnN5giunKQP2+eu4hBc4JcHAbEfZ7lKNCF2OVl+yxNqnpObeONMsdHVErl0hpwMkI4XNCyG+3pzoXcH6AJBb3IaE9fbBMiRB+600xIr3nqM5BK7VW8dG5hauRBoUCRiKIR9wy093UVDpcT8=,iv:GGeP7PhW/J0u2vdDdTm9HPvQNM5pUMDR0DJndPqo1Og=,tag:84eC2H1Sk1wL0FzSK2fcRA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//bMALeA7DjD1aT37a7QfiRuRPxLGxCuVbRKYf60T/l3SH
            Fgxnchk/ieo3maTwrCVwHh9XR2eMfY/CBis3s/mWIehoGbxoT9UGQBBo7hnBt5Rw
            iVnHER8jP7Az843z0sO1T2rOPns4dbtTNZ+mXlxMGEJvEMtbYt4BAxXpPx7KsuY8
            OcsnCBMM+hNtL1g7zsOx6wLc8NPm6RjVUVhKLFrXOI4PWbq9ZDEUMJSKmcntePtm
            ReNmdbZ7fP9tCzCaiwRgY9H6VkalQ3ViKSKn1Qloxh1O67WnXHhHaivSckAtl3AR
            yitHrSxatf19IcNuHNu4YWfKSk3n6MhayHcuP3S3lwh+MIPiZYsdVEsgJA+ueHto
            +xqzcnCJfsy22CBZO8zteZwqoaLgyaG2JYQzLhAX8Sh62AlYZIAXM1LIfSf0avFo
            7qn/uuuNsXuLoYWGUg978qPtyqSgcTbCX1VZHPen7seKBE25JNn7tfXiccR5WuJi
            rrowSgqj/noC0hH690IYaS57EEks7IEbn5DHwUiSzcGvAFRIhoJE5lMkG7Yg3EVj
            oybYnhGh98x3g9G702kb61ashAPfmInhSPkmFFvVQNznAfvBC85zSKzG1TwDEO+/
            8oIqLgzW+XDqJ4ecjOhJo1wYNt8YjLI0Q0O5Xw6eDIiH6txH+Dck/I8OaUuwyq3U
            aAEJAhCTeEY5G8Z/UgSG3x3EGbllQiIQ2Jh/L44FLgI5YceR36cjbqkxqd4dzb9A
            oXwrAx7qhXIK7nYQa2MZdh6GFJUpaGwZWN/UygIiYltN/ADT4Z4SVHPa9SENf5nc
            U96ogizKeEnO
            =/gQC
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(nginx.ingress.kubernetes.io/auth-signin|host|PASSWD|SSH_DOMAIN)$
    mac_only_encrypted: true
    version: 3.12.2
