nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: koenkk/zigbee2mqtt
    tag: 2.9.2
    pullPolicy: Always
ports:
    - containerPort: 8080
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
volumeMounts:
    - name: data
      mountPath: /app/data
    - name: dev
      mountPath: /run/udev
      readOnly: true
    - name: dongle
      mountPath: /dev/ttyACM0
volumes:
    - name: data
      mountPvc: true
    - name: dev
      hostPath:
        path: /run/udev
    - name: dongle
      hostPath:
        path: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 512Mi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: null
    tls:
        - secretName: local-wildcard-cert
    hosts:
        - host: z2m.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext:
    privileged: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
nodeSelector:
    kubernetes.io/hostname: k3s-m1
tolerations: []
affinity: {}
sops:
    lastmodified: "2026-04-13T20:28:41Z"
    mac: ENC[AES256_GCM,data:k1tY0argHbhnMnk8IeC30c40q5Wx9lL2Wqb9khVvr7OcGKfIMkjcNh5MwVzavDuxD/3eRaFK2w2i1FFXGm9hvglSY3IT+Cm25aBZDtDedvLlaCO2K3J5yMmJoBC6q0411YWjcWQR36d6rC2C5tKS0FHvk2ac4MYdNoOgLulrn8E=,iv:jQwyMoBwbLMk6oPrSXWFV2JdhqZw3ClC5x2Sf7lSiiE=,tag:2ldCOgE8a9Z+caYEKS/m6Q==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//cZCnPA1W3CfczwW9SZCRIrh/B8Y/KfR+3H3lE4MZ1lsT
            IPbhhtnHdsX5YAh+DPSZoMtXEhkXv1Q7NhJoIw61w+hTUQ3+S2sdy1kvyKVHmglP
            2RqoMMB+bXXB3+7TJjN2PcsLjoeRi5xi8tEiGQeCRCVZerGljNghOocKI+gPdL2/
            LON91uNK1z2wq/IxPstnC0D5vaQQxEw5o6p5IW1/yrf6D007lWqwrss0rWMjqToW
            Ml18ZGcxHfXjqXfWaxSIE2I9alriQcXtq570Y3yrsAxBxk3qQ16Of7c2sAklGcXB
            xHQQ01AA5elfPDxtQ6T0eJbboKggxRHGRJuygaliRnP3w+zPWV9a5puntrCpuWz6
            TFSlZBe2u6swy2MLq8ZneuMv1awG3QinVXvCA/lHeOJ8h30C2HRx0VMeJ/C/IKPA
            CZsbTR/vGIkdYcPoSyhFidwuAkN4gb4mVMCqaHGE1Kqv3qmf7Lyp8ecj3BdXWYNj
            XYNXaTgLIBHYy39WKH6mMsAU2Q2wOxNYlS6AnetM3w7gKVymN7iulNAfWx316Mbi
            RDOKDfw2mzOy8+USSvtQ6XLVMfgfjAw+JnRmPQquwWItWJ5TuXgc6LtTtum43rip
            vq3tEKLkYy5SJQBcStwvdPVM7AKrZgilWFL4wSnvl18uyxwSRGCUw6IX3Y/idVfU
            ZgEJAhAfz3t47J6EAzVGODWeWn9kM8HIpHbDhebDFLBZr1ax3tWixISAJp54gnQV
            tgcb+tHwTGG/cPCZsmJLYfOhxZCDhl6xUoQL7fSORBInUG27r46N65hokEDWMyuF
            7IXkTqpHDw==
            =Am9u
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
