resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /api/health
    port: 8080
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /api/health
    port: 8080
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

startupProbe:
  httpGet:
    path: /api/health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 18
  timeoutSeconds: 5
