{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "cert-manager-resources.labels" $ | nindent 4 }}
stringData: {{- toYaml .stringData | nindent 2 }}
data: {{- toYaml .data | nindent 2 }}
{{- end }}
