nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: binwiederhier/ntfy
    tag: latest
    pullPolicy: Always
#   restartPolicy:
command: {}
args:
    - serve
ports:
    - containerPort: 80
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        NTFY_WEB_PUSH_PUBLIC_KEY: ENC[AES256_GCM,data:+vnXcc7a5VTex5XBdNlIbLLI2uVhtyIHqkY49y2jXHSAu9gYQ6yC3fSjxVbnMOeXLuzfP11hMa44//wHzlAqOukQ88gqcO6kzD3twS+1SoGMLwZb1fUj,iv:fqlIsIkanPU0Aw8Wsr76A7yQsb2fDdWzKyAl9SklgDo=,tag:TOP/9EnOWHvGKTnxPJ8ppA==,type:str]
        NTFY_WEB_PUSH_PRIVATE_KEY: ENC[AES256_GCM,data:UJ68+I2V68NAWTkQPef3Li/ihd8wy2hErjI9DZRyZ9y1bhW8RqED8odA8g==,iv:gsDljxJ/DsWmuBhIC688ttJYLVgMo0F8Tbuvutw2FFw=,tag:fcubppTTsRdnsRq3hc7sHA==,type:str]
        NTFY_WEB_PUSH_EMAIL_ADDRESS: ENC[AES256_GCM,data:k5uTYFjTVLi1OB3HiWjC5GncDOZiE6E/MblABw==,iv:jeS/mY7vRLlk7XWbCjMQkB1r+3yEflDGPXp4iH7FC+k=,tag:mh9FjVwv7n95DIuF2hEinQ==,type:str]
configmap:
    mountEnv: true
    data:
        NTFY_LOG_LEVEL: info
        NTFY_BASE_URL: https://ntfy.local.{{ .Values.domain }}
        NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
        NTFY_BEHIND_PROXY: "true"
        NTFY_CACHE_FILE: /data/cache.db
        NTFY_WEB_PUSH_FILE: /data/webpush.db
        NTFY_ATTACHMENT_CACHE_DIR: /data/attachments
volumeMounts:
    - name: cache
      mountPath: /var/cache/ntfy
volumes:
    - name: cache
      mountPvc: true
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 200Mi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: null
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: ntfy.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
sops:
    lastmodified: "2026-04-13T20:28:45Z"
    mac: ENC[AES256_GCM,data:fL3nmf2ndVQfiwTz6wxd3H79VqwlMbc9BJ1YqjwNwLxFZnFPnvD4LmUZfTuJSlOaLcpUPD06Sf/idcERIYt16jWUQy0n0wqb87IaTxvm+hjilaHz+emTxAdIe83KrEeUUPr+DPzvwZRE2vlZ/9JHJZN2fTOjPQIYcxkfrT6bEZg=,iv:Dk0cJa+ayrq6vy27u5ulbkcjbLDWSry9LHs0dbM7LLg=,tag:MyUtQg1UOnxX9sgNsH51XA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAhUC3VSnBMzKTNnub4tb+uSplViw1i4x65/JUdIZqtNqx
            N4/0LWCscOm5MxtOQ8mqE2Ckn4jHlLHCCFbzN7lygxaF2e+eAdqJoIpbyG/Cq3I/
            qmDIvdRNFMwygXdRIeBggO4w9GT80WDGDvC2Ye0wO9AQbBiYJq7puRSyzA9jCVrd
            gIrDk1xWrwvh+/WywrJDfgV/n1KtTKutmu33AiDJoR2GEY+yka3bAAISictuEwbd
            EwM4f5234UkTr7HYyWADR/9Y5XVuQ3QR8DILuwsgK/eU+NyAQMBC1SXbPz+58cW+
            +dDfmggjSey2lYog5FKKCl8ppMcchEMkdDAT8hrG+tIKlhGtXoNhcN/cFEP/PkUm
            8ftVib8te2f5fAt4k5WvhwhUhRX2H2VDNG1B9bOJMoVXxaUdqMrfAQXMiRY9mMN3
            nnV0NkAfTkuzjfDvV0mRChFpg7RpYzaJN1sIGh0k3a/1+Mnhk/ah70pUY/HIYT7B
            BnjiewfS+c+5QNWjkJXMkUwbsoz4HwJBQA6zECp5qIKjnhCebDnXIf0tMAVba2SV
            S91fP/RVy3guupYuu2y+haaZHp/uYj9fhMgl2TFChU9UchDwThpxmXQiPJHy2X23
            qlRh4mPli0uUh76U5QC5AHsSLHQnqa3ZmJuBlgmfedrECsLbfGssaLKtGbxVUjrU
            aAEJAhCmNMd2jr74Nw/elv//GXwpAe1YuerVqqYYlAEsVE7CJ4NHn1LQQcbX8O71
            zedRSJWKhk/TFvItnAYyB+DzVHA/3+Z40GEh7naa53J164Q8UzFzqsfnmU7aQ/6b
            4xZG2NeqWiiL
            =ct80
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
