nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: binwiederhier/ntfy
    tag: latest
    pullPolicy: Always
#   restartPolicy:
command: {}
args:
    - serve
ports:
    - containerPort: 80
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        NTFY_WEB_PUSH_PUBLIC_KEY: ENC[AES256_GCM,data:eDRbCQ4T3eqdCRRWTKwdC1wj61Uq+A7lmf6FYXNWvYF7jJhWTx3+FzNfwRA3rzs5jqlmtfrtaIixR6yt5P37VPOYeAy2nth6/H02xCAXrecMoSLkk5vB,iv:PQQWrdpuj4/I46TF8bm1Fu6FlSbQe0sVsHoCGJKlscM=,tag:boLOyvQRMF+aPvRYx+J0yQ==,type:str]
        NTFY_WEB_PUSH_PRIVATE_KEY: ENC[AES256_GCM,data:hRz6CvbLgEtSxfw4KeLlaNMucSHll9zv7PzciLaTz2N7cNTIgc3zBv2m3Q==,iv:kq2jIw26HmLfEWhxxHvK620wZT1UE6Kny1C9oGKLMlc=,tag:NTwJNGbjcE/5cn71OoD01w==,type:str]
        NTFY_WEB_PUSH_EMAIL_ADDRESS: ENC[AES256_GCM,data:vInO+HKSlK1CvX0oPxzFQ3FntIU0qD3gU41oQg==,iv:VRfz55AMDYqPmrmLUyuJ4V25H2e7wy/BoQY3tHd71Vg=,tag:iHTFjshKBe2nnKWYw1jznQ==,type:str]
configmap:
    mountEnv: true
    data:
        NTFY_LOG_LEVEL: info
        NTFY_BASE_URL: https://ntfy.local.{{ .Values.domain }}
        NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
        NTFY_BEHIND_PROXY: "true"
        NTFY_CACHE_FILE: /data/cache.db
        NTFY_WEB_PUSH_FILE: /data/webpush.db
        NTFY_ATTACHMENT_CACHE_DIR: /data/attachments
volumeMounts:
    - name: cache
      mountPath: /var/cache/ntfy
volumes:
    - name: cache
      mountPvc: true
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 200Mi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: null
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: ntfy.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-14T22:55:36Z"
    mac: ENC[AES256_GCM,data:EZA0kwBZa3GVRimIilRc7eC9c61pcw38k5dzZ8hK84llgLVP+bnP9U4V/y/wQee9trofEw4c/N0Q6EK3vF+rGhF2CTEaxybWFmRNpHgKjnrfCetTzQrOXfxPZiOCijRcCfcr2LbHBin2DISRuC5+m0/C3XynpAiA6eWXfpQtOko=,iv:cEEwh+/1bi0uc7pbpDYE7kgIUurtupYTbqmLj6Bblfg=,tag:U9QaYZYYW4jU0zMwQxpIDQ==,type:str]
    pgp:
        - created_at: "2025-10-14T22:17:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+ObUbJ7xWNt0fl5AI+MoKVOnQ+USNNgRFcOlQ5omMit6A
            fF1Kld+wps1//LbYvoAIu9w18mLwlGZMMVPZn+84bF+T+uu7+sc0XBa7yU/Cvtj3
            s30y5UeomZ1rJVnRLGrOeBU6XCdBNnLJ16MWA3Oro4X9iT58+UPVvdoK+1+TdiMh
            yVcq22nPuCBpAGLSMIKUr9FWa+5pSPkbZZ/tG/1vylrv8Wm5ASgA47dJKzHP8YoO
            Hwfo/XifnG5D+ENMoZSQSW04Zb2Jp6KE92yvQrvMqTZ1UogL5bTBrhaeviVxNVpi
            MDF+5AsqQsAorehvShYjUP4Y8848mCcFLzUrHgtdFAyUDTFqKGCX3iJUbgm/MziT
            VSE/fkt9jHDPaBY+jK86/QGzdFoQsG8G/nhBXNhscbulEB5LTJZCL4DR1HAMKnpn
            iuYyo5AhtR+NlGjym6VneEJny/wMuQ3bWvat8+fZeHbEIXII2Gd5ZP2JZKOoLDPi
            7+Gd6poo9FTGNegk9h/7S74Z9xW2CK9S8bx0D1ELFwgOG1ZI5eBWuYcnuE9eF1T9
            QoBj1UT4slp5jfCYLuGz5gOgLa++aR0+El3GYvVs5Wqzaw1/hDp7mvpWQiU8RJcC
            nHuPPGsslZSzGx8ejKtlReXE9YrafFZpRSldNkLvehR80mhjmanEkBC31vjFcQPU
            aAEJAhBRJLR/V3CaGgQFQy4z0xJ17k/fwefLLgyimmYL0nE7kkmUcYzI80+BKuaU
            TuJaq0RbSQiRUqeKepgo0nkEHJUuUSoGtkhgqCfz+yHyqUHAA4y3GNoH9D0+PaR0
            NYNXjiT6cnEn
            =zWfQ
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    version: 3.9.4
