---
- name: Update packages and dependencies
  become: true
  block:
    - name: Add user to sudoers without requiring password
      community.general.sudoers:
        name: "sudoers-nopass"
        user: "{{ ansible_user }}"
        commands: ALL
        nopassword: true

    - name: Apt-get update
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Apt-get dist-upgrade
      ansible.builtin.apt:
        force_apt_get: true
        state: latest
        upgrade: dist

    - name: Apt install (base + group + host)
      ansible.builtin.apt:
        force_apt_get: true
        name: >-
          {{
            base_apt_packages | default([]) +
            group_apt_packages | default([]) +
            host_apt_packages | default([])
          }}
        state: latest

    - name: Apt clean
      ansible.builtin.apt:
        force_apt_get: true
        autoclean: true

    - name: Apt autoremove
      ansible.builtin.apt:
        force_apt_get: true
        autoremove: true

    - name: Apt purge
      ansible.builtin.apt:
        force_apt_get: true
        purge: true

    - name: Pip install (base + group + host)
      ansible.builtin.pip:
        name: >-
          {{
            base_pip_packages | default([]) +
            group_pip_packages | default([]) +
            host_pip_packages | default([])
          }}
        state: latest
      when: (base_pip_packages + group_pip_packages + host_pip_packages) | length > 0

    - name: Set cron to update caches
      ansible.builtin.cron:
        name: "Update caches"
        hour: 4
        minute: 0
        job: "apt-get update"
