---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      targetRevision: '>=1 <2'
      chart: longhorn
      helm:
        valueFiles:
        # - $values/kubernetes/apps/values.sops.yaml
        - $values/kubernetes/apps/longhorn-system/longhorn/values.sops.yaml
    - repoURL: git@github.com:afonsoc12/homelab.git
      targetRevision: HEAD
      ref: values

  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: longhorn-system
