nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: binhex/arch-privoxyvpn
    tag: latest
    pullPolicy: Always
#   restartPolicy:
command: {}
args: {}
ports:
    - containerPort: 8118
      name: privoxy
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        VPN_USER: ENC[AES256_GCM,data:suIa6Zmg20bqLOKZuejIGSTALO5SGE3M,iv:zYofW9Eexr4RdvhyxyujOgVfATJmUUG/VICUVKhP+LU=,tag:C0FYnylQ9jcndIrpojBMMg==,type:str]
        VPN_PASS: ENC[AES256_GCM,data:oE0Vom8Xmikwi5UKzsMkckU2NFGXjNVj,iv:13PWpjbKx+YmWBYxU3xTlV+YVsI3qXcFPeuGEzpD6wA=,tag:U/rWF4sK+WKk4QZDC30F5Q==,type:str]
configmap:
    mountEnv: true
    data:
        VPN_ENABLED: "true"
        VPN_PROV: custom
        VPN_CLIENT: openvpn
        LAN_NETWORK: 10.42.0.0/24
        # VPN_OPTIONS: <additional openvpn cli options>
        NAME_SERVERS: 1.1.1.1,8.8.8.8
        #          - name: SOCKS_USER
        #            value: <socks username>
        #          - name: SOCKS_PASS
        #            value: <socks password>
        #          - name: ENABLE_SOCKS
        #            value: <yes|no>
        ENABLE_PRIVOXY: "yes"
#          - name: VPN_INPUT_PORTS
#            value: <port number(s)>
#          - name: VPN_OUTPUT_PORTS
#            value: <port number(s)>
# DEBUG: "true"
#          - name: UMASK
#            value: <umask for created files>
#          - name: PUID
#            value: <uid for user>
#          - name: PGID
#            value: <gid for user>
volumeMounts:
    - mountPath: /config
      name: config
volumes:
    - name: config
      emptyDir: {}
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
securityContext:
    capabilities:
        add:
            - NET_ADMIN
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000
nodeSelector:
    kubernetes.io/arch: amd64
tolerations: []
affinity: {}
initContainers:
    - name: surfshark-config
      image: busybox
      env:
        - name: SURFSHARK_CONFIG
          value: us-las.prod.surfshark.com_udp.ovpn
      volumeMounts:
        - name: config
          mountPath: /config
      command:
        - sh
        - -c
        - |
          set -e
          cd /config
          mkdir -p $PWD/openvpn
          wget https://my.surfshark.com/vpn/api/v1/server/configurations -O configurations.zip
          unzip configurations.zip -d configurations
          cp $PWD/configurations/$SURFSHARK_CONFIG $PWD/openvpn
          ls -alh
          echo "Will use file /config/$SURFSHARK_CONFIG"
sops:
    lastmodified: "2026-04-13T20:28:42Z"
    mac: ENC[AES256_GCM,data:ZLmBJ/aQhn+KHImtDIkeq6WaQ+n8CbvMNBFT6qTISh372ZAhIPk3FLTOBYkq/2rmFn2mjWiG03tGxSdRsdxExLRiaoJ4P/cVmqu5PV3AvOyQB8mRwimQuDNgXjcULx2ZOMa7oN42IBHRoKXssjw/RxCiMBao1cP0YyrtJ44Phrw=,iv:mj5g4lao4TDpaxEP6lyKfPCiLSKZhkOvckmwS7HgFJc=,tag:2ZSLkz/wsyuFhzeb12EYTw==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//TWpbVC8d57kCiem4NjnC+7jno8BG/tT2AI4HihKxTD3U
            Xu+GA0Y7g3ETFRhfBFfq747vdbQzf6mBeuGqoHRRgg7f4JPP4AqtDxy15Asli9vj
            g6wdbjzuNdMDCNktbz52tUEHzH4XWKgb7bXtHLLvRLbVCJABNxH0SpOodM/R6Ei6
            9NT2bsM9TGgdP5zfKe4xbj5K38LcNu89qXqLKvIxFsP3qgvuSDHKxobHos3G25CI
            3MXlOwl8GIo/+JyJaX3Moh+QUamiReoG1Vl6IPZD88Evs69Prjh5yBNUX6/wUD0b
            npU4Ww/Sopf2Kl4G+nIkG61y6v1ioFDkCYBwUr2vmQeQt9Bme5trNhdLDMzEBeJO
            BvA1hGBCh+0wOR4/zXwfYJOdIWgX3qZjvkSm5cN2IvUBgIZaqZqZ/KiHmHJgmL+I
            wmnWGWtQbdbR0Lub3M5u/O8MC8fYJGkW0Ua8iOJN10JlJGFNwkETD2C5Dy1WOMLG
            qF5jdvh0GqsN2KFuhZIiWvo+2LC0/B+CbFGyvTujtr5mNv12NhzTEsmg91zfwHsV
            Z3WNHfsLyubFuAMwa862JpTsBP9d7g+EIUNhwj51LG5nlidiRRsREHrnSOyxVv11
            RxcpPyWlV1nIZ9da2PlGkE42mFfDax2GptZn9W8PRkCGK393rrjiwnFn1yE9uAvU
            aAEJAhAAwmMVBR3hEACbYjGh/kjri3fqxnp2XDThfgzWsp6Zy81WrLjn51k08VdH
            s9usPpBNo76x0XNtW06i32U1yfWNSMMQxc+i+wLRM3ttXBcAs43+7Qmd6cWZkqnj
            E4/rj7oM/QE9
            =n5O+
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
