# --------------------
# WLED Kitchen
#   - Repo:           https://github.com/Aircoookie/WLED
#   - Docs:           https://kno.wled.ge/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/external-svc/values.yaml
# --------------------
---
# Default values for external-service.

# Labels applied to all templates
labels:
  host: wled-kitchen

# External server configuration
server:
  ip: '{{ index .Values.ips "wled-kitchen" }}'
  port: 80

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: wled-kitchen.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
