---
raspberries:
  vars:
    skip_system_upgrade: true
  hosts:
    rpi-4b:
    rpi-z2w-hyperion:
unraid:
  hosts:
    hoarder:
docker:
  hosts:
    rpi-4b:
masters:
  hosts:
    k3s-m1:
    k3s-m2:
    k3s-oci-m3:
      skip_system_upgrade: true
nodes:
  hosts: {}
k3s_cluster:
  children:
    masters:
    nodes:
hyperion:
  hosts:
    rpi-z2w-hyperion:
