# --------------------
# Forgejo Runner
#   - Docs:  https://forgejo.org/docs/latest/admin/actions/
#   - Chart: oci://code.forgejo.org/forgejo-helm/forgejo-runner
# --------------------
replicaCount: 2
runner:
    config:
        instance: http://forgejo-http.devops.svc.cluster.local:3000
        token: ENC[AES256_GCM,data:DCS6AETeKraLh19eFOcJ4x4fTdZtsR35RuCNtXAL9GBnB2i4lkm8Q2n9zQ==,iv:aAzqqlWQdOjGl8z9UcGt62UsyNuzon5pd5p/xYwT+/g=,tag:h8jagAp3jVMKZ32U4RRq4A==,type:str]
        file:
            runner:
                labels:
                    - ubuntu-latest:docker://catthehacker/ubuntu:act-latest
                    - docker:docker://catthehacker/ubuntu:act-latest
                    - self-hosted:host
resources:
    requests:
        cpu: 100m
        memory: 256Mi
    limits:
        cpu: 1000m
        memory: 1Gi
sops:
    encrypted_regex: ^(token)$
    lastmodified: "2026-08-18T00:22:13Z"
    mac: ENC[AES256_GCM,data:wdkern7qZq6vXJ3ZYNq+cbBV8cQYYsiYMet2XN+XAKbVHErDeUECsW5IROm/GE7z/enG241JbgR2fVpZPeryqtPFgbcxojMLTnAt6iLlkWzkzpBmjhLHTI67C9WUbe82PdYXLZl5xGx+Zq3c4b0a3r10yZtTrwDpT7YBDKTE5zc=,iv:sTzBfUem+47oZi650+Z1oA9eIVAjcA4S+e2iuIj7LVg=,tag:RGoh17BQla8Hqc2ImQtSBg==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-18T00:18:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//cp3gvhqsi8u5HdG/kue0ibxrdteU7Rw8whB3BBl3reJY
            c6PEDrwRyrhzdWje59UyuMOOBThceRYdQVBhRkVKHQ4Do3LXNMM5QpYps73of9HW
            ygkBMRQLySh59JltnmkMPEYT74J8uX2Ru53hY64shNvvwY2FzsYo9lsY8++nJ/Mr
            S/ueZY2XMMeQ5JWQA39Z44OUdwRIb7F4vJGAukDCS/4POwL8J9yZqM/nfWKM94UT
            Qjgly0+IDw9R4rLpmcP2uLLm5b3EAu6//OlCh0dyMDTGE3lSlfgWyjHG18F72JYZ
            NTB133y1wx9fZ5CAusrHvaOAck2DBE8EMhWyQ1jJ6AwVSYNhfGtSZvzn77s1dwC0
            mA5u2se6uO6y30Jhb4DCN+yaJwRimPWkElDHUxw/EbPvuLL+iE1gl1f21UpyTTIr
            mvOSSTuweAB7BkwR8VCoWEqttw53BoVcj+Q5MKzKDHpCA2IUveu9HfHbh452Lksh
            wDjlZpRx6u8MKBAM469bjETZBuLjGIjpIOUHEysnFjeooQRyMd+vSi99U1qyo3w2
            rAPN5p291Y3PcTM8UJAkoY3IYitKYTGTR6F89IOR/0Wzk8+EkaydoWm0+eXbUete
            NPD45MQ6tN5D8Vq0RWTtS2W+RBdvGzCL5YWtgHxVpp8jAa8MjwODN+n+HswkzfDU
            ZgEJAhBYtu4hGHxq6zgI+YnKUeC53+0snaouUdctYWpSzChkX/RKQSA2YeJ27Gnl
            fXqOii05vIDIkbXO/Ebq0WiuMiOG5nGQ1CzCBtjtUZ/ZKOmpumuCpg8xeSa1uyKR
            BPhilvdDPQ==
            =FoGk
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    version: 3.13.2
