# --------------------
# Krusader
#   - Repo:           https://github.com/KDE/krusader
#   - Docs:           https://krusader.org/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/external-svc/values.yaml
# --------------------
---
labels:
  host: hoarder

server:
  ip: "{{ .Values.ips_tailscale.hoarder }}"
  port: 8088

ingress:
  enabled: true
  authelia: true
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: krusader.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
