# --------------------
# Hyperion.ng
#   - Repo:           https://github.com/hyperion-project/hyperion.ng
#   - Docs:           https://docs.hyperion-project.org/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/external-svc/values.yaml
# --------------------
---
# Default values for external-service.

# Labels applied to all templates
labels:
  host: rpi-z2w

# External server configuration
server:
  ip: '{{ index .Values.ips "rpi-z2w" }}'
  port: 8090

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: hyperion.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
