---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.io/charts
      targetRevision: '>=10 <11'
      chart: gitea
      helm:
        valueFiles:
        # - $values/kubernetes/apps/values.sops.yaml
        - $values/kubernetes/apps/homelab/gitea/values.sops.yaml
    - repoURL: git@github.com:afonsoc12/homelab.git
      targetRevision: HEAD
      ref: values

  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: homelab
