# --------------------
# Glance
#   - Docs: https://github.com/glanceapp/glance/blob/main/docs/configuration.md
#   - Chart: homelab-svc
# --------------------
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:afonsoc12/homelab.git
    targetRevision: HEAD
    path: kubernetes/charts/homelab-svc
    helm:
      valueFiles:
        - secrets://../../apps/values.sops.yaml
        - ../../apps/homelab/glance/values.yaml
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: homelab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
