---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: addons
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:afonsoc12/homelab.git
      targetRevision: HEAD
      path: kubernetes/apps/addons/argocd-apps
  destination:
    name: in-cluster
    namespace: addons

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
