# --------------------
# Firefly III
#   - Repo:           https://github.com/firefly-iii/firefly-iii
#   - Docs:           https://docs.firefly-iii.org/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/fireflyiii/core
    tag: version-6.5.9
    pullPolicy: Always
#   restartPolicy:
command: {}
args: {}
ports:
    - containerPort: 8080
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        APP_KEY: ENC[AES256_GCM,data:I1n8zpgnc1DmKFMupWQ9FDgOvx23x+JAVQHGH37qbEU=,iv:AbgN9sYw5rdBZ7mDvz9+bfpKygT+X1t8UHP3zDynr7s=,tag:Ld99zbaDZ+//Bf57ypBW4Q==,type:str]
        CRON_TOKEN: ENC[AES256_GCM,data:999Bl9mzUIhG3IF+gq+sJ7u55nQd4lspwY6RrHZKdKs=,iv:TpXeAIEKqoEL/xTXasBNkWOi0jLiyro8DdV/H65own4=,tag:A9LoMzHSb+WQHliHM09tFA==,type:str]
        DB_DATABASE: ENC[AES256_GCM,data:a8F10MajnA==,iv:qdaIak47u3cGcgRCes4/d1IfZUe8/R3tpB/QoO1l6jg=,tag:Nt8ycGN/aX5TbtLyZcA7/A==,type:str]
        DB_USERNAME: ENC[AES256_GCM,data:pxowDE5OLA==,iv:mhV5coWoZlpRB7zEOoRBMD09Pj7V8xE6gYjJQwm9Ctc=,tag:SfGYPuefUtD8cr8I36MZxA==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:ZMLgN9mkygYqZzkqWEPKKtUqRPQ=,iv:wmfyUOTGVjLV+fClwaesqXova1cp6AriFioWuHF8c34=,tag:ByHrFiIadodA3RQBCbZdmg==,type:str]
        MAIL_FROM: ENC[AES256_GCM,data:jAWAp83bMuUuRRTSNPh45KIJh2Gv,iv:JUgdeul2xptlC4+J8l/o4IQfb50fA3/iBHF6QbSyM9I=,tag:mBXg2RNE9KxL9TtS3i+abw==,type:str]
        MAIL_HOST: ENC[AES256_GCM,data:EUKana+wcIdPa5g9dF7tg0w=,iv:pApe2O5lL6sagTQsPFey5G9hebtELmGmtEuUTwbIRWU=,tag:zH33NPQT5536zRc7gQ/+og==,type:str]
        MAIL_PORT: ENC[AES256_GCM,data:NF5a,iv:Vgp9pcDuaw0Jc3WdO+udLc4bojqORJ2nYeJYsohZrCE=,tag:IoM8nshGPA1eXcyp3EwtGg==,type:str]
        MAIL_USERNAME: ENC[AES256_GCM,data:kZf4W7QT,iv:L/fU/Rcm/stOGfE/GacHuz3tsTix5ElY9C/X19oLKWA=,tag:53F+s9/fhb2fMA8iZdJgkA==,type:str]
        MAIL_PASSWORD: ENC[AES256_GCM,data:EivbRkfsgjaYTEi8VEZLroT7/xAzE6FcWehqvWg28IPhFd1gFSJF0wwOPbx54S6Piar2H3UOqr342xgd/eEUY9UdXtlD,iv:Ge0D7XlziljeU/uQzGOuGR6jcUvzPFnA0TVnWS/zgiY=,tag:nO394t+jggYlwLkbQNA17A==,type:str]
configmap:
    mountEnv: true
    data:
        APP_URL: firefly.{{ .Values.domain }}
        DB_CONNECTION: mysql
        DB_HOST: mariadb.databases
        DB_PORT: "3306"
        CACHE_DRIVER: redis
        SESSION_DRIVER: redis
        REDIS_HOST: redis.databases
        REDIS_PORT: "6379"
        TRUSTED_PROXIES: '**'
        MAIL_MAILER: smtp
        MAIL_ENCRYPTION: tls
volumeMounts:
    - mountPath: /var/www/html/storage/upload
      name: upload
volumes:
    - name: upload
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations:
        nginx.ingress.kubernetes.io/client-max-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: firefly-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: firefly.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - mariadb
                topologyKey: kubernetes.io/hostname
cronjobs:
    - name: firefly-cron
      labels: {}
      podAnnotations: {}
      schedule: 5 * * * *
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      image:
        repository: docker.io/curlimages/curl
        tag: 8.19.0
        pullPolicy: Always
      restartPolicy: Never
      command:
        - sh
        - -c
      args:
        - |
          curl -vv \
            --fail \
            --retry 5 \
            --retry-delay 5 \
            --retry-connrefused \
            --connect-timeout 5 \
            --max-time 15 \
            -H 'accept: application/json' \
            http://firefly:8080/api/v1/cron/$(CRON_TOKEN)
      env:
        - name: CRON_TOKEN
          valueFrom:
            secretKeyRef:
                name: firefly
                key: CRON_TOKEN
      affinity:
        podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  podAffinityTerm:
                    labelSelector:
                        matchExpressions:
                            - key: app.kubernetes.io/instance
                              operator: In
                              values:
                                - '{{ $.Release.Name }}'
                    topologyKey: kubernetes.io/hostname
sops:
    lastmodified: "2026-04-29T12:29:16Z"
    mac: ENC[AES256_GCM,data:kROTYCCS6ph/UsrCn51RM1Jv+6qWtfdrob+1JBVvholUjeHp8tV2HjCdbPc1oAHvkqkxfs+yBJ8KxhK9HzOCWZrdh1EDjJA0Nq0gIU/dgrjb00eFfN33XQXVh8okKtmJk58UQashPYTILV7JU/NmCIIk1r0NtcMo37zs6VqJGWA=,iv:ARC1v3WvZDNSxmBz7sKFRf0j8SGvNHhzNZACOr34OMg=,tag:9EfPyX4pmts5B6jNL7PlPw==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAnHhys/6GWctl77OGWvkukp+tk4gljQT7qfQjNb8vuuDa
            sHIqEsiaoR+XId9kL/6zy1w1G7y1giJ0PndwD4UMCrrkTyHQxG8JaLrIeGgq9mMN
            jk36QRwTenZVtsJE4CcCyLhe7eXlnbTp3+g3YCCLik3UyFishLqpzx4Rq3Et+KDf
            DpQZCvEBnhmsYWhr0odZQqWTksceFVbLetp8OnlWhzfPpJm0WkuIQ3m9Ur0ZZLfA
            6PMyVIVY9t7sMiW92mYmaEk05e21tg8Aqz9BqJlKP8F/DHh5h5q8Eec2gJp5gkFF
            jAyole6o0SrXausXRyuEqJGDuDAZXz9lk0YDw6t+leQHz8kERxE0O2T+Lq7L9lgV
            0ECV5v2Jy8oTWU/4N75cHQ56Fdl4xkLVrdo4SOQlnz1nX0JOArh3qemXeok2kNWi
            vgPEJsLzIvfupiDJp0BJTNX1eh5ZcaBg1phB2X+V6dyDA9avCyTUffg5kcS7VvNA
            a5hoPEdpp/ev8b8lJLqhdDKcB7UB3Ds2rzAeTs3P3BBdd/W0DecNCdrZuwkOhHoC
            pLWg9D2+CPfQ0YD9/wzw0VAQlvKlu8kNysj6JE/xWYZF0KQPjjFmqpknxeSNdEHM
            dlDXu+KX1JqXQKzPYbYzcBDZQGKGa6HpNrgz249riOQn40OaLNM37cWhckeisyXU
            aAEJAhBg09VtEOVahCsu2Tqxk3Id4fZ8Zs/osTY9YA5MUFSWqqtRD4HOAwhzzXrR
            o4UO9TIlYODkw7u/rUVCKd2XLqjIR/w0prP4+PsmZAmDj0/gk6FckCkbnjAWrxS3
            T5SKZWpO5SM7
            =WQ5L
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
