---
resources:
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: agnhost
      namespace: addons
    spec:
      selector:
        matchLabels:
          name: agnhost
      template:
        metadata:
          labels:
            name: agnhost
        spec:
          containers:
            - name: agnhost
              image: registry.k8s.io/e2e-test-images/agnhost:2.39
          restartPolicy: Always
