---
resources:
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: agnhost
      namespace: addons
    spec:
      selector:
        matchLabels:
          name: agnhost
      template:
        metadata:
          labels:
            name: agnhost
        spec:
          containers:
            - name: agnhost
              image: registry.k8s.io/e2e-test-images/agnhost:2.61
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 10m
                  memory: 64Mi
              livenessProbe:
                exec:
                  command:
                    - sh
                    - -c
                    - pgrep -f 'agnhost pause'
                periodSeconds: 30
                failureThreshold: 3
                timeoutSeconds: 5
              readinessProbe:
                exec:
                  command:
                    - sh
                    - -c
                    - pgrep -f 'agnhost pause'
                periodSeconds: 30
                failureThreshold: 3
                timeoutSeconds: 5
              startupProbe:
                exec:
                  command:
                    - sh
                    - -c
                    - pgrep -f 'agnhost pause'
                periodSeconds: 5
                failureThreshold: 6
                timeoutSeconds: 5
          restartPolicy: Always
