# --------------------
# Wallabag
#   - Repo:           https://github.com/wallabag/wallabag
#   - Docs:           https://doc.wallabag.org/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/wallabag/wallabag
    tag: 2.6.14
    pullPolicy: Always
#   restartPolicy:
command: {}
args: {}
ports:
    - containerPort: 80
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:OTI7L5YtxD8=,iv:3bFw98E2xxpjgsj1VrIeuRB2LItb33AB/71r2Sqa1vU=,tag:6GIOSQSdMy3BQ6E3Wz9xsQ==,type:str]
        SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:dg8EKcEH4H9ffbhPUJ0tvOrB+Qg=,iv:Uxk/xRpOB8PY2aOJVrKhq/Qi7GOqs7r5KwfTUepSR4Y=,tag:T6RqeHzomF5zehkfc39hDw==,type:str]
        SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:bBw1gaqBzCI=,iv:nh0UeS1Arty9F5w/uJ2ZTQ8TotwYP6Id0gcYSiKL47A=,tag:PgGt+u/bXgfcHBbxxasdpw==,type:str]
configmap:
    mountEnv: true
    data:
        SYMFONY__ENV__DOMAIN_NAME: https://wallabag.{{ .Values.domain }}
        # SYMFONY__ENV__DOMAIN_NAME: http://localhost
        SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
        SYMFONY__ENV__DATABASE_HOST: mariadb.databases
        SYMFONY__ENV__DATABASE_PORT: "3306"
        SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
volumeMounts:
    - mountPath: /var/www/wallabag/data
      subPath: data
      name: data
    - mountPath: /var/www/wallabag/web/assets/images
      subPath: images
      name: data
volumes:
    - name: data
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-replicated
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: null
    # nginx.ingress.kubernetes.io/client-max-body-size: "0"
    # nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: wallabag-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: wallabag.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
sops:
    lastmodified: "2026-04-13T20:28:43Z"
    mac: ENC[AES256_GCM,data:zNAyZJu5RRfeEM4Cxp+aGGZ6kOjFsT1QL2Vy/tfVnbR3DyV2zCZx3YOUDXO3NZm50dW4qHj1blwVjPXn5GeKdx1FZVLurmEwYidbpv2dO0kDxXgUzUm89R1w+hJynnrWwvGFn6mWsKxXmzuj86ZtVk+dWwc/mrQvStEdzUBqcxg=,iv:ZgRSydeN8IPYuivNLk5DjGkho3nO2uESSgOVOCqkdbQ=,tag:Q+yuAcl8HPZVuFcaRpVg8A==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+JwuMw7aiA05e/iFIwGt0RbjNLT+nehP6UIMsZlr7l+5b
            xiZxXwpli15cTCpUdhNgFffceQ7EyjG4Kr5wUmT4L0Y+Rgl7XN6elix7SGGJgbz5
            wQ7x7ENvG3+614yvd1QD0/jQptBFj2gKjUpsVRcGEtbCagvd7zem/rDvJYCr9gIK
            O62YUtXLFiZMQaTuBrFakoUgBRIjCj4GG6pwjotOuFNrinRZ9GpaJYBp8zGKOX3L
            mlAafGAXKyelM+0JRoiGU6WrX4IbfebibB7T04BqUdGidhSJIVf8/fSUZhECK9p+
            TPEOqEcPW9BgCecdCZA3KQHwh1O1Mdn4ksWA1RsYuMwcL1Ilf2Y9306dDa7U16MG
            jL98D4aXtdw/Pfo3BCH+xOkPU2PsOQPwsnR1sGFkwIm7LP73kmfRWZTz3+Z/KYt9
            eLdR2kD+oAeb123ADS5fTNAbuqefTiNnx3ZZMPjcUtzU6t0Azf2Z4TQCUJDocURL
            7gxvUR7xYqfUmb/yguiil/0iNdYgwhlxH8d3IIivAxBabFgnlx996v23bbuRyeX3
            p9fd/aH8IRpRPMJdzauhisciaURsFTStWj69Vz5rqHqYOS+mE6xp3CHiN+R2AHpy
            ABAPkFlGv+q47zCVOzbfQwsRWKrhfczGa++e1z7UokYl3jHXcngYJyE0mAmdNf3U
            aAEJAhDlfvCv8zAJ07CRzjhrWkhe/CrZHNCXQa2lwaUbnRUfg0ctko9y2ORSH8Gd
            StlHnVes6UOcH6pGBq/gF2yq9uQAbcJyQAAm1tCZYJ4yR4vgC2MgFkB26YVDUjXh
            r11th5Hhv57g
            =T9k/
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
