# Default values for external-service.

# Labels applied to all templates
labels:
  host: hoarder

# External server configuration
server:
  ip: "{{ .Values.ips_tailscale.hoarder }}"
  port: 8083

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_busy_buffers_size 256k;
  tls:
  - secretName: calibre-cert
  hosts:
    - host: calibre.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
