DOMAIN: ENC[AES256_GCM,data:PPKf9XL9gfLnlu8GHQ==,iv:OOAY2HgjyMygPXWc7sZW4NooApDq+cLsUczAaibuvVc=,tag:/MmCLmj5c2iYYAtYs6MBog==,type:str]
VNC_PASSWORD: ENC[AES256_GCM,data:W16yGOuInvfhig6ljxnIll8NQQQ=,iv:YQnTsXGksjwXD3hqAfeWb+ll1i71XYv2na2VenOe5pY=,tag:x3ThoTbiye4ZbKEJzSGAvQ==,type:str]
sops:
    lastmodified: "2026-08-22T20:51:34Z"
    mac: ENC[AES256_GCM,data:vlaUD+4hvcCARdXcVdiWIJLeQtSSGokrM2aNq/Djl+3MqqM5hGpyy7OwFLoWLXeJxoqvlQEiPqttpHbtLIUZvAIcV31dx75SKGvhwDMQmTsCRqKeAxuMmDWaywbzT1SFjkBTsXq+BYaoZeqcqaYZ/QXppujLwTw1kSxyCFFmcRY=,iv:j8IKhhDrFB/weiNCD0RcaA/jnpyX5+YgxZPCWXLQQ6E=,tag:6qst6v6xHx2lCEBiKkSFmw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-22T20:51:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/9G8S2DN8WdNIeGX/GSXUj3q/yRp9ANnnESqrE7Rng8b09
            UXGrU3+4K6c9KjToq4jmGFR74jvUwkY9paasx2tBRgTpTUy1KhI0OoW1ny6Qvelb
            CSbBpLFKDAAUB+qRvyb3AAbveibv/5LUa7HQcF65aZxWhHJyOvNJEhMoFDI0632y
            uO9Z1F7No1qmUHJB1KhhcQbB5efPodEa495hGCgDgqsMweMHUvsSUoFv+SLuNRRV
            CIncPt8FKnuNiRJ28gqIT6e/FLRd/w8xMXqm5JycdZ0BiT8RA68M5GBSYa7nj3GK
            IQEaU9wmqn4xJeMC6UXJq4cnO4ByRn80LPesrfkHf6qeqPAYqHDVULlyarXbp1pg
            015xN/QPt1MX/Tk099ixpyWlwRRlQzgE04ppuehMVdsLoubm/swwvzbK4VEfNQc7
            LBBJeMyJcUwQdoEWSrJT0zKtRT50L/bBj6G528nEnzMgZAWj3EwnV/BpH3I3ftDE
            E0JIZydbMCELd0L1zcNsEugoBdqsd7DHwJdPxxwTeilIPnWAtu6U+gC1y8rmhJgD
            mUIibXWBziscTX15YKBIcVagCeyZRvZr0tLGdeUIhKWqSxhhME7W1LETbbgBVgeW
            cSuwQxiwmNJcT81ABv3Ec0MbatK17CvrS6Dg34ZH1QcYlUvfLhd8XvXERBXLuLnU
            aAEJAhAQMi2CGu892b5LpLjQxD6xHjey927mIUyvDQND6+e/qX1wUzUbn2sIpnZQ
            oYg4jWgrFpEasOi/5oKRGSGIDdTqY4K76alFmx7LqRUCQe6lCu5LlRjgv8aHcucI
            VD9Fchy+Cq8W
            =4HnA
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
