DOMAIN: ENC[AES256_GCM,data:OJ5AE08C7uMng/F+YQ==,iv:PSFOILGijy06tl5NS9UnDSApSOce5Gw1q3iTH2SsFqQ=,tag:DywUvjOJOHg/xNlwpTpahQ==,type:str]
sops:
    lastmodified: "2026-08-20T13:13:34Z"
    mac: ENC[AES256_GCM,data:/dpwMNOXO7TyMfRBCydElu8x6QwKIsAHrBPCoYNl+8JwLXyN/2kicYX3iHgvqwCHtV2s6ddInwAj4r3gP0UuhyLrdms2P5gBr6J/RXrkIG6dUqEdONv1IZdl+WGTJ5f4LgTcZaSi+wvY4f0Tkd5e/1x5j5GkzpD3lxd/40jBfBk=,iv:uVho+muBVtwqYPTNfqwnBcvrZYv82R/2MJWSGYR1yLw=,tag:YMT4yQZEGKyuFAEOBtc/9Q==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/9EK5+nnNH7y6Au+/UvcEg7SNJNc4Q5tDoUTjUs7gbzPxR
            PaLETQbYqzCVsqoD0zz6L7hPasfEZ0rguMFixZ+ryONWMnsVM4+l55rfGpg0bmzN
            oZYC1SQ+Dhcox4xqSN16f81XkLIyHnqLCwBnoIaQ7ZVfp16vxtLMeQfn3ksTMqQc
            7nCeO4h/1J4keBGdINS7FiRPaqtaASmlKdNyLBtpe81yn0jz2j4A0MMy+sMy/sy3
            fOYdEhSVp/njLnnazGYQlrHUY8RDLY+ZYa1KHIL3qM+aknHkemKVNfoTHcAZ1Fsj
            jrfM9hRrlN5EpGT0TiIWeKo9JBhUzn12teSaJwJTBBWvPQTxOQ5/+ndjvzHe7Lnp
            pi6yWPul7BSd4GDSufIcewZes85XjMOIoj5XBS9PX3dYsJhOlDBN7uTxDKO1DaKm
            E9Ob+m+sZLbQ5iXIOTWEO+d9IbjsePXUrm2S3b1KLZg9+Fej0Z+dSr8yC+iCviN+
            DY7j5USu2u5DvJP8Xs9xgmPa8bDM7+GrAY55PZdKaYiyu76lWMGrUC0rZfHZfBpB
            vvM+WSepILEjlWH56XDUDDpf0RSXzE+Ub019YRa/TY8UESl3kxFxs4kuyvV7WvmX
            s8M8HnY4oHlmoa/K/15cUDnn37wvTU9QWLHnm+f2Z8wzExCoTHZQW0GDXgpYNfLU
            ZgEJAhCbYS8rwIP4vQONiV9O044aUu16BAeu3/QPv+fRtnUMDcoT7/5oEpzK1Bik
            gHZYVK4e9ZObBaD4CXWbXulGR081C4GCS4Nucg64XV0FyZWwGtLd1WNfzeHTqTk0
            uR+VimzILQ==
            =5Isf
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
