DOMAIN: ENC[AES256_GCM,data:HkWtqnpYmtWf13yS3w==,iv:J+Pud4hhk8jyYe8Gng5nZ7nPDCEKq3GQzO3eCl60FO8=,tag:HgIVX0kwky3kHDskp/pSMA==,type:str]
sops:
    lastmodified: "2026-08-20T13:13:34Z"
    mac: ENC[AES256_GCM,data:OQX6141PEfS6FSoRYbC1vbNMpcWDMntL0r4q36aeTkqwH7znZgIGL7pDgFPknIkq97fAs0P9lmuxcAqHyPdMQ5Mx3NrOrdKA7yvh7IKwAxP4bem9YLUdRtiZSTZJyhR0jDWSAp0ziKVE5ndulDNWgldSTI5NfJ6Sm24n2pdUXrA=,iv:6IRUB5RmI5nNLu/W6H4WKtBGc1Yjt552Kf3wTKm4GTc=,tag:h8eSakcqoNNKuBpsmugsCQ==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAlPL/T5Yr2NLVIJx6TCoHzuhhHArA742HjqCPTNWWO0GS
            odMiU+lOQxUC4Fv4O+/IkqnFZHE8XHoBOUP57jUFk0F7wpYYxLYd9jVkNo904nXW
            KdRk07fmE4EbictuEQF0u53At3ZT8L2UZEOUMttzvoRL3TLkJENOYOs4o85Voo8P
            AZ4PaEdhA2oOqKYuLgPXun3Ns5T4pfD40xea3c5REhpMgaj9+bf8kDK8zu9M11iU
            bOeM6vDpEZCOHYmKs+5LCz7C0nObHrzCYLF61pxa2fYGOOjPQGV5vs2TfSQntMr8
            GNJYWr5bWRv1vttmuOoAHA7d0LAEDxPJehiBX6RfcvVCRgyfO19baWPh5+e/GVPe
            RzShmHTYlHUagNhaZXwDeR4dEF+BFCbiCAP6pt0Dyuu7aynMHGaaIHG5dXqOpgwN
            3S15sOeEQwpoZm7cHF0A5SZCWqMXq1prisrukookHoEHdUyvVrjy9wqSrh1ydKD5
            8YWKhMq2hj1vYtF/O/iikTHhTDvTqoS2vfmSt1W68U1ksI5GELQ9hLRg45tuTE43
            emeYMSmaFDPQSEJgiuDGi249B9j7VyokiwgBKLvmtc/PI0TmA9fTiRf0/dtAlWfE
            YQLChp03W2ax8MvvbVpZ9SvI5AJba0Rp021qHr6TnYsxpzGxSd5R+os4aOznP1rU
            aAEJAhAQYWcLXD/iClTZsEK6JveSj4rWwiqoL+5LvlIlr2H0hsLWm2rb173/XJO+
            hk7cz30ukHD2T2JG1Q3hhYRYPVrIWeObO1t03xgigmQmQuP+QfLZMEdWQHwJleDU
            i7saf8dWG/FH
            =D6NW
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
