# --------------------
# Govee2MQTT
#   - Repo:           https://github.com/wez/govee2mqtt
#   - Docs:           https://github.com/wez/govee2mqtt
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
labels: {}
# label_1: abc
# label_2: def
replicas: 1
image:
    repository: ghcr.io/wez/govee2mqtt
    tag: 2026.03.25-ab9deb66
hostNetwork: true
secret:
    mountEnv: true
    stringData:
        GOVEE_API_KEY: ENC[AES256_GCM,data:xqC+F16/88m8KzuW0Uz3LcHqTg16X7C+2nVPcZHFgXwONeQY,iv:IC0BZhj4TqLgH7ct7KfSi8ayQSiVDaoZntDoH3WlVDg=,tag:CGqN14c3v/7Cio4GhR29Jw==,type:str]
        GOVEE_PASSWORD: ENC[AES256_GCM,data:BkmazpBMmDVO4RitRR83jfWZrFc=,iv:4ydxTwFhPiPY2PADmfiR3PtbIxYN2zwOkn1yY8GPmSY=,tag:K63ARJb9NdxAvsm3S8s8vw==,type:str]
        GOVEE_EMAIL: ENC[AES256_GCM,data:9nYCzpc9qOfZeLvWbZgJp5Zrqg0vKVTpV3ZM,iv:5m55kNnUQlP+91pmx6XW0xoFwPOdo9zGd9vaDVBfass=,tag:oj1J5NPSxuTEGEKMBJX/og==,type:str]
        GOVEE_MQTT_USER: ENC[AES256_GCM,data:HymY7H96FRan,iv:mybR5uWM1a1WxA57fEGduzBVF6ZdVCGuErrZxnGNl7k=,tag:HK5KHoqix0Atc3GV5lHbaQ==,type:str]
        GOVEE_MQTT_PASSWORD: ENC[AES256_GCM,data:pjFy8n2Hr1y1qNrD,iv:r6/wcUKQH+klM20ikO65AlMHahc0OZz7jvFRm9LIaTU=,tag:G4QmHldmwW59oGTZ4NrOSw==,type:str]
configmap:
    mountEnv: true
    data:
        GOVEE_MQTT_HOST: mqtt.local.{{ .Values.domain }}
        GOVEE_MQTT_PORT: 1883
        # Specify the temperature scale to use, either C for Celsius
        # or F for Farenheit
        GOVEE_TEMPERATURE_SCALE: C
        # Always use colorized output
        RUST_LOG_STYLE: always
        # If you are asked to set the debug level, uncomment the next line
        #RUST_LOG: govee=trace
nodeSelector:
    kubernetes.io/hostname: k3s-m1
sops:
    lastmodified: "2026-04-18T13:23:08Z"
    mac: ENC[AES256_GCM,data:LLFcdJXTklhCdMA3Er9yru2s3hhNggeiu6oLlSITbtglv33eRh5TlIvlBbnnXg10hsMsj/R5gxD7v+xb7BisakRzadAFDKp7LHCj+f0TFWMAxPKu7h+H3RM/boKAfMZnhx3skuF9xLVqL03sxKTNHRthkoL1Wh3S72aX8RMmqZI=,iv:rO+p2F0XO/3yGCH85cm/k1A46wO6Mrc0wZY7M16J1dM=,tag:PGx0jURbjLwoyXRii9fpTA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAArwPEdX+r92wXIdiRkS+OzCYreEUN1cBIA72Tbzu0obAI
            Dt7Ehr1Lw1uKDTRMSYTnvXVG58YINeIJRsip2tdmHACsDJCp53O6ArxggFndnSlU
            0Ywl/pfajjDMQQE7or1myTu6uV1ieWi8MBFX5MALzGguHuA4JQfuu5mikWgIRg0c
            6DC9F3SbcBSHoeQe5Giok2l7UQt/zbMAzxQzrYIAS4fj1z36m11wDL9DB9ReLPHQ
            6Q9bc8H2yGuWgucKU6rqPVVChF6b6Wp1wK63YVIv0AyUhMFLf+K2fZL45Fg6H+0y
            5MkKRri3Rjz19xSshcfH7Jw7GuXqbhnZfAAmtUA6+iAkwMtL1PPjngFACEeYLzhW
            3qkCBHY04+nSdcNIYiX07/QyA67iv4r722W8e8+i1NHg+pdfUZIgdVxsGCy7y8DV
            wfDlqLTjzPHDsvG/UeRif6GBqH0ssiiaYusu9Do+KIwaKWXH1UBQRbC9mf98sRnY
            fo9XMjWMKLj9kg18MFYcmt75rV8r9mif1ESPHiafFHYwMUYfFEI7/mTyhyTnIebn
            S9fGeejOCZUjcP3Eq9drHolNi4mmAhcQlgjkF/rcl6RnNOqrTMl5flcjiVbKXXiE
            +Vs2Q/OOUEBNvi1PhOqp1xn0s1YAYr7qNif3uMEaxA6x2l4XR0ate+gVJfQ4mJLU
            aAEJAhAtVbPkMEhV0GI1unMtffUBQ0QCNQQ9Y0q7A3dpymfxlW5OFug/2rfmhSI6
            5QG378X08yAL4vGoEJDTvgw8n2hFnKqdRWfryd7PgXusk9BmGGQzOfvlAQtNXRFK
            zoYAZgRhwo8h
            =JZUf
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
