---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.goauthentik.io
      # targetRevision: '2025.8.4'
      chart: authentik
      helm:
        valueFiles:
        # Was causing issues decrypting second file
        # - $values/kubernetes/apps/values.sops.yaml
        - $values/kubernetes/apps/ingress/authentik/values.sops.yaml
    - repoURL: git@github.com:afonsoc12/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: ingress
