---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: '>=4 <5'
      chart: ingress-nginx
      helm:
        valueFiles:
        # Was causing issues decrypting second file
        # - $values/kubernetes/apps/values.sops.yaml
        - $values/kubernetes/apps/ingress/ingress-nginx/values.sops.yaml
    - repoURL: git@github.com:afonsoc12/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: ingress
