# --------------------
# PostgreSQL
#   - Repo:           https://github.com/postgres/postgres
#   - Docs:           https://www.postgresql.org/docs/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/database-svc/values.yaml
# --------------------
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/postgres
    tag: 15.170
#   pullPolicy: Always
command: {}
args: {}
ports:
    - containerPort: 5432
      name: postgres
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: ENC[AES256_GCM,data:cNGJoiBoZhASWGI=,iv:v2IA2kukdZ61k6UGXPK0IiRfwDvvW+LNbuTB6khf6xQ=,tag:ESwuR6AtbpIyR54Pie9b8A==,type:str]
    annotations:
        metallb.universe.tf/allow-shared-ip: db-svc
secret:
    stringData:
        PGPASSWORD: ENC[AES256_GCM,data:GlJvzCREQu9eNmk4TF4x42x3KEw=,iv:/Xeew83BQfqWByRfFXoBoLT4CtAVptSHN2R1HynJG4M=,tag:pFYkZkH65iLCkRCFLi9J4A==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:fSJv4FXZ7rF1tLoSH/WxRDbFSRw=,iv:4PBjgwUhFwTjCevhM9W+Xy5Urm4SlmOutE1JM1s9Z10=,tag:gpvmBhQnCgcaz26M/OROXA==,type:str]
configmap: {}
# config_1: abc
# config_2: def
volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
volumeClaimTemplates:
    - name: data
      accessModes:
        - ReadWriteOnce
      storageClass: longhorn-persistent
      storage: 5Gi
livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    exec:
        command:
            - /bin/bash
            - -ec
            - pg_isready -U postgres
readinessProbe:
    initialDelaySeconds: 5
    exec:
        command:
            - /bin/bash
            - -ec
            - pg_isready -U postgres
resources:
    limits:
        cpu: 1
        memory: 512Mi
    requests:
        cpu: 50m
        memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
backup:
    enabled: true
    schedule: 0 3 * * *
    rootPasswordKey: POSTGRES_PASSWORD
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    config:
        MODE: MANUAL
        MANUAL_RUN_FOREVER: "FALSE"
        CONTAINER_ENABLE_SCHEDULING: "FALSE"
        CONTAINER_ENABLE_MONITORING: "FALSE"
        DB_TYPE: postgres
        DB_HOST: postgres
        DB_NAME: ALL
        DB_NAME_EXCLUDE: postgres,template0,template1
        DB_USER: postgres
        DB_DUMP_FREQ: "1440"
        # 3 months
        DB_CLEANUP_TIME: "129600"
        CHECKSUM: SHA1
        COMPRESSION: GZ
        GZ_RSYNCABLE: "TRUE"
sops:
    lastmodified: "2026-04-13T20:28:41Z"
    mac: ENC[AES256_GCM,data:vQnQ1aysK6NTGSNYMNl4FQnpSfsAPjjYeQzFwWVC+3W0kfJ6miAEZWcHNI866/epCFamU7WicxzwxAo42vY40YAEwnMWQpUIR//11ClL9GnV8Epj2gorYghzueyIukZkoPPEz3n/apBWHHpRMV64dwdsjuXlBd2kqGzJWs8Skpg=,iv:zfdjqsEnq7qwNHpiV9zL/1nqD/LYUevL/b/VT2R+Nnc=,tag:nG8i+N9sUymaE8CEkVkmLA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//alEQ7bnZ2uMzZ47rqd+kEDwr5JZ7uneSHLu7CTLMovlE
            EAx4tDv/Li/XzMPuUbW0LOdQWyMqAHdKOav3SNCv0wBeEoIULz0O2RZ73yX0Z+Xe
            29F8pXQwnBMC7iPayLZ91UmsYd5idPXCjptqqoht//Ix+cBtuwu7yA67NoU+ZrvS
            B3HQyahLNGDHRpDMywRfq0KLH3/bCl1y7wYLTLpgWxdlMsk/vBRHkhHgpbxar3NU
            Tk44aot0z3T3EA+1Xk0AIDzF+7K1PL659JQADGMuP8BMlXnssDQwwmQdBDKmogL/
            vesMwnfXAJ65TM9Ttew8Q/9FEJhOCUGCoSawIVBjhO+XXPoibmgUmGcqndu0a+ci
            +9LQx6bAT3nIdG0iRxIIF8X6zFQ1hyjFQvsKfi4gsNehP0GfFrjdUZs/S97Hg3zy
            fEodNZkMUXlc7gKQU587W/JWSLSnxgdE//m3MybaQ8h0KfD9ZQgVlIEqwEpgEKaY
            iJ2J8TlIDm/XNcH8sDMbJtDSkT/Gn83IVCzNQDDUZYtd6xKT7t5IwuF5gISqfCIA
            nyV92h1/piFAys9nFbcZYfYMbQHjwMBHokTJ6YSoE8ib3GoheL3P5cUXg55aWH2K
            528G8YNV1biPB1xrovZtiD30yV5cdsDmVkzFR/wjJ/tkfzRWsru4d70hPG3BiVDU
            aAEJAhCaY25w5E7gqCxRcxA0mOf8JPJBUFsrKPk6cFP8vYrXgR5uKKbzJAWcXGNT
            FyHFMOtZBrUu3uQl0kpEuiWDLqts573myPKxHESlGwEHDd+wKymt1ea19MYzP7a/
            ujQtQx9pkiBT
            =8HEs
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
