---
# --------------------
# kopia
#   - Project: https://github.com/kopia/kopia/
# --------------------
services:
  kopia:
    image: ghcr.io/afonsoc12/kopia-temp:latest@sha256:c458d695ab35546308aaea93df2c5f4090796991ead5b89549988b0e318565f5
    container_name: kopia
    restart: "no"
    network_mode: bridge
    user: "0"
    hostname: hoarder
    ports:
      - "51515:51515/tcp"
    environment:
      KOPIA_PASSWORD: "${KOPIA_PASSWORD}"
      TZ: "Europe/London"
    volumes:
      - "/mnt/user/appdata/kopia/config/:/app/config"
      - "/mnt/user/appdata/kopia/cache/:/app/cache"
      - "/mnt/user/appdata/kopia/logs/:/app/logs"
      - "/mnt/user/media/kopia:/app/data"
      - "/mnt:/mnt"
