#ENC[AES256_GCM,data:QphQEQEZwdGgYDjxSYFU2iwdMKUDcaPPlOWHRhx5qDgK48zQHZElCMsa6ZcEm/+kree8c8c+6mK6wIr0IQ62QM+oeb8+mdXe,iv:ukFynStvYWkq51eC7zLxwCO71INU4tQuSkVySgNQu+w=,tag:cMj9t41ZBYcndthpO3VLDg==,type:comment]
KOPIA_PASSWORD: ENC[AES256_GCM,data:3oAO5YhSwgk5CEc5HbC027ieCIoT9VBXng==,iv:bhkBSPRwIP4X2glg5gh2IrZBLJ3XxHVzuNQ/KyR1FE4=,tag:EZa90RfcQrUeDoth3lUBBw==,type:str]
DOMAIN: ENC[AES256_GCM,data:tkshpKnzocTY1nBe9Q==,iv:ZSdorbqbAv7MN2bQc8d41uQKxBl2S0NIvnpF76UKVeM=,tag:fvmNv35hcZyJb3xBQdSc6g==,type:str]
sops:
    lastmodified: "2026-08-20T13:13:34Z"
    mac: ENC[AES256_GCM,data:rLkRf0ngcwaokhRyNKQmNs3XM+bGvAM52zTiNKzQDR2vyF7QvW6ryPve+s/Ejjsehjs6350RPPtA0SM9DXmYvjyi8A9EC0NQF3dep/2poVpgps89guf7bj36WQT4fB2Tbs45IVWV/wjLzpxHmBN7MMCGfNUOtdC489qw64HwILY=,iv:ZKGpw7ZSCKXv7dKtlgxNktp0LB3w2KHeCc8NGbfxANI=,tag:+lhAIXEMwg20IcPLTTSkXA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAgXIz7dmxx2GvbvHIP81uvB8fGCiOXAzBFmoFJP4xuVD2
            7CHDkjEMQapRXN4Z7OZ0ahQSae9l34pC+gAqAwxPwfirdzfcmLLbicPnKH71dQNQ
            HO9ZOqHleKpN9HFYKH1G090D4X3Tbei82MoBA+StP758jLokLMe7R+/LcDg4BxlR
            J5PoIx7bOTB5poF5usSy27WEFxENQKpW3gxfqJ/Xizdd4AFVSoUkgviK80MHM5OF
            syfHEzGQhXOs5vktT8UzIUdq5xq30Cfcu/4xPjWFkvI7rvIdeZL7tkuuloIJ2Csz
            xFfMqeZHJxe85AbdmDpYiGwSHVQ7pPSdhl1L/5PN4bqNw0yGJ9ksOsrjwkCFfGyq
            g7yGjRe94V5REl8BG6SWHhK6Fd1+ISbVQbdqQScKYuIh9yEiNFpsvxYSIQ1/Hm+a
            gY1GoF1L9XKamsuiWa+/Ed3BiDeriHB7eueNsGD7NxJpQ412VNFPGMINkzQ5S8Xc
            3ya9/q8HXLFQyZtZ8JEdwMkuGfssHA9X5iVMSROAk/k5m0LDzvrpII85h4eAOaAr
            lmQybS/YK2vl//bKDeOHMkffsm32lJ26ZsNOZV781TQn6Zjfxc/xGrPfpZ5MFXfo
            YtT43uIN7oGU1vuul6UrpcgEV2wz+gbg7Su5o4yYSOAvdTzSM7V2PWShpxiXfrrU
            aAEJAhBQr8RucmQbx667yN+NH7wYm4Jswmdh55zBqluenfNRIlTWrtwJ+Agz2HGt
            yJFb58+fHC7T0Ot9lw63NgjMyyp0mEVKQbQLDlRg0NXQhZg3o4SwGIuKr/9np5HP
            hMfvzfrVaAxy
            =28ad
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
