controller:
    # Must run at least one copy on node k3s-m1 because there is no horizontal distribution
    # https://metallb.universe.tf/usage/#local-traffic-policy
    kind: DaemonSet
    service:
        externalTrafficPolicy: Local
        loadBalancerIP: ENC[AES256_GCM,data:F53YVQFAseHyQgc=,iv:AgShoZwEcm5vmEuf2fJaRizQGRKnVWNQajDGP+cCfDk=,tag:IcsGnoOXGfavGxxjcDh2vg==,type:str]
    allowSnippetAnnotations: true
    config:
        enable-real-ip: true
        use-forwarded-headers: true
        server-snippet: |
            # Drop requests where Host header doesn't match TLS SNI
            if ($host != $ssl_server_name) {
                return 444;
            }
sops:
    lastmodified: "2026-04-13T20:28:44Z"
    mac: ENC[AES256_GCM,data:cdhMhcDikO8yUAlOlHeS7nbo7ZjTefk2L+6QSV7Fuq9h6g8PWshFuhZO1VW1l44E04xV77PQLmfggIKlV5MJveE3fEcEuWbudwiQAZ+zeWaXUswTriEpd5gZfr9+Q0qITxufyHAYy9Et3ABWLSfVTX74dDP+keAXFjbhYQcZo8c=,iv:2pq6jQGqglsqJkacx9KI6mFlJgFR2tz72vmozXUX4dg=,tag:fZyyJ+K++jnTQ/BOG0fGlA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAl6x3gTi/JY5+wv3qTkTj5HFveohC48br/7SCaFMVWHrg
            CKUXuv0xgtbCGgD0fKDkn8S7opLIkC40ig0o38bK64Tx0/lYY+aLXQKDri2coNBf
            islLHNFu5shfQK+2qspJUSWfJ8gEsDejzVNyniU6eGpmC3LbTxzA+l+M9bVXJCi7
            CtTcguZbyaLSmXq6oKzQFjDojajxSm2LCXh0YNWs7IqVBl7Udf+s58NoY8YTuVRe
            ixH1I2N1Z/g3MSCGQJlJDSvO2ZmVGrfX74kedo5JgAIXhLMc7QQwSrdE6LEnMs91
            +mAQw33p067585qTC4rCL+l+zAypIwaiJ/Z9cIqUjY8KFZg1zXZ5MzfE4O/fgCKo
            uO4ltqzd/4vtwx7Np+mDlinYaJ7saYZxGxeJ8gsOPkrVvSD0dc7Mf52qn48NELro
            95s7AAFMof06lLiiaaC+hLl6AOmdlzRWJOpXZ/Mki/XdQtKiMRZk1T07/dhADKnr
            Se79np4bZ5fpFsmAGhk4Kr5YjgC30nCItSYtAUz/xHVItWkx2P5lk52r79/VOr77
            KtLSzt20YDpJN9sWoFLAqTlZiRFHtyaardm9urI5T0U2/wQDgqzxlb8ggzAlYU7P
            7tjGGSSlvrSZ6wrNMdSxvDKlGzffVSZcyptVnxoXJf9RL2YpegnKjd/Rwltmr3rU
            ZgEJAhAjDZPnWsyfDkxZ/FS2xKajte8cYBTwYH8utY/LnXftUKGK7mYZdQ0IVKAJ
            rT7LOwCaL6Uy0C7xKcOmW5E7nTIiKX1Ntsax4wTYeURR8sSyYX3aR58Ju2fTLxZA
            JSV5y+hibg==
            =kD2U
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
