controller:
    # Must run at least one copy on node k3s-m1 because there is no horizontal distribution
    # https://metallb.universe.tf/usage/#local-traffic-policy
    kind: DaemonSet
    service:
        externalTrafficPolicy: Local
        loadBalancerIP: ENC[AES256_GCM,data:fp2xrTbaCWIIns4=,iv:DbmDPdPhqi19l7c+DCS9DP/5wYHE8u7vyvZHbHDpJjc=,tag:h+dNCl0e+lX6ypsmJaxhkg==,type:str]
    allowSnippetAnnotations: true
    config:
        enable-real-ip: true
        use-forwarded-headers: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-26T13:04:49Z"
    mac: ENC[AES256_GCM,data:wiUQMzSZXsjZZlyly5nZCssH8OQJfbK65Tw1mhuNPiQva5phudOj0Kbzlgam+Ny9N+YKp/U+468gTAyw65ccVs6f3AdjKudw8ZlRC8KL9R2kBQVXYDZpbG37t9Ot/KsXXsNxeDP6npwUCGV/hsH0F4uOjTGVKPdPC3Vy/d3WYNc=,iv:5Gw35lBF3YJw7hVu0VxgCPsbjICBybPsGN8ceKHTyto=,tag:Q1QVK4C3ivBdeN+2/DIZaQ==,type:str]
    pgp:
        - created_at: "2024-07-20T14:15:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/8DFKctOMu1LMSwQWs1KJgOAl3CIP4AhWQpWL0tA0dQFlT
            LmcBo7fa+sbKNUeO6uzQcEq2v/5939S9N3DK+gsiuheodRSbeH59wghVTdhljiPv
            097Ffti0kbhMpJnB+bOcF2hO38xVtYKRIJ/W+AKImTMzexw3uDO+yHUtTXebEBMK
            ExVEmnqEDSMZvhTghVzDUqxDTp4cPW828530yHJtJp7hx8MpjplUlb/9Jj8k2lD3
            dMMRSmPbz0dvnVOx0rElvP8ypuhHP7K8lT5mg69G8sH2j5DrSHTzlKk8h+EEEhb1
            S4rG73bXYdeLX7rx7MCLyjO/2W93aK6xTMVxl8foITlrjCKnFc0P5z5Tm3rYrcw6
            SY0cHTXVm792R2+K38fCLFO3vtk+eRUweLv1ORhAG9E6T2ZBPdXFc/KSTv1ObWJU
            a2xh+YGfq0F1sHf7fKZPPw1H+SZhcjJrGTDVLdqO5zhO76nw5Ik9roIHZ1nZSXI+
            KQIRwV+MKvdFK5dx5CKgWBKtlQpqWjql76Upz4Uq1HiM95SC8eZwX13WZDZ02bCR
            7EwOu4bDRUstfCF9In/q2/9rbxVFJ2yMSzx1PeyCkv74JcRebI0mVBFCAIdYyzq/
            ZV0MACnKcbk25dYocs7YoCpABwUK3St7+x2FZ3XyfNaf6+rAYtEP5ntpid2h463U
            aAEJAhAR2ZihP04PI/rTgME7QIOsG9Miq4pV1Q+N6MTUto0uefqsznC24lq3u7ms
            JtQJc/ZEemUBrFwNcy/XTZs9vwS6E44eNiPnYclB+KISwKelGVHLSrvLSR2aKwY8
            jjblsvTG8Yh5
            =KjyX
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    version: 3.9.4
