# --------------------
# LLDAP
#   - Repo:           https://github.com/lldap/lldap
#   - Docs:           https://github.com/lldap/lldap
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
labels: {}
# label_1: abc
# label_2: def
replicas: 1
image:
    repository: docker.io/nitnelave/lldap
    tag: v0.6.3
ports:
    - containerPort: 17170
      name: web
      service: true
    - containerPort: 3890
      name: ldap
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
    # port: 80
secret:
    mountEnv: true
    stringData:
        LLDAP_JWT_SECRET: ENC[AES256_GCM,data:jcK3i1MwyB9F5yED3QYVvBc/UCfoOyl/QrEAeh5xLmi+Q0ooEQyZIwEU1cJRD+Nfv3DRhLjAn16QDHgvMLyTFQ==,iv:VhPI6bbDY9lzdRTazTU+z0RQiOhtahb4copyEjBhR5Y=,tag:r9hVcR/0PdQ8BPwnmJN47Q==,type:str]
        LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:fWM2igKaNKv5JbA4wC8Y60l/gA==,iv:egEeaVWUSV5qs8Zj7oCQL4t6nquerbG/mkGenCrUNTI=,tag:e0EExfsAhZu+KLjXkwa4Gw==,type:str]
        LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:m7IlRyS+8nSycthoZjP8AAwVm/0=,iv:N1BFmWJCuyTzqHxHUvLmq/xc107SwZH1X28mjIbsMjg=,tag:9Ml2SALZnC4Q6xyk7w8uMw==,type:str]
volumeMounts:
    - name: data
      mountPath: /data
volumes:
    - name: data
      mountPvc: true
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 250Mi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: {}
    # nginx.ingress.kubernetes.io/client-max-body-size: "0"
    # nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: local-wildcard-cert
    hosts:
        - host: ldap.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
# livenessProbe:
#   httpGet:
#     path: /verify
#     port: 9091
#   initialDelaySeconds: 5
#   periodSeconds: 10
# readinessProbe:
#   httpGet:
#     path: /verify
#     port: 9091
#   initialDelaySeconds: 5
#   periodSeconds: 10
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 20m
#     memory: 64Mi
sops:
    lastmodified: "2026-04-13T20:28:44Z"
    mac: ENC[AES256_GCM,data:lCNMi8ysudMVa1G6BO9nQ6iakLUeoVqwuNphVm8KEmfmWyeF3WYe0NlS9AS7Yho7aXUMf6vu4rSXJZEheX0bAkaFmMoTS/jDv0o+Utl8C3j2tUmtgF6YJzDAxPnnWj1rK66P7/5NqVRJLJA+rXATGJzqflFa9RVcGgtlQagLs8I=,iv:8S7xTplXLVDBBTOVBlIHdxtE5DILCAFMQaJKaHtqijM=,tag:oqRpCPl8r0YsEKeozvdLaQ==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//Xq97lEJ1yUgZRZDhtNsEfB7nbqdQ9UdPm94DpDUzyPWM
            +G94FWP22E2DCOAgvwYk8G2s5++hps3HDX2RiOGKtf3z3iTZB2hx+ysnVNOpfkLa
            vrx1jmN6IUYMS10stBf+7eg+cWdRFawYGuoiKJZ+3lJCKly+E8J/l3flE2Bme7dq
            8T+Q1axwzTkmIt4X9QXF4Ak5D34Wi9eTBFmkyy6p21UxXnsXtCIdG6OpGfFBDyv1
            aXZVuvtZgBxxcj9+sAj7IqJbJZgnUMTbO7cQSEcdtyn8tdqJBLJLOXJ/COlHVvxB
            a4R0Y8uLAT2SMJAiRM/k3LMFmWwdXjNqK4zJREMu1pA8KUSoaDx7s3VUjAYu1wLk
            JTvl26eb63D7f3RYKSJqG/lTU5ZyZ7ItP8g+j9wWgFbaXxOSgywRsgmq9s+JVCeW
            kohiuj5weO+nGNesUpGORaSPWb7JkfSy9Ett4XfYc1L0Q3KTBCDaMjM2Ckm2375E
            C91nMIrxYLJjRP+gmqq7aP1qOEwFKmTIcUG+QZ3Qsy81Te24Lm3Zlbz0O2TgXQO4
            8GfpwrqTr9lcWzeXXvuJN2l0aiRCblh2ooAwqAefbnKFBgFXQmnB9SzHUDnmJKcw
            bpTqlvtRoiaVqAa9vEzAltnwV9t1TmyFbVVfhalrf965sE8OqEbMJhLfib37cpbU
            ZgEJAhB1RULNEvYyO/zfZjOIF6OCJKsSsTfn0SWiFGa8zfBrMuxe9oPQ2QPoRna5
            paVQJrGIxc1k7KwYSh/vBkYSk7IRUpL5YXDFSQH+EyCFt8H15dOM58fOIePVBSnf
            uVymHiEmeQ==
            =SxCO
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
