# --------------------
# Wyoming Whisper
#   - Repo:           https://github.com/rhasspy/wyoming-faster-whisper
#   - Docs:           https://github.com/rhasspy/wyoming-faster-whisper
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
---
replicas: 1
revisionHistoryLimit: 0

image:
  repository: docker.io/rhasspy/wyoming-whisper
  tag: 3.1.0
  pullPolicy: Always

args:
  - --model=tiny-int8
  - --language=en
  - --data-dir=/tmp

ports:
  - containerPort: 10300
    name: http
    protocol: TCP
    service: true

# Uses ports from .ports section, if service is true
service:
  enabled: true

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}
