# --------------------
# Wyoming Piper
#   - Repo:           https://github.com/rhasspy/wyoming-piper
#   - Docs:           https://github.com/rhasspy/wyoming-piper
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
---
replicas: 1
revisionHistoryLimit: 0

image:
  repository: docker.io/rhasspy/wyoming-piper
  tag: v2.2.2
  pullPolicy: Always

args: ["--voice", "en_GB-cori-medium"]

ports:
  - containerPort: 10200
    name: http
    protocol: TCP
    service: true

# Uses ports from .ports section, if service is true
service:
  enabled: true

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}
