# --------------------
# Wyoming Piper
#   - Repo:           https://github.com/rhasspy/wyoming-piper
#   - Docs:           https://github.com/rhasspy/wyoming-piper
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
---
replicas: 1
revisionHistoryLimit: 0

image:
  repository: docker.io/rhasspy/wyoming-piper
  tag: 2.2.2
  pullPolicy: Always

args: ["--voice", "en_GB-cori-medium"]

ports:
  - containerPort: 10200
    name: http
    protocol: TCP
    service: true

# Uses ports from .ports section, if service is true
service:
  enabled: true

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}

resources:
  limits:
    cpu: 50m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 256Mi

livenessProbe:
  tcpSocket:
    port: 10200
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 10200
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

startupProbe:
  tcpSocket:
    port: 10200
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 30
