labels: {}
secret:
    stringData:
        OCTOPUS_API_KEY: ENC[AES256_GCM,data:nXedJymB0K6papwp545dOVjJW7YoeSpxBzdHEJ+71eQ=,iv:FjA81ex/ewlU40tiu/F3zsgxUjmZ91sJw34V2nsszlM=,tag:1GffbUkqvP+ANMvtSZyTyg==,type:str]
        OCTOPUS_ELECTRICITY_MPAN: ENC[AES256_GCM,data:UDAtYSayk/qPuxlbrw==,iv:nEctVo11NM/KWaIA2CCJ8Bu32y/FMV3cR52jpQK18tY=,tag:7JGB4wI3Sndun2iCTJD4Gw==,type:str]
        OCTOPUS_ELECTRICITY_SN: ENC[AES256_GCM,data:AwDp+2+nthHpsg==,iv:4Fr34dU9PLJ6DtgJbLvE3VVdnbJH2TjfKlFpcX9gBWU=,tag:lo9Bh6b+0qI0QlZOgDvYbQ==,type:str]
        POSTGRES_HOST: ENC[AES256_GCM,data:sgEVBgG01JfU4fQJ3TSSzkR+,iv:NBh0ZGS8Vsz4fOdc92pJ+xqgq9tg7abZP3UYcGYufXw=,tag:SyJ+5zXS5Txt1C0Q+QO7Xw==,type:str]
        POSTGRES_PORT: ENC[AES256_GCM,data:Tw8H5w==,iv:AGBb8o5VOw+5Mwgq9UxKQ2Aq5MFD9+V6ove1B1D+DqY=,tag:37lFxNNCF2HlJRKdUFyaKg==,type:str]
        POSTGRES_USER: ENC[AES256_GCM,data:SLkrjImnieF/Lw==,iv:+R4Ip7RBqwdzCwv/IA40rr9A4kBdsmS50IQdUDQK5rk=,tag:/qmi7KAHpkp4NPcoDpIK4w==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:uF+6yYu3fiASzGIEAEC6rC6lnm4=,iv:1Y8k559sVELDSn5kcoaWDsXWv2Y6AuuBJVnrU5/EGio=,tag:PUSCyqQRItf6UXIR3khQHw==,type:str]
        POSTGRES_DB: ENC[AES256_GCM,data:w1NFNid2f7gtug==,iv:smJ0SFilnZrjR63iF1NyneVsaqhwrwDRBDZGO+VQCgo=,tag:tgGHrE14giM/tb9KqmrKPQ==,type:str]
cronjobs:
    - name: octo-usage
      schedule: 0 10 * * *
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      backoffLimit: 0
      image:
        repository: ghcr.io/afonsoc12/octo-usage
        tag: latest
        pullPolicy: Always
      restartPolicy: Never
      args:
        - --infer
      resources:
        limits:
            cpu: 50m
            memory: 64Mi
        requests:
            cpu: 50m
            memory: 64Mi
sops:
    lastmodified: "2026-04-13T20:28:40Z"
    mac: ENC[AES256_GCM,data:qGtvmPv7XZpKUPT8Z8zeOly8Gd74bSfcsBqLjdJvfhR9Fr4Cz64ohHqhReusO//xXKMIRG5LXqQIZgScB1sqZ6gyhzHle4CwdlH0S6SsC7qrsdUnl8bIqlz+MkRKxP+pphUwxZx4IztPGXIwZJWpFM8XC878Gy09ZpjxCy9cJ9c=,iv:pqbcPNlMk7YmAu5NbY/qIFr/TZummVbfS3qNgQBHV+M=,tag:Y8az7+Sacz/zZYQCbXtHmw==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//YuP0dqNEDYDVJ90LOvLivcAXhOJblhmVv8OedqcsRUya
            mW/lu43QY+d9dv9RD3o1XoY+KYL1W43rH+WjMPKCaXH8A7L0r+T1Bn773B7+Vqct
            N40rjx5eRxm91NcxjQhJSpvQhGATzg/QkGksh4YcEG689vOesYc508ueP7idqBap
            3tKct8hG3Ix1jhLkWbRhGGy04FLxpjRpC16YkhKs5jEvF2ldqdE7GeqfTEcTgUKE
            BjWnqriVHRRoMXUSkoA0YKp33tZnR7YVrDYwjqwTpTFFJ8x++aEjYqjzysrVp/yU
            8+/OLUW5hHRJgBh0GJTzxOYWQkIvaPeFMkZB7g5/Rp5UkGbymp2V2WTRbueQBJGb
            oee1zzsfwbCiF+vTM92RyV42V4Jbsnuy/EF4pmZCIKImh0wfQa0sgRR/7wi+SpN2
            OBwIXn7rVuocsvaNowpch82bapsly5onwdqov2boWDjCJn/gCSNYQM/SPFsD5K+t
            ghImUcFar8jbAILBmfET0MCuXi1NRmF6q/25zqRB4l+JNpMgm+8M7l262D5EhYPd
            iINx50mu3rMqKhxRK9OUoyK0BAn2vjahRDirBAkSnFVp1oPHHRpLquiofxSx1n+A
            nYzpHYB3QrOwGTJ/Hn+v2/PTlEtAUjQQ5ZabU71bOjda571LQHCBw4dPP3IUIgbU
            aAEJAhCBBo+noUPZRUaUDVCCQRRbsfQzISAppUX9VNJvg1cZBnoqqGCQPXE7ILu/
            C1p04MxdusjYnqzwIwDT47sxjmBnEQuAMjAG9gS0cqnEg9KufTnBv0jFQBmbKtzH
            9dkHOLwV/XUG
            =nVpD
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
