---
- name: Update packages
  hosts: docker
  become: true
  tags: [update]
  roles:
    - maintenance

- name: Install Docker
  hosts: docker
  become: true
  tags: [install-docker]
  roles:
    - geerlingguy.docker

- name: Deploy Docker compose stacks
  hosts: docker
  roles:
    - docker_compose
