{{- range .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
    {{- include "homelab-svc.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  suspend: {{ .suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "homelab-svc.labels" $ | nindent 12 }}
            {{- if .labels }}
            {{- toYaml .labels | nindent 12 }}
            {{- end }}
        spec:
          securityContext:
            {{- toYaml .podSecurityContext | nindent 12 }}
          restartPolicy:  {{ .restartPolicy }}
          containers:
            - name: {{ .name }}
              securityContext:
                {{- toYaml .securityContext | nindent 16 }}
              image: "{{ required "Must specify image repository" .image.repository }}:{{ .image.tag }}"
              imagePullPolicy: {{ .image.pullPolicy }}
              {{- with .command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              ports:
                {{- range .ports }}
                - containerPort: {{ .containerPort }}
                  {{- if .name }}
                  name: {{ .name }}
                  {{- end }}
                  protocol: {{ .protocol | default "TCP" }}
                {{- end }}
              env:
              - name: TZ
                value: {{ $.Values.tz }}
              {{ tpl (toYaml .env | nindent 14) $ }}
              envFrom:
              {{- if and $.Values.configmap }}
              {{- if or ($.Values.configmap.mountEnv) (eq ($.Values.configmap.mountEnv | toString) "<nil>") }}
              - configMapRef:
                  name: {{ include "homelab-svc.fullname" $ }}
              {{- end }}
              {{- end }}
              {{- if $.Values.secret }}
              - secretRef:
                  name: {{ include "homelab-svc.fullname" $ }}
              {{- end }}
              {{- with .volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .affinity }}
          affinity:
            {{- tpl (toYaml . | nindent 12) $ }}
          {{- end }}
          {{- with .tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
{{- end }}
