{{- if .Values.extraSecrets }}
{{- range .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "homelab-svc.labels" $ | nindent 4 }}
{{- if .stringData }}
stringData:
{{- range $key, $value := .stringData }}
  {{ $key }}: {{ tpl ($value | quote) $ }}
{{- end }}
{{- end }}
{{- if .data }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ tpl ($value | quote) $ }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
