{{- if and .Values.secret (or .Values.secret.stringData .Values.secret.data) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab-svc.fullname" . }}
  labels:
    {{- include "homelab-svc.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ tpl ($value | quote) $ }}
  {{- end }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ tpl ($value | quote) $ }}
  {{- end }}
{{- end }}
