# --------------------
# Cloudflared
#   - Repo:           https://github.com/cloudflare/cloudflared
#   - Docs:           https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
replicas: 2
image:
    repository: docker.io/cloudflare/cloudflared
    tag: 2026.3.0
service:
    enabled: true
ports:
    - containerPort: 2000
      name: metrics
      service: true
args:
    - tunnel
    - --no-autoupdate
    - --protocol=http2
    - --metrics=0.0.0.0:2000
    - run
secret:
    mountEnv: true
    stringData:
        TUNNEL_TOKEN: ENC[AES256_GCM,data:vo6TFJBEz0UvTgWEVo4pZtr7FLJLgFSiC6kjsZg3HV2QNxaj+iaeNMrklpI5V2MrqR/xHuS1kGUjoEk1aRgBDVyNXDW20aaBQKwP4vChK8iE9Cxy6NFmubFMnB8HRUBefB87EnTjhyB5TUiUoYUWEDOsGhvUIn29XvUfpYwWZ33MMYHJE20+wWcSwEaOEa+a8T/sHFU273Tt+Rb8nFySjfZjDUU2+0ZrYP1Wkx+4t3A+sYwN,iv:GwjDxf291vSGLyKzlia/szdOW9HGdEBMKQ4PbEog38g=,tag:haPQC0OfRmWkSiK6OxpQKw==,type:str]
    livenessProbe:
        httpGet:
            path: /ready
            port: 2000
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 10
    readinessProbe:
        httpGet:
            path: /ready
            port: 2000
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 10
sops:
    lastmodified: "2026-04-13T20:28:44Z"
    mac: ENC[AES256_GCM,data:2zul+SaF/ZlOoP4NESrhZaj5cfx+mb8rhrUPn6MEXDrfr1Tw6MCS9J0r6YbcH7Ij8zuYhigtiyJhUVd3uCPj1UU88PxwtagTEk6aoYq9ajCse1Jh7WEUySdX42K2N6U/xqyFv8mZsb2gnSqcJ8ORXbYNQ6DA+ABAWi9sDeIPpwI=,iv:oKDaPCNv8sC8MnHoACf1/RuhC4Uh3etV20I1/eA2l0o=,tag:LaYyNCJcdq6EFaHrxExqbA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//dbaG7tkMLayPGIN3qhoIvFV7KIKJ5ZkFfj8pzmcwZIEX
            Gkt4cRnrQAFuzn6rSM58Qb5ZZT988vZ86+Lpjvq2xmDSeSD3xFDaKURRsDBVaPzI
            f9SsqmgDKunwL4FIYYrxH2Gl6kOPks13KJ+nGtumYJjhJ/M/buLgF68I+6i8LtM/
            bp0H/EjRDq3CZZJZ2H4o99b5pHB9YiXXv+BxQxyjOse0ztLGvYvZnwJkQUM7p6/r
            kM+b9vq5fmfH1tY2YS0BJWhZ1tmehZVBXaE+bw9jmtLDIIR3DFJG1PVfRn3yfeUH
            5WGJrDtoL5q2zAIJkYaDRSTxue96e2r6fI3YTuXkgzEIIMeYjRu0YNoneHiIDnaT
            /WkNAm+eg5LGqZAFWiU9mT/aa9qAIuDlN6ianjF3R4Y4vpG4sVxHsArs9SmeT/m+
            goeP3D8jQpB/Mm/5K6Gm4aQixyxchkAScMDiKf4uEdFxsG+Gim+htwL1E0l1DUu+
            8y8LY1QcjiyiFcZrDJb017zJwELCQldVcdCM1KkAYII4x5o/D6JgADwgDRkLMKDz
            Af1tuhdXRATajmhT14hKb1IGD+d/LFfaPRCa+GPKT1hNmVlwhYUjst+ou8PMtAf5
            BBJz4+fDzp7IPgbnrFI2QGLt/YSN3NTHP4JJOQy3aS/DHUPCzJVuqRo1wI5aQ8vU
            aAEJAhCiuqiBkaVkhX/WegVnYHGDB3YK7aqGaZRokVa+nSgRFZqGjCxikt6lqBqL
            1B987haz7cAdiyG3NBzZpcnnbDqd0G7aj2L3+YFkQ46cxwm0yMCppCSWyerNGyPZ
            s9A+dP2zwvDN
            =9YNy
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
