# --------------------
# Cloudflare DDNS (UK)
#   - Repo:           https://github.com/hotio/cloudflareddns
#   - Docs:           https://github.com/hotio/cloudflareddns
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/cronjob/values.yaml
# --------------------
secret:
    stringData:
        CF_APITOKEN: ENC[AES256_GCM,data:K+86EOVB4+uzRwT8SM4i+Ugn6g2/huF1VF6y5S83PJei9EUy8NjXpw==,iv:sKSjCjwKsNH8+VIcD09Ajolo/UxcK5RgVMlyeCCDgss=,tag:PloZqIMVqJ/5pz4Wad0Q9A==,type:str]
        CF_ZONES: ENC[AES256_GCM,data:OuC0grkC92JqNQBrEsFQXWzMSDArZue15elRSszTyYY=,iv:harM54F3CBBRwlOzJr4j+HS8rcdym4o0fnQ9HtARy+E=,tag:YXDmeyzCPcwxYCMGVT7Tng==,type:str]
configmap:
    data:
        CF_HOSTS: uk.ip.{{ .Values.domain }}
        CF_RECORDTYPES: A
        LOG_LEVEL: 3
        INTERVAL: 0
        DETECTION_MODE: dig-whoami.cloudflare
        APPRISE: ntfy://ntfy.monitoring/homelab
cronjobs:
    - name: cloudflare-ddns-uk
      schedule: '*/15 * * * *'
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      # suspend: true
      restartPolicy: Never
      image:
        repository: ghcr.io/hotio/cloudflareddns
        tag: release-34a15f7
      nodeSelector:
        kubernetes.io/hostname: k3s-m1
sops:
    lastmodified: "2026-04-13T20:28:44Z"
    mac: ENC[AES256_GCM,data:kvNK7yB3i0pmCm1qB6CddRgaH5diI+wJXt0uqQwFR+CNWpRMAV00vYUdcHcScy1FkdtwHVuLXAb3HFXAprmaR6ktiujYLCS1rABUWmCbnmB+722/wEEn2Mt6/HQCcYYsZZCJ58hw8ckSR5jkei9s7dp9NxcbPU6UNiNZRJb7Bbs=,iv:0HJca2cZlk+K2e70aUm7UICp1qK0dXGkEwUZJf7NnEE=,tag:IxgFL5s+ZP3fGEKlngayTA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//e+xyG+WxW+plPh5kHe8OH7Dr2IzcOo19eh55uoVIaSPa
            xRnBWzQHaMjq3KZ1GItAL6z0hTPJV2Zyup0rWJjZgQhI5KEUEBfh/UZeIFHr7k/U
            4wf2zA0qSc/t4JNfxWAAIOvKzN70AmSMdTb1al828avLhKJu0nW1YImvar6ywPkz
            pHpfYfqPX3JyYPerjPMO2XHs79LOyv0CWBiQuZKMYbz2v/QJI5nc8oYx/mDx0TMj
            dbJsmOvLSQvq1XHYgyF7FdQMLLNVdxhRVfpcXxCQLEuI6+APKAq7DILA0YZn4FLu
            gldoQjdm2k4QW0nNq4yHQbCeYskZQaM73FDr4t48SUVxC8oZ7tCUg6/PK6eHusSy
            YNZm3Q5mxcZVX+OB6gSNd5fHnI7ex3JJzLbsMlw0WETkz1Pe25JJTD/oCNeVOcEm
            DDPppFJT4iS4ck0pP6HLlyp1A5Aw7T2TY+H5mc42gFscBZc1J3w5H71F2m8K/lja
            wSOJWx5SSGXS/ZPr13u8ZeZgdStuk/DNfbWxn0q6hhyKKTGJ3JFg1eKmqauxKK+a
            RUXtdlJTrvZRq6iJ4Izn2UbXC1YHQKiJS3YvFztbJ3lCQx8/PCM2c/QhVSKCIrFA
            NOUW/UnB61EOfdvlWeGiJQmCIz4Y6xzRkHiHMH2TSwVB69Kc5AoIAyZCm4KinizU
            aAEJAhDOBjLRncFLF7mrec5SFep8+omR762SDIRVNG3XXq5Uhl/aXy+AnP2FKx+L
            UJEMGLCDEqgw4v/AqlAHc/x7Nnzfk0GPqlVmneDWu0iafd8XAPF+ND+sAKtmUjsy
            tlltu4YvVJ2G
            =0rme
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
