# --------------------
# Cloudflare DDNS (UK)
#   - Repo:           https://github.com/hotio/cloudflareddns
#   - Docs:           https://github.com/hotio/cloudflareddns
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/cronjob/values.yaml
# --------------------
secret:
    stringData:
        CF_APITOKEN: ENC[AES256_GCM,data:x7ooNBAta6xd3D8gOwUIfq+kJxNnEQgPppGG+OT9O8JUXkpqOGpNaA==,iv:KsPme9bLvmjJx/HU8CozIGDlJt80fGEst4cakOlulPI=,tag:9C+BcKme/zjnak7TTIMGgA==,type:str]
        CF_ZONES: ENC[AES256_GCM,data:wBjSA464KOLMlaZqRv1DOwfta4LOxFQP9kQKqX5WuAg=,iv:finNbUicJTQlmkOAeR8xRzOH87sFoO9awUzWVsXlVtw=,tag:xB/JfBd7BO7CIR4OOZPK0A==,type:str]
configmap:
    data:
        CF_HOSTS: ENC[AES256_GCM,data:QbnOprq3lz+A8kleSdE4IoDZTJO0m6dA2bI=,iv:wMH+tbzEGyV0GACANUExlA73vKfqjCJHiHcR9cAVIPQ=,tag:6hyR9xSd3EB01msyH3HnVg==,type:str]
        CF_RECORDTYPES: ENC[AES256_GCM,data:tw==,iv:ShKSulBmgaz8Wuwvzm22xA9o0zZVq3uqHLJwG4e9thU=,tag:eP38ebg+gl9ECA79LbxM0Q==,type:str]
        LOG_LEVEL: ENC[AES256_GCM,data:aA==,iv:TUK40zZwF3J8mObsdsA6qj/A2iQMRYLR4/xNaZR3EMM=,tag:/EAY5LAUW8HOcDt3irZEhA==,type:int]
        INTERVAL: ENC[AES256_GCM,data:Mg==,iv:5GO8TGIAD5u4jLtKilsWZy8xf6Bld3jN1NjYeA7PnA0=,tag:GX79NN9SW3enfOeIgpPuVw==,type:int]
        DETECTION_MODE: ENC[AES256_GCM,data:CjDn84PEIwnRVgTVggWfjb7dMwnk,iv:SMQRFWZLa4jiLcHu08EhgqEWfAPQNsymi4jVdR/voAc=,tag:hkIHlxSrKFXvubCSmSAPug==,type:str]
        APPRISE: ENC[AES256_GCM,data:LoGjhaBewrGdmTGk23uortC/WHwhW8crDvQaOKOq,iv:QVK5JbBh+aRLrc29YxcQGTlIeJFz4rbFRcA8cXKRT5c=,tag:RxPtzSGxtgXyl2SbVeVVMg==,type:str]
cronjobs:
    - name: cloudflare-ddns-uk
      schedule: '*/15 * * * *'
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      # suspend: true
      restartPolicy: Never
      image:
        repository: ghcr.io/hotio/cloudflareddns@sha256:dbdb3f7854ce46ec52abd392920cd74a02b7d0b95543f16c94108cb864d6cec3
        tag: release-34a15f7
        digest: sha256:dbdb3f7854ce46ec52abd392920cd74a02b7d0b95543f16c94108cb864d6cec3
      nodeSelector:
        kubernetes.io/hostname: k3s-m1
sops:
    lastmodified: "2026-05-09T18:33:54Z"
    mac: ENC[AES256_GCM,data:uAm4eHIbnqV78l9o14jMiqBl8aiWheyioQcPIU0nzv/682wSw0xcQpSkKe0v2q/8wHm6jDbEXn3/0VAkEwpJK8e1d9Tv5TAKEM5uPz1ptls1awUlaewrOW9MuFb95+GOLjpFAzofONSWAbDywHFZYzXl+mP2MdsFDjNWQ79RJGA=,iv:zbf0Byb6z8sy5WgVj1R3mr++pzM41DiXsMm6kT513GM=,tag:wh5OiZN6pq/Ry4jOwc4PPw==,type:str]
    pgp:
        - created_at: "2026-05-09T18:33:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//ZGuk8/l1CjUJuWt7CsNT5CZRQkVAMUVx5f1VylShnUt2
            ugv/gEh2LWNkmRYGxBS+yOM2Dh9Q4B+tn5p88wHA4Mzjysy7toatMCnGcy7Ftwua
            qZ35CU0XfsFk4HIVtHAXfeowhQWZMCa1KQ8YdB7qB6OGRGWAu4JPevTcYhV0/iAp
            F1hu4Iv0PL9dFaJMTkV7MCxT/PYJeamhxi9vC7BCtByDnJnl1onxx+Y/bSNWmPB1
            hZ+YKfw67ExdJcExVoDgt7ijkELzAQXRG3ZDujf0bRmELK06rLb5l2FWU5ZIZ/zR
            hp7gSqi2VQiPULZs/UmD91ZzCSYkwDdYUD8+o527xmXA2PtEQ7aOFD908QeQpgvI
            Cesn+hoez2H5cgwvhjOBxB6KqO8FlEZi3X0buaBUrnhxwFjMldGhRQ7Rd9Yprdb6
            0lW0FGD2IusIDq5KEnq1c6PjB1PIpNNk+Jzfi+7xv22rluj4TPmjD/jJ7DSk9z7c
            DD4Ic4gAS4ANE/0wxEasT6RBkXiWaYWb3T7jNGFAzDgaH3l8pABRExie5+m0Ujzp
            D8knfdXZTUeLgEVbEh+Vf6qFncTV8xpObqnl3wRv0fW/r5foDA5Nhs82gc8fdkIJ
            rEEtw836ownrjgZmg73OvPmDsbj59k9iD81fUfoWxbAOe43+me8CUSosZ5fWH97U
            aAEJAhDJ196ZxiDr+tBWWSXKvrAQPE/hIRSbvbtcV3/s/E/CqmhkF2WWmeD1a2rh
            671HW7GBogUM+1vOiHLMnlXSGPdSqTjziqqBYltql+9GWeP63uxQEXAvduO/ncGH
            w02KR2kzG23g
            =Qinw
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|secret|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
