{{- range $name, $addresses := .Values.ipAddressPools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $name }}
spec:
  addresses:
  {{- range $address := $addresses }}
    - {{ $address }}
  {{- end }}
{{- end }}
