apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: addons
spec:
  ipAddressPools:
  - ip-pool-20-lan-uk
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k3s-m1
  # - matchLabels:
  #     kubernetes.io/hostname: k3s-m2
