{{- range .Values.l2Advertisements }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
spec:
  ipAddressPools:
{{- range .ipAddressPools }}
    - {{ . }}
{{- end }}
{{- if .nodeSelectors }}
  nodeSelectors:
{{- range .nodeSelectors }}
    - matchLabels:
{{ toYaml .matchLabels | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
