# --------------------
# Authentik
#   - Repo:           https://github.com/goauthentik/authentik
#   - Docs:           https://docs.goauthentik.io/
#   - Chart Defaults: https://github.com/goauthentik/authentik/blob/main/helm/values.yaml
# --------------------
authentik:
    log_level: info
    # don't change this after the first install
    secret_key: ENC[AES256_GCM,data:55V+ok8jQNVnGdOV8gepybc18saq7iLwxz9nMuIwjHtsN3KuHnFPCg4rRzzGqKvBFkv+zwIiRRpr9KEOgql2t0YgtgE7dcWfVzadJ8n3wgQ=,iv:Q6lKHmnD2qIOYkTPJzqcro6vt2sXLL6mbPb7wfNexvk=,tag:ZeqwUkaVOd1tUBIwiuvmAg==,type:str]
    email:
        # -- SMTP Server emails are sent from, fully optional
        host: ENC[AES256_GCM,data:ZH7ygXU7QI3AQesHQmZJ9ak=,iv:r0is2T+kjuw1DsiaWmPPAhdXLoZ6eK+9K+flyQiLi2Y=,tag:aJjYWbMiiVaknTmmI6hYVQ==,type:str]
        # -- SMTP server port
        port: 587
        # -- SMTP credentials, when left empty, no authentication will be done
        username: ENC[AES256_GCM,data:bWuitbwQoaqbUMn/vzmxbsBdjcYe697keirkGH+y0eM=,iv:8Dm23J4DNAp5akZVU2409/8p9HJeN7L/PJBnfW9+ZlA=,tag:a0oBHNQps27Zk1mhwK083g==,type:str]
        # -- SMTP credentials, when left empty, no authentication will be done
        password: ENC[AES256_GCM,data:OXtxqpNeeIl0oY8NKTVGF4zoC0FAstneNgbsQvw/uS0=,iv:DN+5kmVhunaAFFJVNZdcGeDjDE18SEHHc4ZIkbQJqRY=,tag:pUvbTdZdsUHV8bTquEXXyQ==,type:str]
        use_tls: true
        timeout: 10
        from: ENC[AES256_GCM,data:FBF8yUjJgUVQx18330tHLQBqDfOLmROzqjwhjzw75Ttd,iv:mn7peAtBXdTz7DJaR09DsMuvn0lgaSdZPccClU1vdW0=,tag:gKJiSbq5CE/be8g8oXFaNA==,type:str]
    error_reporting:
        enabled: false
        send_pii: false
    postgresql:
        host: ENC[AES256_GCM,data:5GkFsRl053hZdwg/eUnohtRN,iv:0p/qu5cfWbLyipmNpXO43TcVPDjKZE9WENphx+MSOt4=,tag:Vw5b8cKpic/nO+yn28Ay5Q==,type:str]
        name: authentik
        user: ENC[AES256_GCM,data:jQzoD+3Q5009,iv:apZp5ICdaHi3iZgnk6GOTPl49fxBWoKlq8pSIdvp4/M=,tag:dntQbybhq+gXnpWXhNqfcg==,type:str]
        password: ENC[AES256_GCM,data:MeegAiu7X9UYWmZon3QHsJlxxHw=,iv:L+dkfVPJ6+qmhxowyKTcT9B9bpBC8WZkkmqpFhpyw1Q=,tag:uxzoqdJPmaCSMY3S9H1OGg==,type:str]
        port: 5432
    redis:
        host: ENC[AES256_GCM,data:n/wlfMBjeFrWBTHHyGl4,iv:2bMBzaWqorDqkFv9L+FRIsSfc8MnHoPJV5ZissINzLY=,tag:5j6vkk/rVyHtU79G3S79kQ==,type:str]
## authentik server
server:
    name: server
    replicas: 1
    ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
            - ENC[AES256_GCM,data:ztVKubsoWYA/lWPNfcsSkh4=,iv:8AUzHd3pxzhNdEMs3VXV3ULVja3QxoccYNh1oiRUXpA=,tag:ysKtrC4yznEciYWUbSY3PA==,type:str]
        paths:
            - /
        pathType: Prefix
        tls:
            - secretName: sso-cert
        extraPaths:
            - backend:
                service:
                    name: authentik-embedded-outpost
                    port:
                        number: 9000
              path: /outpost.goauthentik.io
              pathType: Prefix
worker:
    name: worker
    replicas: 1
serviceAccount:
    create: true
prometheus:
    rules:
        enabled: false
        # -- PrometheusRule namespace
        namespace: ""
        # -- PrometheusRule selector
        selector: {}
        # prometheus: kube-prometheus
        # -- PrometheusRule labels
        labels: {}
        # -- PrometheusRule annotations
        annotations: {}
postgresql:
    enabled: false
redis:
    enabled: false
sops:
    lastmodified: "2026-04-13T20:28:43Z"
    mac: ENC[AES256_GCM,data:uDYn8hf/m9VxSTqS97lPJCVy4+UeuS5aYRGqtVWpu6vV2EyxapBSqndbaqa1bTk95MshKb20pT6J4FMUoCzgAiJWDpKE63hzUNlT75gSZLjSugpMxj8EENc5eq0v93bVqshrqWIQrDRBqZ6mS+gWXTAM2x0G4/pycQclcY1RsEM=,iv:PK7/sglpyaXjgH1pUn0XuAw2QJrN8cZYv4M7LfE1p88=,tag:hrIVnP+LxVKBtRX71RjA4Q==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//Y4tXQfbtOQGSm1cwZSfpcJ5HKBucjPJ9MhElG7zgIdjZ
            eBMOMDJmXDNDGpDjRxW27zgOKDX4RCv9ckug85eK3ODtdKKWZ343j7Zgm5XBsPHs
            p6F6jmm0dJM7m0z2mp+nVtHrHvmMMFGcE8bCjm4AcCZo6FAKYMCymUhTphLgX0nY
            LIMvdzclEzYCG+DsWBbCBiI+28AWx2igqXuZuTh8HDYUvQE8pxC5JtKr3K9a3Vxt
            fY5o10ZtUvy+uci4Bj6FcUU2pwiOAN/ErLcr/WgIBOCmVKcLc1+UBYTn10vSYMed
            I2PLFYogcsJlMieew5Ql6TqNbo7lEH9LapcB3mA0m8McAarM5QENKMcGvLbFv2X5
            +zPD3gnQEzqdY+ZPpEqSU+hkE2v1xlnjjo5vpSE9G9Iy3PvfMejJaMynceWKad36
            XeOEGR/5vwo2215zPtOJUqDUt28kz6fJ2+9OcQNFBwCQVKlld7v111CRzhvsruM9
            AvCuq+4SBQgC9hqrblzow/UW4Lfuxv2wVFkzRN6XsI2VN5jiv4gi6YrwiLoI7WZZ
            mbg2/Ol/KE+w4Csr8fYQtVMqdPrmXRW4E6G0rTiqlDO3QmkXlMHtDzGoiRu182YW
            1hCF4CJyLGjhSXCKF6YkR+U13ZQcVG1pVcgzfTyiPn693eJQi7mTI/Icm8Blz/DU
            aAEJAhBr2XTEIOxu7tIcuMO2WkpnUz8m3+rlihJesKm0kvGsHsjnAozakPUz9y6N
            PmdKy4nFis+Ps1KTVWMTShNlv5O4i9UhAAvjjE94slxy2eGwoDPKLwRmp5keeRFE
            /78PQDnWhIm1
            =6Bef
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|password|secret_key|username|host|hosts|user|from)$
    mac_only_encrypted: true
    version: 3.12.2
