authentik:
    log_level: info
    # don't change this after the first install
    secret_key: ENC[AES256_GCM,data:DVM1lPwFQV6RPRq6vlpAdh3a5Sv/Mnha4MS6GI/fmmXD4GknPnRyainU7rEt+0KqHokPTG0+VG8oH7fO81UM6HWiPci0oGM2RrSxWAI2rfM=,iv:MtJKCq0yCqnxSFj9W5EqE2QCuGAKf5VGSTKSrT39s1I=,tag:MR9lctD9TaJDFEtvpMlT4g==,type:str]
    email:
        # -- SMTP Server emails are sent from, fully optional
        host: ENC[AES256_GCM,data:lc21Km+L2ZxMsFYCdivULPQ=,iv:K3EYWnOvd6uNANyuT+BsRb8+CptNUqVciUYyAvv8hpg=,tag:llWZSrWs+GVsIEpimioraw==,type:str]
        # -- SMTP server port
        port: 587
        # -- SMTP credentials, when left empty, no authentication will be done
        username: ENC[AES256_GCM,data:VZaqhVwzkE88iwyiBs3S7Q2W+aqrOjNIvRjxdv1Ejbg=,iv:t66HNKHet+iHICbu0ROvRH9tEt4dsQ2j7pHnv20kYS0=,tag:tMEh+EKg72Mk5IfzGc0k7w==,type:str]
        # -- SMTP credentials, when left empty, no authentication will be done
        password: ENC[AES256_GCM,data:s0V9+t4hQNfEEt+tZ63fjeoI6oW08irhA4jkRQuFyBI=,iv:NaylUUXqWHSmeq86sezKrpQJAZ4ery70atP/KAeLCIY=,tag:lkHvtqS2wjvJIL2jjgE3qQ==,type:str]
        use_tls: true
        timeout: 10
        from: ENC[AES256_GCM,data:JHPwSommm7WhwtfiG9G1Bpq8PDvcD5d3C4PgDEO64KZd,iv:6oe4YEh+nIkIuiTMogEpbOHhSHO5nUpuUmxDJMRZFJI=,tag:30h3NORxzR8S4bc0NThNOw==,type:str]
    error_reporting:
        enabled: false
        send_pii: false
    postgresql:
        host: ENC[AES256_GCM,data:kkLTkWb0xds5zj8gUY28OLYx,iv:vJs6evh4gxJphZFy90p4HPaxedXZLMp7EZabg3aAXn4=,tag:oCt7UodkCCPqE/bLjIjneg==,type:str]
        name: authentik
        user: ENC[AES256_GCM,data:r8rheVaIu60j,iv:y1jVLjjCEzE81NHLZu6+u641+qYl7n4m7/sMIlwIp9Y=,tag:4g1PJwBp340CvsO9M+k0Zw==,type:str]
        password: ENC[AES256_GCM,data:0wrSltF1Zcds7cQe8m5kBdAtlWM=,iv:YF8+/OZKDKW2pHS7UuLeG4FzGOQzzKm67AfYZ6MwdAE=,tag:jFcPicurIcpHS+j5LEUWDA==,type:str]
        port: 5432
    redis:
        host: ENC[AES256_GCM,data:I5VwT1uZxWWRHDCU5vZS,iv:S59zwvGwAt2tZacQqCIHPO+/Nr/LThExdq69Gth5Pdw=,tag:eeZYfID1OqyIbGKZl/Z+pQ==,type:str]
## authentik server
server:
    name: server
    replicas: 1
    affinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - mariadb
                topologyKey: kubernetes.io/hostname
    ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
            - ENC[AES256_GCM,data:TtDMqjBMhR1CW+AhKUspc9o=,iv:tUP6FWdvZvIBbIhp4Yspys/R9m5Fyji80AZ7z73qPmM=,tag:ClboLYtWA/1BfWq3gaY1Yg==,type:str]
        paths:
            - /
        pathType: Prefix
        tls:
            - secretName: sso-cert
worker:
    name: worker
    replicas: 1
    affinity: {}
serviceAccount:
    create: true
prometheus:
    rules:
        enabled: false
        # -- PrometheusRule namespace
        namespace: ""
        # -- PrometheusRule selector
        selector: {}
        # prometheus: kube-prometheus
        # -- PrometheusRule labels
        labels: {}
        # -- PrometheusRule annotations
        annotations: {}
postgresql:
    enabled: false
redis:
    enabled: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-13T22:53:33Z"
    mac: ENC[AES256_GCM,data:2p4OFYRGicheVYskzsnSgZrDA3XAmdkpC0DNqLGUne1SoIn/DkXdrpvEMtZvo3b3xgtQTOYQxmkbV24z1vmX3xBOU9YX1VB551q0D/WcrGgTGBV4tPTIevG4lM2el14UmTKzRBHPHr79yBswJTWzXrcSblZeCqPvJvseu9pIDmM=,iv:bX7tPxPPjSFV42fYBEkXLEn1ME8T8o6LTpsPgSh222w=,tag:CWD+Vib9ORm2svmNAHrKxw==,type:str]
    pgp:
        - created_at: "2025-10-13T21:25:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//WbooMX2TbyYrwcxilrd610iLZ9P2AX7U2RUlMsoQuUXc
            QmAIALnmCnYrWyxn4Uvwziuvl2GYAVSp36XDbhZzxnvDRTc86OWZroSx4zctxDlX
            MMopA6LD2w99BYve+LntO7Hz1LWiDuerwva3GOOiRrx2KejkP7uDqVOEe9x18EOY
            SYeoMosHbDnbOBKr71uzYJAW/laCG984VNK5LCSBjxDV4QcfOCoHMo9U2DffbNND
            g65df1Dhi25yMJNXnLqBkbES1fHUJFDKdCU2+S0L26Riez6RiXWMj8K0KHTdWz4Q
            GbGOvXw0vIsyMu4/82WpwLwo8c/2kCF8zghu64K/UCRghXlMJHEXwrr392pAYlqy
            qH9iRJDFrUItgrGG6ZKbIgd+YurdnmO+hL4eRCAcoFjCN+i6RhZHo+27SoiFXmre
            aOgUYYoEqOwUgPYF3EAJvsJ/Bry/oqdP6KsVdMHIV1TWsXYqlhPv0elTvg52C8uu
            O+JoxkS2W4hcy2YP8e/cIMjWckie5xcscEUDURi4+vU+loCFZUPmmnZmAfdRRgtR
            HOwGZEw5aRrw0OvRK//ZyyfMHkqeYSWR24cm4HdJS7TNDyaC4YAekE1fxkItp8Lq
            W36RpY9pTkMzwogjHrbwInHoWamRBbxbTy+Ov8TTxT8poDpYNPcNmPUBg5rWJTrU
            aAEJAhBuQUyWSJM17Az/VMTQPLk3ViH+bQ198de1gSsPJmuf5vlU0woLVzWpgSS6
            HI5g3fZGaG/nXD58mHI3bJlneHa/uu7RbutxiLuxPXfU/jg8zulEK5OdgXw2DCxS
            xhdnVwLS6Fxz
            =BYsT
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|password|secret_key|username|host|hosts|user|from)$
    version: 3.9.4
