# --------------------
# Ghostfolio
#   - Repo:           https://github.com/ghostfolio/ghostfolio
#   - Docs:           https://ghostfol.io/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/ghostfolio/ghostfolio
    tag: 3.0.1
    pullPolicy: Always
ports:
    - containerPort: 3333
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:kCpTG1xMJfcFHA3NHibmv/wKbg0MVYK3/I2DezQbeJfhNA11BoFOVFmwM5eB8GQs8R6EcIl4PK2FyTXBP0Bdnw==,iv:4HT84FDrYS+KJa25H2BBxd3mv0ad1DAL3GNdLP2Zc4k=,tag:B9N6jP2lg4S0GKpjMEQw0A==,type:str]
        JWT_SECRET_KEY: ENC[AES256_GCM,data:mSOHep/CtJYn1/lyEW43kM9l6D+AviFALplD6oiqqmGmK3LAnQde1SjSExBcZ0jCKqrd36NX6G0EYdcn4kLI7Q==,iv:c0re4mL5nKbH1LvmJUJu1FYiLYighSqfZguLoJ1kWRs=,tag:ijh5kRrCSfwXUIdTZxUIcg==,type:str]
        DATABASE_URL: ENC[AES256_GCM,data:wuMAWq6pGvIrPDqgTDyUWuqmKzBJtX69TFKDaF/HP7eJ3nZMRQPi8zK/W26gAabePZLb1wpHiNX/6SqQvkGK9ow3q9oybIo67L/koBi6o1eAKxrN6RmGIrSHO5N/p7dbYxsCUmhG,iv:5+5RjnL0cRo2sqo6WY2eerbKy44Eq0pcQuBX4PRnb0s=,tag:7mONlSjM31ZjTYoc7ABhUQ==,type:str]
configmap:
    mountEnv: true
    data:
        NODE_ENV: production
        BASE_CURRENCY: GBP
        HOST: 0.0.0.0
        PORT: "3333"
        REDIS_HOST: redis.databases
        REDIS_PORT: "6379"
volumeMounts: {}
# - name: config
#   mountPath: "/config"
#   readOnly: true
volumes: {}
# - name: config
#   projected:
#     sources:
#     - configMap:
#         name: authelia-config
#         items:
#         - key: "configuration.yml"
#           path: "configuration.yml"
# - name: config
#   mountPvc: yes
pvc: {}
# storageClassName: longhorn
# accessModes:
# - ReadWriteOnce
# resources:
#   requests:
#     storage: 2Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    annotations: {}
    # nginx.ingress.kubernetes.io/client-max-body-size: "0"
    # nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: stocks-cert
    #    hosts:
    #      - chart-example.local
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: stocks.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
sops:
    lastmodified: "2026-04-13T20:28:42Z"
    mac: ENC[AES256_GCM,data:Xk6tCoYewMWvtE77BC6wQCX8HmlmxNrJlhTJ+xeEON3YpC/G0EOF59pz8DW+yDGSpx0458Zaienkk0wEzMwRDrbEgVc98baSYAH9cB6iV2c6c+Y0fFaaj8Ga6APHjbEsbwhKAg5bW2J7eRHvsM9+qaMiKrVm4sy0X5h3DPPTL38=,iv:j6d90vQngiLCKg6T6YlJMKbRuMRcgSHhM/IPN5EZdSE=,tag:E+N2X08+pXlYsqvX89GeJA==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//RbQLNqDca4IpXPGg5Y8yubwFyedqo4vaudHZckO/WYvp
            opNkaVoEQPr2UaMeZsT8ryFe1BKfqLQSxgxME222RQfbfnHGpA5SpVSYyG66FSLe
            /ravVGLOBaHzs1ZKirOPfuicHnyUiGn/SjWuGEgLW+LEp5mHr7NfDLxpdOfeqc2x
            fUOSBKbFAMNtfIOMspkcMexqIKgR+DQOzppt+Xu2fsc00mbIHinveMLR2tTez+uB
            S0RTCCf+9YjeDktGGGo+IXwEYRHr3oec6In06acXbKyIVZhv5XVrvrW77DeA1O2i
            yCVRi9AxcARrbmu+N60FOwyp8OCI/am5u9S72BVD++bBeApciwC5t2BKpXzCFX+4
            fP/ZiglkJkGsKzSL2oOH2sZrYWWGFEKEgLGav6OqnJE720CR/o7G6ZF9E3je4Y7b
            Mg0LysGUtTEStiM+N0td6ju8EkIzDX2hkFSW5u6cHlOrGMcQGmFfAIGO1BiildP8
            Zo2bVA0xM+IMytcegDNOgqPhpb3eNCSF5RAEa/wmWJLdi3AUx/ZEG64FVcZhfFXf
            mox/hEj6+XULpB1womhx0Olz3vRTyzvkE2I+JlE4i3L7fIC22jx4qqVvgOpJIS7N
            cQMWJOHgrsHfimp2uGtdha+Quh6liCXz+XvBGH3rSB5qYDXkvO1gCWRSkRNpj5DU
            aAEJAhCinh+KMxDmzWR75Y8Sfuw6QonaK0e7XWptzq6rXshMaf1KMIaXqNBTni+5
            taWO2XGHBgTbZbAZ1bQ/yqfRRJsBuExk0a65Yy+AoXX66rpQj+yFhjTTYHmTelsA
            k97aoO0Mpj1L
            =2VQ3
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
