# --------------------
# Cloudflare DDNS (PT)
#   - Repo:           https://github.com/hotio/cloudflareddns
#   - Docs:           https://github.com/hotio/cloudflareddns
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/cronjob/values.yaml
# --------------------
secret:
    stringData:
        CF_APITOKEN: ENC[AES256_GCM,data:nzpaesivhqLbcnLo/Ia79GKAUeAuoqIe0gK/z//AWsZXfjyJ5I8ZuA==,iv:A2MGKRr5ovPqsPuqJ3vCT7ObitPY6ZVPF1qLUeszGh4=,tag:tRj/jdHJfsOOKCDU24qtfw==,type:str]
        CF_ZONES: ENC[AES256_GCM,data:Im3ICTio+rR1hyRBPM9M/pNtNQIutTDB4iZ+/dIrsEw=,iv:m5R0o7FBJdX32eg2fFm0dymhv34I4wEOHbHUsTTAF9g=,tag:T8G9fcXD5jCm1mygdnye+g==,type:str]
configmap:
    data:
        CF_HOSTS: ENC[AES256_GCM,data:jEWpFPLGXtnClw9Gr5cpH107vXyHPSZZsxU=,iv:qC+CFIIFUArhwEVLqaSPNua0vBtCqW/eo1I4IMY3lsM=,tag:MG8SVubXfz1Dfo6ad+BBjA==,type:str]
        CF_RECORDTYPES: ENC[AES256_GCM,data:AQ==,iv:gkJDrW19fQOS/PUKvow7UsN7ixeppdDuQFH7oUXovPc=,tag:0MzZn61cN/w0vbCVLqWuMA==,type:str]
        LOG_LEVEL: ENC[AES256_GCM,data:Sw==,iv:VqqNwh8coscGDcwihWRKQM/9Gxl+0/Oadhio6Nc8RV0=,tag:gtJLLtZBx0PYmpZ7ZOtO1Q==,type:int]
        INTERVAL: ENC[AES256_GCM,data:8w==,iv:HeSFAxrfHvFF21Djlr2wtTR3BgpvK19x47AC4RTks8Y=,tag:IUaBuwa3iuIqtdQEukUZ9Q==,type:int]
        DETECTION_MODE: ENC[AES256_GCM,data:4tK7OnOEnmjnyJ/bc8C0xWh7//Qj,iv:/O9g5/1gC/4N6TVYprwh0/p3iv0q1C4obAwD7SinSA4=,tag:g9TPG3w8G+JxAAy/DvidgQ==,type:str]
        APPRISE: ENC[AES256_GCM,data:bc3WuRjYGiDHEr34zcilUvp7qiw1KNc4G61YJB1r,iv:DCcORuoxFXjx9XEDk71mm7lSn1mxOnGYYiQUbFWCDOo=,tag:2iR0bd0l2XvC6nxyWNWj3Q==,type:str]
cronjobs:
    - name: cloudflare-ddns-pt
      schedule: '*/15 * * * *'
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      # suspend: true
      restartPolicy: Never
      image:
        repository: ghcr.io/hotio/cloudflareddns
        digest: sha256:dbdb3f7854ce46ec52abd392920cd74a02b7d0b95543f16c94108cb864d6cec3
      nodeSelector:
        kubernetes.io/hostname: k3s-m2
sops:
    lastmodified: "2026-05-09T18:49:37Z"
    mac: ENC[AES256_GCM,data:YA9mIde9apWZXm2UyUVbfpIPG5Z3Jr4V0iida88uDLBwzWPv61nOnaaONNMc0+k/hevQbwSrhgf2WmNL47uSTswWHPtCRiETlxkuNwcxzjRjFMsXv0PYvW14tOS067B0d8pRkjOv9iGmRVg9pXw0wMWUXT2lBCoY05a/Rwxcvio=,iv:P9IaA3wkuzwErto5bZkYXMX74qDOhTd5pjYcg6UUbA8=,tag:dkWoK03a4gZrjVjNnN00DQ==,type:str]
    pgp:
        - created_at: "2026-05-09T18:49:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAoGMS4Eum/eHQfh8WajjLt3YnwT8zHVPELMRmWRms1ULG
            73nVJCaZqRv+BEyYM9VVmexOLpOV3UpaVQxhRuvzgFrO/X4EYqaeneVKHBUUtQ0r
            isugfB4VAsSBijxzq61uauh3n0ZQFbfHf2C4uJUYGctQiXCvrKgVlB4u9PQ04ivq
            A1RGyxUn0LOuXOyBWlifldM76WB9fO1dxJg6Q902gAprRyd1Vx04JyE/rwKiRemo
            MDUjcdHKXK+ILcftdDx4Jh4AINm1lAtscCE/GHYpZhWYWjK83nXtUMEIOb/+Fhfv
            bD6amx0I9RB4Pcx8w+XtFCBBtmgMGwPiy0/xJ8TY/8sGzjzX7jS/NXpjhJ2lsG8f
            IyflFKxVxj0RYJOivT3Zd8SyybUXizmeWLA0nScPwPSAM1+OSwP2NaRsdjwplNk3
            std2I2yxOlB4kmKRMpC4ZCsaJUEjfCgWuSjGAJgOyjWbpvdIKQR2ZI3nMyldX01Y
            UcK152y3sCJkie+y+ZAHThZs1lH15jNjvDSJTdUIsdCTRcGSsJnXQ8dLGrSppQc3
            ZwFQojswLviVt6sHS32B0BY/+JgGLdmkbGOA5HwFqtRboB20SH06BJgC+VHk7Ra0
            VHM+i4+W/Cpv/N/pgZhkWr/N4FAvLLpfV1HLmTNPFtlGGKIVznbD1/RoqgL8L1zU
            aAEJAhDq2ftQEHxsH9FXTdGPNnoobH2HVRvkPpEQ0MvsK/VhxS+FENZuemtvXV9U
            hpPdMscn3vlVcwcPzbJEl35h7W03wV0a6L9/ljp9mT6q7xik3eW0loAYtrLxWsZ+
            6NivO9fI3f0n
            =wc+7
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|secret|loadBalancerIP|nginx.ingress.kubernetes.io/auth-signin)$
    mac_only_encrypted: true
    version: 3.12.2
