# --------------------
# Cloudflare DDNS (PT)
#   - Repo:           https://github.com/hotio/cloudflareddns
#   - Docs:           https://github.com/hotio/cloudflareddns
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/cronjob/values.yaml
# --------------------
secret:
    stringData:
        CF_APITOKEN: ENC[AES256_GCM,data:HJp6TYmuI4V9edVwKQH6o21PySdDTlu+lfI5XernTJtBXXUih/jeqw==,iv:xX33d4R6b+PkQc5uyueQIDvwKKHBKv3S4KelvmZyY+w=,tag:0Z5urJDeQHPXI7XBBACVzA==,type:str]
        CF_ZONES: ENC[AES256_GCM,data:yC1YYZp1hvWYW6zkO+DoXALwbwGH+ayiAd5Zv1DP5Is=,iv:swHNlxqh1BXDTlYpQeC0U7Yx7foMqlarLKTW/r2evhw=,tag:rpx+TVP1/eEYxHfuCPc+QA==,type:str]
configmap:
    data:
        CF_HOSTS: pt.ip.{{ .Values.domain }}
        CF_RECORDTYPES: A
        LOG_LEVEL: 3
        INTERVAL: 0
        DETECTION_MODE: dig-whoami.cloudflare
        APPRISE: ntfy://ntfy.monitoring/homelab
cronjobs:
    - name: cloudflare-ddns-pt
      schedule: '*/15 * * * *'
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      # suspend: true
      restartPolicy: Never
      image:
        repository: ghcr.io/hotio/cloudflareddns
        tag: 3.1.0
      nodeSelector:
        kubernetes.io/hostname: k3s-m2
sops:
    lastmodified: "2026-04-13T20:28:43Z"
    mac: ENC[AES256_GCM,data:zXa5q5ORvr7Fc0rn3uvDcaAimIHV0gGPUjSuPswRj9AqHXv/wOb9LYa/12EBRTz+SibR3KrqN1P3SiveaV1s+2I2x99VH6Lg2vr3orRa9BgsukFWZf8kMZsINRWakrhU5+wmRxlZEwDO6maPa+ixBzi3EEbRNnVCmhLm/3E2ETE=,iv:f42bNMOHIF2aRHYpHTgtL0k1syFdF7547mT3/HpqUuw=,tag:u11ZeXmJVKsr1o5Tt9rbwg==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//c983JO/fuVtVNWVG/RkMe3rtYw/ejzQBVnkPw1uXVvgj
            1VPDR7jzdiex03D56tWtxN3dTE7RpZX8738OJ7BXSq2Dr9qk/gQanviI3L8iyvNm
            jOKZuUjElBLrLkweqtaNwdsp+t7oEZtfT/8N9IeWHXhEQgBoYFfrnjJ65vkiZhIq
            5L4X6wcZxAolVfH7QYq+G+t0n+1LuBITIwd+vjEANmMsQSBZV24s7ayuoEhK6g0q
            RaB/b0tlX5N20FCcdL3HOn8HPipG54HxLlIXzvUiyxUgMVApHEgmRqfa6wxtXAtd
            +9WdVMFuhCDHs75M2igFzlpk0fNAV7WC+0FUqQLjEW5nZb/FnL+mHi7qJk0w9xok
            U/ZEOfC9frh/SOYmCR55XLluVMMLfe0TxiaqGSeiYHecEuQtx3J8IlVsQJ28h6Oj
            s5GyIdyRpxliWcm6XX/myKAcOgE72n2/k7vV2IxmeWpz+ITU9UMDB40+isTY7yCQ
            PxKQuAChGCqO9s4kGKaRxxUpmyWS25rqv3EQJAwaE5GqFfCyXUkgj7VVSZqjSrvs
            9npoJ6u4dwlwqpfJTCkWTCMHlsjAkb9DKrKznhqwcbbPnJfxhAKQveQJhn4cDvXS
            5r4TJQopz7XgfTfirk97h2a256ytKIJxPrSJZMiS3SaFrmIhilg4WSfe+XA9uvbU
            aAEJAhAq4nZ1Ty+PGheUGWi1kVpoz7DNRInQFzo/Yh+ivMkUHdToK0uHYdtIl9Qt
            yaUiSiHgqTqy3k8htkiaUK7H/8fZ+7hgCoOSqNP9qh/MBN3zOgULbH41AiL3yRX0
            g9Y1KN1PUzGO
            =osKh
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
