#ENC[AES256_GCM,data:ug+ncuCqQuhylJWWOHKLHYB3CGxYyj1sRbfHEdDg6GvZC0/3DRes+BDq8of1CObSj2BZ847wBAlcmXx4/uuBh9qCR+qx/Pkz,iv:T/Kw/3o0f8ZM2Ee3QJSfefvsuEJujGgxb2SOBgIuuu8=,tag:jWT4LqcI4+cIvUUdLtlJnA==,type:comment]
VPN_PASS: ENC[AES256_GCM,data:OnsU5/5UAuXIAsld4WhsWW/BO0vG+G4Y,iv:BPtNWdzrhpLKbGEmmlRdC8+2x/LllqvmqVSKl1zqP7U=,tag:gUzC9pAkCKNuM2+CbJAseA==,type:str]
LAN_NETWORK: ENC[AES256_GCM,data:0R6nfydqidkdvFuqUZMpXy4zsSOkmr+ZYsHwu7pUd/AMUiojpvA=,iv:9l3Mpkx8vpN0eiYS4E2bMtGM7hfgVlMATbrkMUqA+kM=,tag:brPA/RicHARN21tPnweiqw==,type:str]
SOCKS_PASS: ENC[AES256_GCM,data:nLc7m+M=,iv:fhl/ObSbjPvtPnko0YAEiQryYLE3zDRqD/lUlnV1yvw=,tag:mnQEyFaNJjJk+ntr8V4+iw==,type:str]
VPN_USER: ENC[AES256_GCM,data:dpAiNFc66UVKP+mzeumWSWZFyOiHaSh+,iv:fvHsyVRTwOkWX6Qwqi7EehyC9HbA405Vm+rmLilB3Kw=,tag:3wpAk4YbWv1/ZS7bxR+7UQ==,type:str]
SOCKS_USER: ENC[AES256_GCM,data:0wsKh3c=,iv:vpwzbzft9/Z47bEU/az1XaTuJQlM+wxXJ1UJppbdOk8=,tag:sTz6XKEaQr4VtE+glRpuuw==,type:str]
DOMAIN: ENC[AES256_GCM,data:P4w3RNDtW0F845nb/Q==,iv:1l6eIZrKu1eORqNPmuhagWtwAOw8h5OWhi+VqR8Y6Ic=,tag:N7UDxgH0gdDuUTX0JHR6QQ==,type:str]
LOCAL_URL: ENC[AES256_GCM,data:e887RbEaUvExqgwvGTfYs709Djo1ULI=,iv:XX+b9NS3YGGsSU7P2NQ+supBT2j1YWNeVysgdBcrII0=,tag:1pNpeijDc4O8TucdOFYNCg==,type:str]
KOMETA_PLEX_TOKEN: null
sops:
    lastmodified: "2026-08-20T13:09:36Z"
    mac: ENC[AES256_GCM,data:SwMB7uKI+UXH5kzA8r3prsJb7F7sFagIrCbCQXBNn28lcugCE1SDouzv5h0aLTVRn/9xb9GqTUMN27/TZkSDhIiaLQ7mzA2B/7W/A5M95uLRVLBZqFT2IYQgHsbXLiSfYdViN0W9r2QwFNLtzfanczQ5PoyeYDkFCUKnRUeBr8o=,iv:Y9gQR8s62iFJ9B9KLKsxuq3iiTgzjlx6aYgLVoUOwoM=,tag:UE4grb1W1NcLz3FMICcl1w==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:09:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//UsRplOH2q4DS6v19uO4F14+W9Arb+KiL8s+z3bGV1YiO
            Hj07Tbti0ef4b+Cf1HSug2uswAbyZBjUr54HFqFH4S1C44yZ1eugOkyyiZCl2Nkm
            5Ok2fXg+F0W+LkuufybKRw7fcikl9wDBpaEAtwfG5pPNpVJhGJXoet6CJ9bVcpHs
            q86epskk12mFh6oyXdhGsGGNRrHhn0RdGZrCNoYbIsVVM/B1kNyX/9pcgHPPSM6E
            X56RqalsjzmVWswRwKLxkm2eOEU2oWUiIzbqGvVvcE8Ng9FpXIMyQF8v+GIt86bx
            21PG/WnqiyQEimYe+misO2qmBQukaRzVhKxP+qxoTePvV69+Jl7fH18rG83LVPYj
            PTVcAAegSeo4M8su+F0XavXvgrlShfjwRkqBpIAdR1k+Sc81zRrM4Tg/G1paK6rp
            qmAhP0UjVkP8LxK1PSu4FmshX3YLZ7oVSVMrcHTgG2EdCl/iyOBAYqFvXz6MFRM8
            4V+JoNUVxkCRZojw54KagAStG9v/hnof56X9Q+R7d5F8DCZmpc6NQYT1JH2xYt3r
            C4vzvM0cxI0n2GcykkhJmLv58mswIOycEoUhw257Wk4nNyKh7FQKpmLDJ4T37vl1
            hwICEKkeA9skDsU7bQyS0hxrOlae94TkjktOffDfS8HbUacclDpW4hGUcvwEyN7U
            aAEJAhB2nldb5WR10bitVKP7aLhLU7viQ5VtrIFI1k0f7cmt3FTEHCx/KfHRGYmP
            RuhdwJPXCFhobkZMUe4u4y2aLsaTufdziK6u99RBKklreFlPZurOmUUoXSZdckeb
            W3mGT3Qy3bn2
            =DxLN
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
