#ENC[AES256_GCM,data:8O2e8bvcDDJ8FnQVgFaDdJ94mohsJ0kGNt2MDCIA27rW20w2vXghi8Bvz2PIt7GiLKrpGZ35UtTCh+jBqZ/TzvLsRMr6s2GQ,iv:safxqT4cddnEMmbE361dUEGiQu3x2R1u2DuM+hYwEEQ=,tag:431+0xeYgnN4PDQnID9otQ==,type:comment]
OAUTHLIB_RELAX_TOKEN_SCOPE: ENC[AES256_GCM,data:OQ==,iv:SX6cbM+BLHiC+QpUlKUU5WZ5YjIzfbyrV75s/HgoM+Q=,tag:yRbTPUJgWQcLu1I3Nj7qlQ==,type:int]
DOMAIN: ENC[AES256_GCM,data:mUUWLtQfA6CecEkIPA==,iv:J9M2W2hQQorf4TYuc92V8DDrAK9cfqge0itZadZoskw=,tag:jm9iPnAdQbMkZbsRXY9j1w==,type:str]
sops:
    lastmodified: "2026-08-20T13:13:34Z"
    mac: ENC[AES256_GCM,data:91qljtoRUdDLg8p09/h/bzvQOs7pfFjAvQAc5uQo1SiZ7EP07G7HSkiZl+f8hqhunllHtB64aygpOPW0L7wg7fbxUtgVXQmc1HI0BPY/u6mrNDcZ85haGn1mTMQat/oGjqdoMHNUS0dgXu1jckJZPxK+Pp2BDaU3goLdsZxe1DE=,iv:ZzNslf10BUODeU4whLzGgdydVdb1Yj9rTDvxj/QBpqw=,tag:b038u9SZkJLSuE3F1yrN6Q==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAnTgsebdqgJUZRXnop5NoLQbP6+rlP4e7Ib9NgLALveXB
            xBBX8SOeHwZ6qIitdAPqVBDF5WEcVEyEduOp8AIw+33YXh9DfBPE16nQqNl814J6
            ka+1CB0HeJE9Ep5f3BQO5H/FWxrUQzlLHfPGKQRkckCV9eYuwx0B9yTaYGcGb/dj
            MCmBgrycqtyEKImidLfHOH94ZLOyR7pkLrXlxCIm0Z2Y0PXEi7VpgTkDGz54jhA6
            n8N36yggpNg9H1v5+/1WqTrrCxUPLwGuJ8LumCyWjzVy8oD4o10JzkBM6TIazZMI
            SqEOXikb4A3OobnV4tTBulgQXAEYLC4aW/BVc7mPGB2Ie1N+MrNTEFksgjSmq7tx
            xqcuIwWq1bZg+WV94q4eBNFzCVkXNx9SKMySpTmAGH0x4YiF9ip+kEWMkmHZFFNy
            pOOvlbO/XXWlEZczVf6edGCRElPLwDab+3OBEZeww8L7WsWIFnZ9y1M06/t1cxmj
            1Q2X5dk6XZHN36g+Yi3e0Ih6F+WZt7uE9ENrdupzuLIJHskdbbY3C0RdIsUFdkep
            LGZ3GfqzxHymoPcO4f26XyWPOMHAVRgHIuQCPfly1qP6+J0pjsZd6N1Khuf/vCeH
            z1sMQurUPfgApMb0vsmg150DemLi5N2t1fU0qliv5hJEXAEhbwkr6QYAbQeNCErU
            aAEJAhAgCtB7BrQUrhuDDc34GpZJjsZr5IudWjCkQHIWL5SJMbicGkGbvACnnxu6
            gd9KhJVYwBX2ecDLdmSPWPV7LBEEkIDTudkBaV0rid7i6hgWN1zBm9Bmj2/JeY9+
            GpzZ574K3g0s
            =Xi/d
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
