---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:afonsoc12/homelab.git
    targetRevision: HEAD
    path: kubernetes/charts/homelab-svc
    helm:
      valueFiles:
        - secrets://../../apps/values.sops.yaml
        - ../../apps/automation/home-assistant/values.yaml
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: automation
