labels: {}
secret:
    stringData:
        INFLUXDB_V2_BUCKET: ENC[AES256_GCM,data:+NPKhKPndw==,iv:p6jf3+SJXfgXkzmut904z4abh4PpW5QDZdeiOaHEN4E=,tag:NMGtUHHp8E7S1YIVF0ny6Q==,type:str]
        INFLUXDB_V2_ORG: ENC[AES256_GCM,data:owE39Ydyzw==,iv:htW2AQbuJo+3cY0v3rLLeb4CoPjYHflUPjNPm9e+DUM=,tag:ffjA3pQ4MXsX/msMUbJosg==,type:str]
        INFLUXDB_V2_TOKEN: ENC[AES256_GCM,data:0gEgv1sr7P5glNr2uuFh39COYjYiJnCgx36KObSKnXDCiTLYcMpmwQ6RkKYoAO1eWtWkBaJ/6dUUCMMASaxVEwYdxwR2zNIOzqbPhqt7g2OrsuZ7xP2E+Q==,iv:wxC1D/9wPGzLEJIgu1hENUlqzQodUTvVadAKWtpwxqA=,tag:IT5U6Mh7aL6BRsL5XCCzcw==,type:str]
        INFLUXDB_V2_URL: ENC[AES256_GCM,data:EilQ3IHHNoNSuSrp1zxlRkqhu9rjoxo8RBo7i9/y,iv:GzbN5Qr5B0halzmHEeTzpPLLhDNL8B/o5fUGMikLIs4=,tag:3lMu66QYybkWz+b/6iPPkg==,type:str]
        OCTOPUS_API_KEY: ENC[AES256_GCM,data:SoG68wonxv+QLqchD9RYo42t8RASJ4qfgVfdkR5IOZs=,iv:UrSmMJ0llcTTuNGetpqPm7cMvzjGJJ1oNx0arK8OZYo=,tag:BQzXM07k2Eh2J+j7RbsyiQ==,type:str]
        OCTOPUS_ELECTRICITY_MPAN: ENC[AES256_GCM,data:nFsGqKg/gqxvBfIXwg==,iv:0vmz4b5vbcuGX+xtQLcUM+diyiTgSUJBHAxHq6ePEss=,tag:ciMKbby/1oQ5WsF3D7S1ng==,type:str]
        OCTOPUS_ELECTRICITY_SN: ENC[AES256_GCM,data:bA0FCnmfcD2PpA==,iv:VBCisSdx+dmdRPISXWmrVv3np3dW7IGnKfkvR9MKDWE=,tag:iH6XyyuGB4mvrAfStHfNzg==,type:str]
cronjobs:
    - name: octopus-api-consumer
      schedule: 0 10 * * *
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      # backoffLimit: 0
      image:
        repository: ghcr.io/afonsoc12/octopus-api-consumer
        tag: develop
        pullPolicy: Always
      restartPolicy: Never
      command: []
      args:
        - --period-start=1970-01-01
      ports: []
      #  - containerPort: 80
      #    name: http
      #    protocol: TCP
      #    service: true
      volumeMounts: {}
      # - name: config
      #   mountPath: "/config"
      #   readOnly: true
      volumes: {}
      # - name: config
      #   projected:
      #     sources:
      #     - configMap:
      #         name: authelia-config
      #         items:
      #         - key: "configuration.yml"
      #           path: "configuration.yml"
      livenessProbe: {}
      readinessProbe: {}
      resources:
        limits:
            cpu: 50m
            memory: 64Mi
        requests:
            cpu: 50m
            memory: 64Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-13T10:29:54Z"
    mac: ENC[AES256_GCM,data:jev3xyiySjwtfWiG5ADiUTsiMyYRytj6c83kh9ourQ8QaDfnug2hjxHMjSeB8Dwv2kXaGy8gj6+KJ6vnkgSzuyDwfJ6mO/9HORSKbyKINQBoyWA9gUiGK4U4CBI0vNnLIb7SzFCiLoyq1IhXSbUksGoc8o81gDKcvQBpk83ZTbw=,iv:vz6wJBeHdQCjyw2QcE8Qz5DCWly+cuL+d0+DDCHmipE=,tag:6rh78V0qKftvW0f/iHgH9A==,type:str]
    pgp:
        - created_at: "2024-07-20T15:01:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAovTKlLtkOb61ceSzA3qPhfaP3SOmVVvc3MKvtei379ZL
            i+w9rF8hEtg4OT6g+Xq91bG4uEzbqWpLtDgEjb/IVhPYH8uP2g0hfyYDXC14eBJc
            JmnC/Wvap6ZSNrRLE5vS6PJ0sQGWgumYyIFw0fAOz1HfwUEHxWK7XbGqWMx/LleV
            PjhZBq+bwQ91ZWb6kYqHVJnXV75RYr1Mv8i/QJQENGU8Baj0km5vqSXbONsJFWqL
            8XWHRchoSEWl9wnvKk5pdWuum23JSt9wRVjqvuGvay8qZaZymPrULPn1fRgoWuJm
            U/Sa6oHY3bG/dcS+2xVmT2cL1aXa2ugo9zy+hEqR9cX3cqei+QhMcLITtASE6O9I
            qdiDIWuxKgUiwYVbwK2zIKov0DVO1Ke39le0/uw1ZKWFIIjWMXjP8Hy94MhyRFtq
            wmqyEUJCr/Log87IWsDvwFwKX3MRauJoGRz8FaskM5wqal8XLmCg6wD4xv9SLxk1
            7R9hE0g0rm7lkebIMEYJznYzrVhbw2g3TcDYzsQIDKxQc4rscFDqS5SA1zc5a267
            G7IXae5BpfeoK9p8orIxEIcex2QWcREiRM7RhUaWQdVj3FklLG7Zl89ptUZL8Wcq
            nF9xPxW9V41wahBIWhP3xUJMFE5dD0CvrXfu1z9L0ovbL25s09b3GXytV5wVVTLU
            ZgEJAhBmRpp9oCQAKxkFmW7b9HteynrVj/Rhkg21cjyWxwcHWVswT1gmcGqd3BNo
            Ca0OOo64LGgVwe/c1WoJgdT7wduQXAVf0jSOMRV0VZW2Y3KWFtgvC0qZWddCKtuy
            ksCHIP058Q==
            =ulOd
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    version: 3.9.4
