scrapeConfigs:
    - name: node-exporter-lan-uk
      namespace: monitoring
      metricsPath: /metrics
      staticConfigs:
        - targets:
            - ENC[AES256_GCM,data:WRl6zlFj+a530r78dJ0IvjY2,iv:JazR+r7+8qma+gEWzD5OXB5JYaQWEFatxlaPYYPAvOQ=,tag:A40s9K17NVw4PJEMwTD9Qg==,type:str]
      relabelings:
        - action: replace
          targetLabel: job
          replacement: node-exporter
        - action: replace
          targetLabel: hostname
          replacement: hoarder
        - action: labeldrop
          regex: cluster
sops:
    lastmodified: "2026-04-13T20:28:45Z"
    mac: ENC[AES256_GCM,data:SgOMLFNJz16dAsHNxCZUypuNAlZ405AhRJZIgb2kyYDCN21unRUpBbcpuRb/1CDSIxJpQcKBQwV07tF7x1WxKTPeXw0/ZHXJB6jxib0S4v9TyOicquKt2boc9BrxPFek0cITyEXWDI6bPyfjn0hg7A2zC2wTDO6bGoAtr5OyCMw=,iv:NGODAIfNwLiwGhVWd6ar50hy9x/yJvNKjLPjx4pEEKU=,tag:08vKG+2TAixcvZfnZxDqmg==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAnGEHfqIHHIk6ktyrQhPVJbd87RpOnnDlD9Lx0oog6siU
            lqSeIM5Qte3z6s119luLrEqfgnT9bZdzz5haMa81GLw/6SPhVM/vlfuOoXl7Aqu1
            0cUgN9gk1wGDB+zp6eDwve3RDPV190wEyaLUhCGnm56SPqEO49iCKL3itQ02Nyd/
            ub9kuX6bXsR3eG7eCwx9nkQIGvzYo1U5ZHg+cFUHDcKK2KI5R0qq9MVjoj85lxtT
            XVxUoinmpKtQNThJrEr6ONWHfm97pVGnuDMAzly4/Gvo+R3a096MoJo9mz7XVfZX
            lL9lZ/zlCAdCr/j2kHCetA5MGlyLKdOEhssE2FJgcsuCcL8BWt/Qo0eyUFtFOFDo
            c1k2y0YLB3yLvJUvVYvwlvffG5rsXiBXosJDpWbOH/Enmjj0hh3qIoXagUPuTqzF
            xUt4XBUfnKamKh4K9r+fng4fUO8mYmvEtgpW+AE1/NeqExSSgexsK/kRzHsgm+q0
            VxxHyJE605rNplj8Lr5sdgiUAibIV2Il8nPMlA1acSGPHPTXYX6kO+I0WDE+lkhY
            TlFJlNDBneLLYazhvFVghlRlEpdufa44iD6Y3qPBm2F7jR31gDF8XYkHfJTjGl2i
            OIWFfwVR05rGZRUyKVRG43xqPphIMzDFxddyXf+aIB/GkTr82d9nP5OT5Biu+r7U
            aAEJAhB1b4oHb52+Swgf7sdUNxjtAnGImNNzdHAMX9hIDFSQQiPldwh9Xq08UnTT
            mWIy+bzWOr3Gy7XNFmgROqyCFvFz9B91Sc/v3LnxkJ1WxvarWFyCJNGrsOEFWNQp
            XxaMl1Nuw7Rk
            =k2sd
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(targets)$
    mac_only_encrypted: true
    version: 3.12.2
