# --------------------
# Grafana
#   - Repo:           https://github.com/grafana/grafana
#   - Docs:           https://grafana.com/docs/grafana/
#   - Chart Defaults: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
# --------------------
ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: nginx
    # Values can be templated
    annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.ingress.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:TKfPz5CON462tGz1UkZysChoND0RMzgIoY3E48D/oMk2yBRI96bBZy1RkuoF,iv:rFvhPDaSAtumiuL69gvj2YgVDzgQkTyvhKx3w1AND+w=,tag:6XKNvpDjGTxYhjYH+P40/A==,type:str]
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
    labels: {}
    path: /
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    hosts:
        - ENC[AES256_GCM,data:snGSBY7L2n5sbLzez3tCaarYjE3S9VGOiqTu,iv:KwaB4/FrEM5ihrFpRohAY98ULgcxnd9YTLSlDLmzyj0=,tag:Ym+kjJLZT4VoidP9/u7UZA==,type:str]
    tls:
        - secretName: local-wildcard-cert
persistence:
    type: pvc
    enabled: true
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    size: 1Gi
initChownData:
    ## If false, data ownership will not be reset at startup
    ## This allows the grafana-server to be run with an arbitrary user
    ##
    enabled: true
env:
    GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
grafana.ini:
    paths:
        data: /var/lib/grafana/
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
    analytics:
        check_for_updates: true
    log:
        mode: console
    grafana_net:
        url: https://grafana.net
    server:
        domain: '{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''''{{ end }}'
        ## grafana Authentication can be enabled with the following values on grafana.ini
        # server:
        # The full public facing url you use in browser, used for redirects and emails
        root_url: https://{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}
        # https://grafana.com/docs/grafana/latest/auth/github/#enable-github-in-grafana
        # auth.github:
        #    enabled: false
        #    allow_sign_up: false
        #    scopes: user:email,read:org
        #    auth_url: https://github.com/login/oauth/authorize
        #    token_url: https://github.com/login/oauth/access_token
        #    api_url: https://api.github.com/user
        #    team_ids:
        #    allowed_organizations:
        #    client_id:
        #    client_secret:
    ## LDAP Authentication can be enabled with the following values on grafana.ini
    ## NOTE: Grafana will fail to start if the value for ldap.toml is invalid
    # auth.ldap:
    #   enabled: true
    #   allow_sign_up: true
    #   config_file: /etc/grafana/ldap.toml
## Grafana's LDAP configuration
## Templated by the template in _helpers.tpl
## NOTE: To enable the grafana.ini must be configured with auth.ldap.enabled
## ref: http://docs.grafana.org/installation/configuration/#auth-ldap
## ref: http://docs.grafana.org/installation/ldap/#configuration
ldap:
    enabled: false
    # `existingSecret` is a reference to an existing secret containing the ldap configuration
    # for Grafana in a key `ldap-toml`.
    existingSecret: ""
    # `config` is the content of `ldap.toml` that will be stored in the created secret
    config: ""
    # config: |-
    #   verbose_logging = true
#   [[servers]]
#   host = "my-ldap-server"
#   port = 636
#   use_ssl = true
#   start_tls = false
#   ssl_skip_verify = false
#   bind_dn = "uid=%s,ou=users,dc=myorg,dc=com"
## Grafana's SMTP configuration
## NOTE: To enable, grafana.ini must be configured with smtp.enabled
## ref: http://docs.grafana.org/installation/configuration/#smtp
smtp:
    # `existingSecret` is a reference to an existing secret containing the smtp configuration
    # for Grafana.
    existingSecret: ""
    userKey: user
    passwordKey: password
sops:
    lastmodified: "2026-04-19T00:58:06Z"
    mac: ENC[AES256_GCM,data:967K2/iQVokY1SM6ZfgDaP0YwFNwuVenVCxQUWRgQRh+xd/sRRi8XqYYG5DWwlchdKCUoDAZcKrfTMY/Zr9l31VgH5CW72lD2wqBYkaCcIa8o/jdJk3IqFnjtJJ7+iK/DGPgipAL1tfwCzkgwN3mfJZFvbgrD0XeLA1YXF23wLY=,iv:qeMhW/Drdco07pTp2zUp+IYy+nfrS4EGhLadYeiYcqI=,tag:CwPo5PFFow7GBuA2cJBJPQ==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//fwlnGBt9nLMybuk62vg04R3GV6AFeX9Dz4mo+H3aG/t2
            ItOX29M3h+OXcnGvmnFuDo0jnCtb+AGjUBvJ8bvI+16MurqsWG4n0iOQ7FpAaxkt
            qC0whJpEBPNF+s60CAGJWdAhmhFxz42FyrQm/h7Bzre54PHbjxZSWCIiqjeWKdML
            iIl/eNYggPCyjBfI512BtLAriGMusTI07JTb+by17Xq5GzQ7wookkQJ4yGeYCPGO
            gFzBbA48KZB7lVgzSBoQ0i27bmCdaQ4N6ZxIpTtT0LLJMJ7JhJmnCj+aEsCG81AM
            rRovbOPs/PM8UCTgngcZXgmH551EKLdkPzt0DFCQiu2pbuSsQ5y415s0+HXvPgPG
            Ls/avfvQOx9UwLKd3hyAX6pAUbWUKVimdFstGrMlfyTm5IKMDYRg7mYAk69BDtio
            NEvyXpJ5ssk7shq6ry9IJ44VsuTd9LQQs3rk48Y3UGKukoiTI6HKZyzpccZsHByJ
            09Wqd8CBkPhnc7ZNR2dQ0DGBJ1BPyWiy0Df2eaxYQ5/biYKeh70iUg/t0xtgLDSE
            tSVLhJVUhL3KSqHwfEnLRqgC3V4xPRzVgpXlqGz/+ErWP9bSNVKGYHoJ4fqpGO2H
            X75CkZBB3gJZ7bKfCFTtSOYHqcBBYfVXpfZox5vPHqowjcCi+Le+IwlIo4kC2yPU
            aAEJAhButpMr5P/aYTXIJ7IYQcxNq+hp1OfJRwUyNNzVH7pkcL9hsEMjq5GOt5cJ
            +6+AzIn93/3GgpEuc57T7+dVQi2Q7rGeUmrx0oy9yNYbNEmJ0NZ/5np3mthPE8Ik
            Dx/PRZDXNtB/
            =k2tK
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(nginx.ingress.kubernetes.io/auth-signin|hosts)$
    mac_only_encrypted: true
    version: 3.12.2
