ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: nginx
    # Values can be templated
    annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.ingress.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:SGi03gMcIIwJzBDQWbLZZHVH5zljenv3eEvCiVnPMLjl+x96xUhA0NfZCWTw,iv:drhsOshCmj1gO7rHFGJAZXAjfdsiJ7JOT3FBiKBX3WE=,tag:pAGTAt4lO3YRqmoOjW5ZCA==,type:str]
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
    labels: {}
    path: /
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    hosts:
        - ENC[AES256_GCM,data:WYGTIId7oe3I9vIAbZU8SqgaMQ6ZBdQ5FqDI,iv:H8DbErIwIYVY0Nof2baWHV5ZZM2HOSix+Vv1uSUfCOs=,tag:1p/u8a8q+Mz+RYlygvOECg==,type:str]
    tls:
        - secretName: local-wildcard-cert
persistence:
    type: pvc
    enabled: true
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    size: 1Gi
initChownData:
    ## If false, data ownership will not be reset at startup
    ## This allows the grafana-server to be run with an arbitrary user
    ##
    enabled: true
    ## initChownData container image
    ##
    image:
        repository: busybox
        tag: 1.31.1
        sha: ""
        pullPolicy: IfNotPresent
env:
    GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
grafana.ini:
    paths:
        data: /var/lib/grafana/
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
    analytics:
        check_for_updates: true
    log:
        mode: console
    grafana_net:
        url: https://grafana.net
    server:
        domain: '{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''''{{ end }}'
        ## grafana Authentication can be enabled with the following values on grafana.ini
        # server:
        # The full public facing url you use in browser, used for redirects and emails
        root_url: https://{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}
        # https://grafana.com/docs/grafana/latest/auth/github/#enable-github-in-grafana
        # auth.github:
        #    enabled: false
        #    allow_sign_up: false
        #    scopes: user:email,read:org
        #    auth_url: https://github.com/login/oauth/authorize
        #    token_url: https://github.com/login/oauth/access_token
        #    api_url: https://api.github.com/user
        #    team_ids:
        #    allowed_organizations:
        #    client_id:
        #    client_secret:
    ## LDAP Authentication can be enabled with the following values on grafana.ini
    ## NOTE: Grafana will fail to start if the value for ldap.toml is invalid
    # auth.ldap:
    #   enabled: true
    #   allow_sign_up: true
    #   config_file: /etc/grafana/ldap.toml
## Grafana's LDAP configuration
## Templated by the template in _helpers.tpl
## NOTE: To enable the grafana.ini must be configured with auth.ldap.enabled
## ref: http://docs.grafana.org/installation/configuration/#auth-ldap
## ref: http://docs.grafana.org/installation/ldap/#configuration
ldap:
    enabled: false
    # `existingSecret` is a reference to an existing secret containing the ldap configuration
    # for Grafana in a key `ldap-toml`.
    existingSecret: ""
    # `config` is the content of `ldap.toml` that will be stored in the created secret
    config: ""
    # config: |-
    #   verbose_logging = true
#   [[servers]]
#   host = "my-ldap-server"
#   port = 636
#   use_ssl = true
#   start_tls = false
#   ssl_skip_verify = false
#   bind_dn = "uid=%s,ou=users,dc=myorg,dc=com"
## Grafana's SMTP configuration
## NOTE: To enable, grafana.ini must be configured with smtp.enabled
## ref: http://docs.grafana.org/installation/configuration/#smtp
smtp:
    # `existingSecret` is a reference to an existing secret containing the smtp configuration
    # for Grafana.
    existingSecret: ""
    userKey: user
    passwordKey: password
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-24T14:11:33Z"
    mac: ENC[AES256_GCM,data:8Y8jzgL9hmGM1H9KPH0OF1Op+3NqxKM8JatdA/euw3SwDPXTuSwkMjmxyd5ce9/eF1K0Y3/qoyTqcWQDQ+oQ3gwEmb3mPG0cMK4dC3ZLkzwYRwe1Q/v/MmLPUFZwDt6cp7lOqMJ48Kr9NXVsRcOMaDA4nH6C3Phw/d+gSqfyZ6w=,iv:k+Fcsa0Meha6CqiY3+0JokDbhaGgMa6w6kT9bvboKHo=,tag:3fctbOdwgf/LWUeb9TJ5zA==,type:str]
    pgp:
        - created_at: "2024-07-20T19:07:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+Kxh5m9hwkvL4/YdRifIUKOrG1YexCKss8M0RWG8vW+QJ
            vj+L+E2hPyGfOw+bJfNml1qH5AD3fUqRtycyXeaeJVwzhu7eID021gpNGiZ18o2c
            PF/xoxlQMf8Gf9zSHzDGPBI6+axkaufUgJgWpuWyZd1P5gZ4wuHOU26mT7wD7IuH
            Z0CQShUw5bCObCyPCkEpSrJXimjnFjIp6ctq8eASHIvNFz0yfeE6B+d8aBilu2Pf
            SsaZNFkLdmzl4StcwoEe4wh1mwvUhEPqRcvsiL3637fdKov2Zxt5SOCsrlooUvYn
            rTSICJPfmN7MS7VnMy/UmZXbnJA0go+g9R8BtaUX6rH1/U5mJfWfUg76uy0Vv15c
            Zd2XRf6jw1gyZnJlhnWqpjEvRK0PKHltLo6G1g5+VR1U+obeSXIoLtI/kT5x/wpz
            kzyiT+lCQEIT4RaQXG36XBnL7OLRX7gdo+PyUUb6KsqOU870r7yKjV/uqcUijse5
            DqS4GTulFTBlqJP+FRKc/9cP5HKfQ0+2SKFpdJzHnMYKhFqHw0i8ZTI2aZqsTOhn
            8s7piyPDk58b8qBf/b9MMGdljBZSvupKbxLfIqNk5Acw/QbCHiuELHp7RAYxJ71s
            t9GOBf1VvusT8nbK4nbb1rwelFZRCkYtKBEvsOVP2h4RQv+g7wT7UuxrRqaXemrU
            aAEJAhBQ5VaUvVhEr4cI/i3A8Qg8usW2HNUcwhQ8OA0syEDgyBh21LBx8bHGyJCb
            sm/5PSooQT1SOzcjkiZJdp9kjqeaXkmG9oeGSuHQ4tmf+nLHPVMWODTWJDeuaj+P
            yTVzcQJqRoBH
            =3TUM
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(nginx.ingress.kubernetes.io/auth-signin|hosts)$
    version: 3.9.0
