longhornUI:
    # -- Replica count for Longhorn UI.
    replicas: 1
ingress:
    enabled: true
    ingressClassName: nginx
    host: ENC[AES256_GCM,data:ReDEo44aPWe+A3y8Os+lhRQsFAGnsK0YQ03gAg==,iv:qqSnaUo/8ISG8gWZIc7MkPt+23sD78tV8F7/eivZ3dM=,tag:vY841YR4VypLYvlkxy/XWQ==,type:str]
    tls: true
    tlsSecret: local-wildcard-cert
    path: /
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 10000m
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.ingress.svc.cluster.local/api/authz/auth-request
        nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:HF1kdNgTTjh8YJx/GjeHbKogW+0sSf7L8rapa1yt/O6jbblhRswg5bfUlNoP,iv:PxyHPGv5P/Ntm4sswr7Ek+JAu75H9DRtQ2/+adDkbV4=,tag:FAi3UYW9Tb+glFNuB0luSQ==,type:str]
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-01T16:53:08Z"
    mac: ENC[AES256_GCM,data:unsR0BKysymBgK0ngh6N4MC6NZVLwQpv80JvBRk71onounkdo/rkscqX8dJoDLoT20aUyzxb3pNrHve9Rpq+UF7PvvY+/jbKnI/Ig63O2zR5VLDi/+YUwAbSyo6KLqk9VImBPl1zZioan8Jv4YJ4587DkzxMuZmDYoS7lD4qDbk=,iv:945fHR3gjw+HjLn7Hq5+9+1961FiYfIRBt26Ph2gcvE=,tag:V0PVnjQ1KLduziMejPfJMA==,type:str]
    pgp:
        - created_at: "2024-07-20T20:11:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//ccRTb/gHKccBu3kXaRM43l0n1tG+qbY3ycVFWJfZ8ehe
            Qz6RCmzIjPu2/GYv5cvl5x7II3wpK5jLsjPEDYT/udgmBKrWnhORe7NSXLu9eYkK
            YDzVTnLjplyD9x0aljaCKZICOPO1GlFGxmZ+Dq/bGhsJCLSMa8UjGQuU+6ZyRDG2
            +s0E+sKRuggKTK3RoUuwPmI+wcXnuOvwGOMNOkB3hchghNoAKcu8UVHWBnYjBSdO
            +ZGf9mLhkDBSOv+OW8IVDLe4Xw7I79MjZljHVWX5FDx32E30AXn41cY1c85I/AnA
            d3fs2SsrBfN7SSPezD6GjbtCeALqKPX1SREnaxqIFms4P+TXUU/RZ70n+QgaMd7Z
            Gc7FfFtt7axgpoEesZNB066OOL5ftpxtbwbsEMcjmqh67+cihslKWMpeJZ9T/im+
            a2PUXAwEnH04rXERyLXxBmwsqfazkEu+q5CGxSeyz9vVmjST6hdRqPFSqXq0QQUe
            v8BsNXEgwhD6VuwLsKXWSxWKHBUl99HNEQCb0erIKc/hKbwyn+vPiCuQ13Kxi2iR
            l7X5k6hDD1yAEG11dq1R100AKouljaKEa1I4vjLuZ3dvXGO46qcRe//h2SBTANWu
            tBKsznVkxJt3X08oOriUbkxcyharg13a4uBIVp3G5Wm2pX6hSyG9FUeri9NzchzU
            ZgEJAhA03Lc8Oho1nib6rmGfcQEATjFDuZAJ1BX0wRRTZ2JPr/PU3025dhS5JcUk
            gIza1T47y441q7YTCRDJ/3txyCZzjGSkfWcvf4FmSmL3iqkYB6wvDUlPH9bSg/Vf
            rK7icxLFSg==
            =WkK9
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(nginx.ingress.kubernetes.io/auth-signin|host)$
    version: 3.9.2
