# --------------------
# Longhorn
#   - Repo:           https://github.com/longhorn/longhorn
#   - Docs:           https://longhorn.io/docs/
#   - Chart Defaults: https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
# --------------------
longhornUI:
    # -- Replica count for Longhorn UI.
    replicas: 1
preUpgradeChecker:
    upgradeVersionCheck: false
upgradeCheck:
    enabled: false
ingress:
    enabled: true
    ingressClassName: nginx
    host: ENC[AES256_GCM,data:3ZZUp26LHuGTqIgDdL991yhmz3Fdvm82LK6/IQ==,iv:UdqfNG4Rcav7n+hp8SAj0KYHXEgOJPMVStV3vEM9RFE=,tag:EHNGU52HphU7fh4J5A3zyQ==,type:str]
    tls: true
    tlsSecret: local-wildcard-cert
    path: /
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 10000m
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.ingress.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:W/UIJ2b6+0vJN5ACXYcV6ko/nUOnaD4ivKyqKYYLCL3qUWiGV3n9gZYcJEYD,iv:7/T92jiQuva3x6Men7eLel0wKokBJfGYalT7FPDX/kE=,tag:D8QdemgkhIOI1aBetVPu/A==,type:str]
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
sops:
    lastmodified: "2026-04-18T12:50:02Z"
    mac: ENC[AES256_GCM,data:QUx0WE7JkJ7b9cN5jx4QZKOKop+zdJjG5JPGMiaCAVPTFO79HM2zC+0vUG9MgDJTjuBe+XPENbyuaIGs+45QcIl7LD95LVtHB8R88KMl3CjNTXiKNxYx+rFlQMPMI/Dgvl3ADWENKqWngjJj0NToy9Cyx04+qSXWAUbdcEEjTvE=,iv:Oj+PKCKzoZtrFh8ZsgA+eOsq8Q95n9rS3GuqpfasHic=,tag:o3q767XIPC4wbFryZhR36A==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAhK7eUKXjQDwQMjPXOuQ6zQdbnfGcqlOY3zOQN8cWtcYD
            PHP79f13Ffk4RUmepOqu/PReNXl+OdfXczU2m6ovlfUzlzy95T54AjSCg5Np9fto
            PLkqmCOo4XHAIdkX2JVG8lJ+c3AdpIxdQ1cOQ3bHKZXWB4Mol3wZ3t6x4qyx9L4h
            MDP/B60LlhLVQ6lTJKQEMiMbLLWyrtFR/jIGfgxStbdBZPBDlwSK7714OUzXeoGK
            Z3sACq1VMNhDhZDQYh/KxwXg+eMp0U5nA6Z8tg0OM80QBmYqZeLu3aateTObfy1V
            9DIG2+0qzUdkGyK8PZzyrZZFhK7lJyH8N/YM4M1mDbNAarmkQUzs+ubje5TNvU8Z
            cwTuEzRVXNcjRNW/7AW8zAvOxmmAp1xRkSEDJOP6tQc7+LrvYubitlSbefDweOkT
            g6mQX8r7I1+EF/anVp7+xZL2ZQBM93h5vql28nsugv+31sDVQ1gtYdis+xiZ7KR1
            4b3zJpzpsEVh4Nxt53bbB4Z61DuuP7CqRSPPC5ZDtEJeGF0ZFhIq09F4WBfJSmg5
            /6TSPItZpR4/7Y5QFLb4UJoKauUj0UF+zY/izNKYjgr7c3oFQ5O1vsiA4pTkdaub
            E5NkjbtnzaUmM3eEH6YIZIZENjDSlS+xR3jj1BE3MBq6YQZutCaEind5aPRtK6nU
            ZgEJAhCDZl47ztI7uhHVssDaRc3rIZgSWWHEXmD95qBCmpZHZU/5CZhkqBsBk11B
            xq8RlLqYRLcGyzSUyGqLTmFqUF/hyFj+GQyfOZ//hhbR7CAaAUIN9pG8imyhngpg
            2f7rXsPX4Q==
            =Iw4Z
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(nginx.ingress.kubernetes.io/auth-signin|host)$
    mac_only_encrypted: true
    version: 3.12.2
