#ENC[AES256_GCM,data:0O001z+YgdHEDo2FlTQ0bkbsriFRGpinc5IuUcGmY0a+qnh4JAd8Xn9isrEJOteqwmUqJB9DnjOtUHaTkseaRByd1SvwNDPB,iv:446SdsC4BAYVIkr46bmiYr+O5z51Eycht1yAnmduh1c=,tag:LEnv+nMGPbDCbMKslk9oxw==,type:comment]
MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ei8rqUGPhSsPAEUxYYFTprAr5jQ=,iv:aRaG2z5IV2Pr5c0zgeOeJ6Txe1CGc6ri2kZdUNlmXqs=,tag:AYfFY+dFXvz9OljVlq+utQ==,type:str]
sops:
    lastmodified: "2026-08-20T10:00:02Z"
    mac: ENC[AES256_GCM,data:AAcoQ458HdwKL1T2TGM5uPUSJ4kzgr0grVEJ2XNEJQVjsBWh2c6bUjNMzBAX/ufPrg8MK+Yc78/29kuSGploWm6akl1kF6rgVb7jhI1LFXcfPB/cz8J7YqvRTEGKpM4tmCcfeHD7T3LsJtC1llaw1WliOTw4Xrzs4Urzrw0v7Yw=,iv:jLLaghGBfwj1dUn8U+dN6DfxpjNenAFhhLmuJAsSMR8=,tag:h8NqfciIO1R2Xs3w3tRhRA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T10:00:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAr5sPb2KddJnhfAZWXLBvFy6d2SaZfXCSSesHsf4CU5PE
            r9O+HbYyXFwPvQXevCgolBc78wPpcxYfRyE9LRJhkLAPXyysdqFoDaAuqU8rwTqL
            NEiD9x3q5uu/kmKEteaLJ878Hu5U71xS9cKryBuODyLfd/6dTXID7P3xPkO4QzHN
            Dj71w3PxPHfdgXmst2ffJ170IniT6qYvG3vDkfCvcpxKfrUuJHNA2ewfq6Wou7DO
            rwYClUMEkyi2BNfT8IhYPNJy2Dc59I76ytL+rWLqmPhx+aHsPUcDge4oyd4ST176
            LL601WCy13cVTFak3bNRFjouBtkiEDhrxZdmjMRNqjpFwDNKk/cKvh1rztxaSHz2
            zZZDo8ZodXJAM29ABGD9S+Pi2W2obe2WN0TW9yQ3MCs9XtC9Fgal/fO++n5wjmqa
            gqckRG4f2ThMmtAmrrdAydF5cPKlyj8lYbQHRIE2P+7H5z2qBeytJ1qWRjC6cs7l
            fSATamHNqrmp5MTWWkTrztLXSC4JkWYbsEZakSY8emGzREyXusVKHcgyC3qDlBMd
            +bCrYeKSPz2nqGkNiBkaQzuWjwghc1Be7Zw3sWqGRXLPasX7aEYE8npC2z1JE2FJ
            AT4atC5dYTQnRTclfbMepiyQ1LKfMmGpS4p8pH2evpNbfPK68vCUK1kBzpY00rXU
            aAEJAhA6dXRGRrErIZpp289oUzQmKKjnLmgEupuLpwubGyfYqKnHPYPeiJUyrrqY
            S3rbmCl9H9tEvWAS3gTbNrvcLh4it9NCwUDOqQZsvaRNPnOfNjB8Rkrqw606eFR+
            JICGbvUXyM3g
            =EH3b
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
