# Default values for external-service.

# Labels applied to all templates
labels:
  host: hoarder

# External server configuration
server:
  ip: "{{ .Values.ips_tailscale.hoarder }}"
  port: 8181

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  tls:
  - secretName: local-wildcard-cert
  hosts:
    - host: local.{{ .Values.domain }}
      paths:
        - path: /tautulli
          pathType: Prefix
