{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database-svc.fullname" . }}-backup
  labels:
    {{- include "database-svc.labels" . | nindent 4 }}
data:
  db-backup.yml: |
    {{- .Values.backup.configFile | nindent 4 }}
{{- end }}
