{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database-svc.fullname" . }}
  labels:
    {{- include "database-svc.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.configmap.data | nindent 2) $ }}
{{- end }}
