{{- if and .Values.secret (or .Values.secret.stringData .Values.secret.data) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-svc.fullname" . }}
  labels:
    {{- include "database-svc.labels" . | nindent 4 }}
stringData: {{- toYaml .Values.secret.stringData | nindent 2 }}
data: {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
