---
# --------------------
# ghorg
# --------------------
services:
  ghorg:
    image: ghcr.io/gabrie30/ghorg:v1.11.14
    container_name: ghorg
    restart: unless-stopped
    network_mode: bridge
    entrypoint: "sh"
    tty: true
    stdin_open: true
    volumes:
      - "/mnt/user/appdata/ghorg/:/config"
      - "/mnt/user/hoarded/repositories/:/data"
