- name: Update servers with base dependencies
  hosts:
  - k3s_cluster

  roles:
  - maintenance/update

# - name: Docker installation on first master ({{ groups['k3s_masters'][0] }})
#   hosts:
#   - k3s_masters[0]
#   roles:
#   - docker/provision

- name: Provision and update k3s-cluster
  hosts:
  - k3s_cluster
  roles:
    - k3s/provisioning

- name: k3s configuration master nodes
  hosts: k3s_masters
  become: yes
  roles:
  - k3s/master

- name: k3s configuration worker nodes
  hosts: k3s_workers
  become: yes
  roles:
  - k3s/node
