# --------------------
# Homarr
#   - Repo:           https://github.com/homarr-labs/homarr
#   - Docs:           https://homarr.dev/docs/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.59.2
ports:
    - containerPort: 7575
      name: http
      protocol: TCP
      service: true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:/pyDLq6CNje//s+rvB6vr+RZf4OKNvyVCfwfbU1LX6sqFVCFZBxgcQyDyWCWOegYZHTsHhCEAD3seT9+xfFnLg==,iv:GPpJLto+oKr1GGejpmn9lYfNvVRYa+CMd0FiPThIXD8=,tag:ADLfSJKg8cRi+UWrl7NtvQ==,type:str]
volumeMounts:
    - mountPath: /appdata
      name: data
volumes:
    - name: data
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Mi
ingress:
    enabled: true
    # authelia: true
    className: nginx
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: homarr.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: Prefix
livenessProbe: {}
readinessProbe: {}
resources:
    requests:
        cpu: 100m
        memory: 64Mi
    limits:
        cpu: 100m
        memory: 128Mi
tolerations: []
affinity: {}
dnsConfig:
    nameservers:
        - '{{ .Values.ips.rpi_4b }}'
sops:
    lastmodified: "2026-04-13T20:28:42Z"
    mac: ENC[AES256_GCM,data:9b7yYNczN6aO0ncFZgI9bDprynDc4Wul8mu/Xy2kjAtV5syUwnGUC0PyMme0DCyminSkoUpKS0G940Sd3gGjuWMe+j5NesHQgfdotZxC6QkO0oe3I7EBn1TXEE0QRULnJrsYp8IjHexlOtUfNPCI5mAB4DChU9TKKPnKZJ2vaeU=,iv:huTys9dhpwxKt7KN21S11wORXm0H9KM0DQa4A8NGo9g=,tag:LylsST1s9LXF2ZCGv+uDIw==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+MQYLNo4POgI+qD/kIw8JT9TMVAs7le2+14O6zv+FPVgR
            wBqWDjCK7r5sBQC+Sa3jf02Fb3e+tBtWwW0sYGYBTD+PDZ8po4FZIjwdlyZENKFP
            UgvU5aY6f+TSri/n1M4PG60/A19K4HQ9ByqRVt6HbHqNpJstenYce20kOo21Ka+7
            ptT0L/hqqJPbmObKa27uItK2UI3EVXt0BghZLwqw1nWDA8dodvHQ5b3JuWqM04/J
            VAbRKKrfQ/aGTxn34A6povsDTyARxuCJOvwB+llv602U9eAAdAfOqd5bm/nY7syE
            0kb7XRTkxNT1gdDatKfV2Ep1FeE1LNQV6065SUhjORM/eOSdnMUm2MqqA+Tpah9i
            0gl5jnWD8mG9i5YyxWZrd4ov0u4Jz06uzwoKQPm/xJWWH5l3iLxvA1Qxk5hqrHuQ
            RhtlxkqY/0HcU9DVq1n9GYvFL0RO3ip2QD3LtYV843MEs2BL44xpx6pwYnfxUmk1
            WSgJs8e+Vfv5ZMm1H0+6RrlwXTO843Xk3oNLPsXWJETb9VtgAia14l+fLAfsmoJ+
            zH1+R3uj1OLrUxKdAQp5j4edywx+1iONKb9xyyACQ4xyJtddT0IUzXcqCmfQQq6/
            LEhsGzT7ADxrM2Mb+NCfdRslcYwWMLd7GZUj/v34PbiL8l9wDh2bhzXJr0thvmXU
            ZgEJAhBZH2pES4cosw8dDmLVAY6hBxRwISfaDPwVVBylJdUNTYszV1cEHaeIKr5R
            yRARBgi+oJh/PWT2Ap6rjNkOzMtsRWQ38WsmG0wDJRaZKRgCyQvV8HNVo3XtFeIG
            CAwIz0cH9Q==
            =xdn9
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
