# --------------------
# Overseerr
#   - Repo:           https://github.com/sct/overseerr
#   - Docs:           https://docs.overseerr.dev/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/external-svc/values.yaml
# --------------------
---
# Default values for external-service.

# Labels applied to all templates
labels:
  host: hoarder

# External server configuration
server:
  ip: "{{ .Values.ips_tailscale.hoarder }}"
  port: 5055

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  tls:
    - secretName: seerr-cert
  hosts:
    - host: seerr.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
