---
docker_compose_base_dir: "{{ ansible_facts['env']['HOME'] }}/homelab/docker"
docker_compose_volumes_dir: /opt/docker
docker_compose_stacks_src: "{{ playbook_dir }}/../../docker"
docker_compose_networks: {}
docker_compose_recreate_policy: auto
