# --------------------
# Redis
#   - Repo:           https://github.com/redis/redis
#   - Docs:           https://redis.io/docs/
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/database-svc/values.yaml
# --------------------
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: docker.io/redis
    tag: 7.4-alpine
#   pullPolicy: Always
command: {}
args: {}
ports:
    - containerPort: 6379
      name: redis
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: ENC[AES256_GCM,data:csrcaUM9/26WXCI=,iv:gh6fskXLggDRrQqWebXuLfDIZNcCtS5tU489TtsxuTA=,tag:iLbOpC0SF76U2eEy1zVRWg==,type:str]
    annotations:
        metallb.universe.tf/allow-shared-ip: db-svc
configmap: {}
# config_1: abc
# config_2: def
volumeMounts:
    - name: data
      mountPath: /data
volumeClaimTemplates:
    - name: data
      accessModes:
        - ReadWriteOnce
      storageClass: longhorn-persistent
      storage: 5Gi
livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    exec:
        command:
            - redis-cli
            - ping
readinessProbe:
    initialDelaySeconds: 5
    exec:
        command:
            - redis-cli
            - ping
resources:
    limits:
        cpu: 500m
        memory: 256Mi
    requests:
        cpu: 25m
        memory: 64Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - mariadb
                topologyKey: kubernetes.io/hostname
sops:
    lastmodified: "2026-04-13T20:28:41Z"
    mac: ENC[AES256_GCM,data:Kh+zO3YdTlnJVObROwTqoTIDF22Bbu7n8iwO1MkopyAyzF1iYiGlJ5tHilqdpaQ0x8nAXxYTV8B/uj6PhbDIwJsK3zMX3Iri2fDtDImjF5RvuG2Y6JmhOEzDZw3TulqX+Kp9eraNjOmNdje73O6LzJYb0GELC1xchxGb1iHUhTI=,iv:BxsJythBut+FbbIuWTCZLYgu0LJPcMQp4qvNTQVoASQ=,tag:0aUgq2HKi8kSxc0M6d4iuQ==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//fQrMeo7lOXznjwgbOrhdi9dvjNjCJzQ8bDlL99SeQ2KM
            ePSUtOjAyUppZ+3OHKMb3pZCHnTPAcGx/c1DfaczHyS0qMMMbIIUGD303QPpwbF1
            Oj2WVbTD/HA5w9Ur4ls5Hr0arTLxenwd7IVNj4lpd6AQO77CrQN5sI3PH/VXOTsf
            d40CLJMJvNqKWK0kbjmBGCUohjU/lgyUgsDv02M5is0bE+1k7Qv/uHtxMwLgNMDv
            GmhY1D39h1aF2UOQRCkhKtHUVBNubx1nv6OGErRX2+r3QJVzVWt1rZInSGrG7N2f
            tIjmkMwm4V05WvyuIqogg0D8e3yDB5Go3NqozRZvTDosXUD7609P0VM4TB93WpTq
            nkVov4TuPThjc2QNsm4HXoiZQsEYRbQdjTyKjZWSPe1ACVGQTFd7yLHXcAMEd1Oa
            8BP9ZjGsexb6owQwlLxohNTRPEeZwgrjQJU77LYeB2yZ8SWkfj15dhkdbIc9sad7
            jnqpacBczHRDF3pDXqVCZnFES6a6uWP4ytoPtaVwU0yg0y8HdYM0MH3TIJRboVQE
            lUEO9cZOh4/vZIod0gEaPo/4Fx/Bvnt64VwbOOvjth5nXzN5oeIkZJ2stiA1f+ch
            fB5d+oAlWpjyvknNP6AcTUChWnIWk63h53WdP0Ozi9xBj+ieQulfjdISe3ujz1zU
            ZgEJAhDaBXzOGXbZGzfo7JgVHzyFB7OGsQhiaRHLnJ5IzoFlDxPZexPGOXgc0Ezj
            r3riOlU8AsXnViE/uTSc8qMtwG5UgL0Egen+gcTY800WHbYiQIrBQQX8MHR/AIr3
            s5utHzQmqA==
            =3AdY
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(data|stringData|loadBalancerIP)$
    mac_only_encrypted: true
    version: 3.12.2
