{{- define "common.podSpec" -}}
{{- with .Values.pod }}
{{- if .hostNetwork }}
hostNetwork: {{ .hostNetwork }}
{{- end }}
securityContext:
  {{- toYaml .podSecurityContext | nindent 8 }}
restartPolicy:  {{ .restartPolicy }}
initContainers: {{ tpl (toYaml .initContainers | nindent 8) $ }}
containers:
  - name: {{ $.Release.Name }}
    securityContext:
      {{- toYaml .securityContext | nindent 12 }}
    image: "{{ required "Must specify image repository" .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .image.pullPolicy }}
    {{- with .command }}
    command:
      {{- toYaml . | nindent 12 }}
    {{- end }}
    {{- with .args }}
    args:
      {{- toYaml . | nindent 12 }}
    {{- end }}
    ports:
      {{- range $.Values.ports }}
      - containerPort: {{ .containerPort }}
        {{- if .name }}
        name: {{ .name }}
        {{- end }}
        protocol: {{ .protocol | default "TCP" }}
      {{- end }}
    env:
    - name: TZ
      value: {{ $.Values.tz }}
    envFrom:
    {{- if $.Values.configmap.mountEnv }}
    - configMapRef:
        name: {{ include "helm.fullname" . }}
    {{- end }}
    {{- if ($.Values.secret).mountEnv }}
    - secretRef:
        name: {{ include "helm.fullname" . }}
    {{- end }}
    {{- with .volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 12 }}
    {{- end }}
    {{- with .livenessProbe }}
    livenessProbe:
      {{- tpl (toYaml . | nindent 12) $ }}
    {{- end }}
    {{- with .readinessProbe }}
    readinessProbe:
      {{- tpl (toYaml . | nindent 12) $ }}
    {{- end }}
    {{- with .resources }}
    resources:
      {{- toYaml . | nindent 12 }}
    {{- end }}
  {{- range .additionalContainers }}
  - {{ tpl (toYaml . | trim | nindent 10) $ }}
  {{- end }}
{{- if .volumes }}
volumes:
{{- range .volumes }}
  {{- if and .mountPvc $.Values.pvc }}
  - name: {{ .name }}
    persistentVolumeClaim:
      claimName: {{ include "helm.fullname" $ }}-pvc
  {{- else }}
  {{- $list := list . -}}
  {{- toYaml $list | nindent 8 }}
  {{- end }}
{{- end }}
{{- end }}
{{- with .nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .affinity }}
affinity:
  {{- tpl (toYaml . | nindent 8) $ }}
{{- end }}
{{- with .tolerations }}
tolerations:
  {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .dnsConfig }}
dnsConfig:
  {{- tpl (toYaml . | nindent 8) $ }}
{{- end }}
{{- end }}
{{- end -}}
