# Default values for external-service.

# Labels applied to all templates
labels:
  host: hoarder

# External server configuration
server:
  ip: "{{ .Values.ips_tailscale.hoarder }}"
  port: 8112

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Deluge-Base "/deluge/";
  tls:
  - secretName: local-wildcard-cert
  hosts:
    - host: local.{{ .Values.domain }}
      paths:
        - path: /deluge(/|$)(.*)
          pathType: Prefix
