---
# --------------------
# scrutiny
#   - Project: https://github.com/AnalogJ/scrutiny
# --------------------
services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus@sha256:18689773150d6b8b53c94a435f40f7b6e946fd4a6d40b44c64fa2154a5b38941
    container_name: scrutiny
    restart: unless-stopped
    privileged: true
    ports:
      - "8084:8080/tcp"
    volumes:
      - "/run/udev:/run/udev:ro"
      - "/dev/disk:/dev/disk:ro"
      - "/mnt/user/appdata/scrutiny/config:/opt/scrutiny/config"
      - "/mnt/user/appdata/scrutiny/influxdb:/opt/scrutiny/influxdb"
