DOMAIN: ENC[AES256_GCM,data:0afXb78oWymMHlC/Sg==,iv:v0+RZHyrNRV92eUAfCa97WgMBNiqwQcR+hOBRrqBN4k=,tag:eD5zIRnWWt38WOSFQ1JjBA==,type:str]
sops:
    lastmodified: "2026-08-20T13:13:34Z"
    mac: ENC[AES256_GCM,data:BajFd9oj+7nI2fNxYcumuJY5UJm2fRChXa2MALlnf/yhG1lMrRWbmXFCNdk7HGx8nOoKJsMhN9ENkhnp2AbsUYObOcHO0NJhQd1S0YHjE4tl7o1jKFVxvpdqwWQ7z/kDz6AL8Ny4qXdYttdJEhomP5z1J8wKXaNfntX8ljFGJEg=,iv:TJh9/puL2ZK7pI53tt/xgf7BzkbDMEb/4Wa4uBvpiPU=,tag:n4lJxfkMU8wB81sfn1UGZA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ//bUWsED17YCMrY9A72Lg+5XNBrovov4/PKnoI7IB1HHea
            fHNZIMPXAw2cZVLvN78NqdMoAPLD77xySNurIgrEshTznGW31A/+VSNo003HvOMV
            vkrhR0Jz6rb6baPyJGC6IkGUVNxLFlpMx4mTXyQDvgSwEwK7C7XY76Q1hYs82k68
            ZxMYdpOW7n7yY1GAI7fueDe5to1DB1WbfkB24Ps9RxvFfSL8ZCHZSZnUgnQyj00C
            2v+lJGZM1gLWJJ1bBMqNIYXfUfS6q6unLg9TnSwNHQPL2K7YTSNNap9qnCNaIy+D
            tdqHtszeL463zr7Vx6ddHxuRwWGnZuJoKkwAyezkJRPlOTf3rYweXPPgwxs8ToUs
            WIxZOzl4OnWO8HM8hfWM1QKjl9Pi5VVMgb089LruVYsIF0AcTf4AQYidcdBP+5KK
            i0hHk8u+AZ6DSuKQPOzGCfGG+jWh7Z2DI6fg8/3K/4wqV2nQQskEzBCMEturLmMv
            Rkb7vdr97t0p/VBWvzeDao88o05DEsxcwmGNwU/3/zG8rwo7uKj+dH93bRTOuric
            lryvX8brO5t4D79VZPl4MeAD4twbkEdmMDcTuQTAKN+YK9jRMxyIbbHrpB0qItc9
            DDAFEv+n3bMDiOdcjph9A7IbVr0YA4/fuMRduTR4AbIIBiUBaHTMs5/RWJVhXCXU
            aAEJAhBrgIECNjyA/A5t3Vrh2i931f63OFNoSh66c6EQfhcqbM+nOOw14DIifJyu
            uXaTNFVErlM4b6Z6j3PbvE/Nq15N6xoq9q6DMZxW0pbzAejj/BIjCGn53RwQOzWX
            4eM/00UWrJnf
            =d2YY
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
