labels: {}
  # label_1: abc
  # label_2: def

replicas: 1

image:
  repository: linuxserver/freshrss
  tag: latest

strategy:
  type: Recreate

ports:
- containerPort: 80
  service: true

# Uses ports from .ports section, if service is true
service:
  enabled: true

volumeMounts:
- name: config
  mountPath: /config
  # readOnly: true

volumes:
- name: config
  mountPvc: yes

pvc:
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

ingress:
  enabled: true
  authelia: true
  className: "nginx"
  annotations: {}
  tls:
  - secretName: rss-cert
  hosts:
    - host: rss.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
mydomain: "{{ .Values.local.domain }}"
