apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-svc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.server.port }}
      protocol: {{ .Values.server.protocol }}
