nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: ghcr.io/mealie-recipes/mealie
    tag: v3.3.2
    pullPolicy: Always
#   restartPolicy:
command: {}
args: {}
ports:
    - containerPort: 9000
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        POSTGRES_USER: ENC[AES256_GCM,data:Hp+v5BAC,iv:ndcw5cbeu/oLhlnTPzdoqyjkkM8EGDmaKBGIojQtRFk=,tag:uHo3bXf/37BcB0l1xeBrog==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:8rW7BuZ2XtyYMEeGfY8AVpcDK0E=,iv:DaAr3aZVrAQFLbspkv8devCQYWutycMbvUAKkHqPqec=,tag:dAo5GI9vNxHuA4tJAgJt+g==,type:str]
        OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:QHr+755AMJzK3M3Z,iv:/XMc8LuOVf5hGwrTwTuyaf54deF0+yKicPO7L/X+ab0=,tag:BP99MF9wqfxip/LwTNexMw==,type:str]
        OIDC_USER_GROUP: ENC[AES256_GCM,data:rTeiPr4mMVogQf0=,iv:CXCerbl6f9zaWkQCiQB79gSV/23dG3PpcPetzMWaWlg=,tag:lxXHBRsGtGUXL+UrOu2jmg==,type:str]
        OIDC_CLIENT_ID: ENC[AES256_GCM,data:P3FVVOLbKdBIZZewCPxq0XIGg3lLplP6K+NF18BPU3zIKLCLH4eV0A==,iv:XfhbBkUDpUWevci0LKVS8Yd9cNwzObdCezw8HIPnIkQ=,tag:/90NG3t/TiGx/Lzb3MUIqA==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Ym+jBcHJRwi0/ZcFvfMhsgwWchCAgm1r6F1GKZJs1A9aRq5emLu5ehjNk3+gLKYo0Y4nyrZJW+oBoP5zfufmMtyrGPP4VEocPGpNyDLItAWXLCgz37YV2AI7Esa4Lh5X9pQ48A6xpUWf8UthGk7K4mII/s/QQJjhde6eg7nO2MY=,iv:ragbnrTYsF0C/PQuhHRpAokSW+xoBGkauWbVltm4vV0=,tag:WJJTGOwsiw/yObVEFBnlIA==,type:str]
        OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:EPrjKn3cw1b4oRmki5OiM+PD1QP4CFYw7xIKSIr+HHesiha6J6gfpWnk7ewZXOhrMaOXEQg3YX1NzVyBLEqUMePU1QcquCYUiHyp5vDC7Q==,iv:Xzn5OxpieL5LZ+PYMNU5kx+HvEKWKFgT6GtZWsHHVLQ=,tag:5QkKkG9CSBQXcqkU68KyMA==,type:str]
configmap:
    mountEnv: true
    data:
        ALLOW_SIGNUP: "false"
        PUID: 1000
        PGID: 1000
        BASE_URL: https://mealie.local.{{ .Values.domain }}
        DB_ENGINE: postgres
        POSTGRES_SERVER: postgres.databases
        POSTGRES_PORT: 5432
        POSTGRES_DB: mealie
        OIDC_AUTH_ENABLED: "true"
        ALLOW_PASSWORD_LOGIN: "false"
volumeMounts:
    - mountPath: /app/data
      name: data
volumes:
    - name: data
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    # annotations:
    #     nginx.ingress.kubernetes.io/client-max-body-size: "0"
    #     nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: mealie.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - postgres
                topologyKey: kubernetes.io/hostname
sops:
    lastmodified: "2026-04-13T20:28:42Z"
    mac: ENC[AES256_GCM,data:uUfNP+STeFyslsQR7YvO1fC9uZJi5eifjjNp3m/M9CRTdZEUPsDTi7Ku38ynLBagbKdN9qA7FTPfbDxqWi45PGVeeX0qlskRk1Ba4IcRNss5i4rGqp9QizU9mQOQVYAfz5ViJ2/bY/2PIhUDcvn25EdRk1UKAA09n6i4+ClPVNI=,iv:+2opa9Uz/aALX/qbDoBEeiDfCyLIAnqTCxJQks0OsjQ=,tag:0zF1hKBtUVf8ljGI8A8HFg==,type:str]
    pgp:
        - created_at: "2026-04-13T20:28:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAAjLBcXBPLM/SFlm+N0Jea9h9quQRov4kPbxuM0uwwpwOO
            aBJoLsZCSkQWrjiuiLpoZs6fbkgzD8OiIAuzUGYQxyaFlnTZFZBzmAWl0LMveoeA
            JVJJVu5Tr0x1fVn66gWRcymzZ4Jsz4hpuKOMUUmJRxmE52lRfKFjM0/GnjW9f0FO
            6O9JZnCMlCqxGHUJyTtq8UCEfNwSICTEfOnfrm3pjc5wmK/LFQ4wRzqCXStAo5La
            /4d+Gmc44KCCPRqFu7e2Vo3bp+nXYhjmhtrbyULk+JsIgY5ZBGx0hqNSr04FUm6e
            g3KObm2BCEGRjy4X1AMUWboC5fNEDGequxPCMhaqAHlCZ/Odfc19mbpzkdCrPLJB
            wokcI1MFhY8FEJdmE8YLiu2f07Qn+ZQmWC5TIRoEuiaY5krH6qzNvxaeJ5vfCjko
            4UKZdtcn/7cto8p7fiTYSeUNzFn7YIuHn9iM/r7GFAZnX5ymCt1orGbum0BdRGIb
            iJjUCaue180ypAvLNqu4bmUL1Mrf0XRsQJCz1bMGI7xGDdZ2menMGFm53uSpDL0/
            sThzekIjoabIS7OF6s1uWRvJXsFVtZ4a9Vh8bbUDUvwq0mT0kS/LOPYVgDBtMc3U
            B5QZlOCPL8RjW81qMiRkCpzV0W/G0STFoQnepjWwHT8r5kz6dmTkJC5YX3uUR2fU
            aAEJAhBeUpxdU895KDTLsYRXTTaF26Pqo+m615xrGDnAEggGgwTj3xnLchQQd1Kq
            nxHfQV98edtMetK4Qejg/2k94BJli2ccWnpzQx+FtM/XR9GdNxIaxjuHRvA0Q69J
            dUZ0IDMoBazS
            =y/n/
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    mac_only_encrypted: true
    version: 3.12.2
