nameOverride: ""
fullnameOverride: ""
labels: {}
# label_1: abc
# label_2: def
podAnnotations: {}
# annot_1: abc
# annot_2: def
replicas: 1
revisionHistoryLimit: 0
strategy:
    type: Recreate
image:
    repository: ghcr.io/mealie-recipes/mealie
    tag: v3.3.2
    pullPolicy: Always
#   restartPolicy:
command: {}
args: {}
ports:
    - containerPort: 9000
      name: http
      protocol: TCP
      service: true
# Uses ports from .ports section, if service is true
service:
    enabled: true
secret:
    mountEnv: true
    stringData:
        POSTGRES_USER: ENC[AES256_GCM,data:ABmIZlbg,iv:06/IfIbFSPMfQC3jbeYYJuxCCwdywmDeYKuMu3MNaJo=,tag:/4KJCSrjuYN3XHuoqdh5pA==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:L7ZwlcrdqhwJAD8GJDQvJQhnU/Y=,iv:4sEstygyNizroewVl0H94J8+1sr3wyOMimgL/hQxHiI=,tag:jVdxtkrPAqFySt+h349L4A==,type:str]
        OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:k6K3qGnFGn8w8hgN,iv:9ByoIXx2ReK2eMAyF/pW95iryl5z+CxXa5+/24x61So=,tag:Lu3tYQdth2CmjJGeVDA+7A==,type:str]
        OIDC_USER_GROUP: ENC[AES256_GCM,data:9DjChdPx7KhHMtc=,iv:gHxpPwm/ix7WLP8pm+IxW6EFdAguRHKYX3TeWO3lzeo=,tag:3MQMnsbYz4a1nZPGi9jhRw==,type:str]
        OIDC_CLIENT_ID: ENC[AES256_GCM,data:OQ27CMLqUv/6IHdSzn4f+qINvGLb4GkKdN1gFDj+2ukMEGge5C/T+Q==,iv:k9l6t04RZqbQmASN1vN1tLx8ggeytdBxWwiQuPtgq7U=,tag:Fi1OYLHInqj+F/yiMFwHtg==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:w0EQaysxi7D2bxRk0Y7oIE1bsCx0QxWG5LDEPMhsiDDojZzcUYE0rk9j18VRzjh908o6MBK2pGnX5YsEvrKF5RpqtygDraI7zvLynW1Ru+oXLEL8QLOc4d4VYdK0tpwetnmp/IiNRXgmRknJVajjRMTo0w7+dRWE99FS1qU3WWk=,iv:gDeDhro5FvAvaTyXAxWfCHl1rkYx0mgrz7WzQ4KMvGM=,tag:mdYGO8gsIyLeVfE/Vc1Nng==,type:str]
        OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:Og52mpUyUf2KMw+fOcuAu7DFiaGbzoZCgJQJRnzXgUjGkeq7Erb+t5VEHVRyOaJyamybK3EYwWcYDmXj9rpxcdCmjX5TKzEba8sWAbTA8w==,iv:r2fyjCn96c5n5EBaUf48wysFUDhMX7SPweHe5zk1xq0=,tag:o0LwHbteML4TPOIA0X66Iw==,type:str]
configmap:
    mountEnv: true
    data:
        ALLOW_SIGNUP: "false"
        PUID: 1000
        PGID: 1000
        BASE_URL: https://mealie.local.{{ .Values.domain }}
        DB_ENGINE: postgres
        POSTGRES_SERVER: postgres.databases
        POSTGRES_PORT: 5432
        POSTGRES_DB: mealie
        OIDC_AUTH_ENABLED: "true"
        ALLOW_PASSWORD_LOGIN: "false"
volumeMounts:
    - mountPath: /app/data
      name: data
volumes:
    - name: data
      mountPvc: "yes"
pvc:
    storageClassName: longhorn-persistent
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
ingress:
    enabled: true
    authelia: true
    className: nginx
    # annotations:
    #     nginx.ingress.kubernetes.io/client-max-body-size: "0"
    #     nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: local-wildcard-cert
    # Will assume the first element in .ports, regardless of service
    hosts:
        - host: mealie.local.{{ .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
livenessProbe: {}
readinessProbe: {}
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity:
    podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                namespaceSelector: {}
                labelSelector:
                    matchExpressions:
                        - key: app.kubernetes.io/instance
                          operator: In
                          values:
                            - postgres
                topologyKey: kubernetes.io/hostname
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-13T20:24:36Z"
    mac: ENC[AES256_GCM,data:Obuj4BWgdQlcno2bxzPUiaj6182hALGcs+Sbp7ktOR2Wbaro1eMKmJJ0uqSfUDBG5KhxJTtZ+6SihMDwSIrE3leKNVgkzba8V5tbwZw2mx9P844oHupHsAPMPwRkg8c9y1OpihGfq9HvvmjXMXLTBL/y1VvK7m251zF3Srp2kfw=,iv:XrIYukGTzkMUEJ/XU2iTwY2Zh3YdlrA4B/rnDqy1DP0=,tag:IAh7jUEgYdsIjSwld36ldw==,type:str]
    pgp:
        - created_at: "2024-07-20T15:23:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGARAArFigkI/8M2Bj6mm4S1Gp+n8qcuIOrqlFNXKIDnyA0xOP
            9FF3PBt4ELvf+WvzwQFSzFBzg26VxpekweEQp/RMY4XdPLpELjlKcqZaYgGCmKTN
            htb10OFYBtWAI2lyYvkiuumX4X3IUAX1W4+ZVW3X2q8/aWal40knOkYh4CKvrCpV
            OrvuyNCyn5QGFoKNgL2UScxr+5JUSdp/99A6W4xdXKEuyEmUsNLrjYlQ639EQDvv
            9exy3f9hgU/Au2/wf4kYQHXMgiBvobZKuMqISCOtiqNtJfvJ5oLolyogN8OzgFt/
            TdjDaD25zfkROIjyYLaAbWBxHo3ypN/3AISeXNBip6dVlXZQziU2ngNQam/sqPQs
            fHHBQhZCaGWov7RuKAp5ADM6ZWmjyQ2JPVV6scwB4weuIS1MGV9FP0YlhnRUT29t
            tCutgVWekThbY1G/0Pk9KhxyM89uZjiUC8/q/xIrP2lc8Z6Ai3cFUyeLWVtUAVFU
            9JwPvXXgrQtvFV6GOJFKCK+fOJ3vO+60UV68EBV8XIyX0R1e6DFdZeZ/Ny/WU10Q
            bpzEpjLDc3oE1Ag3gGo0rWPKSqzDFEkSh9ZRRudZvkrJmulI1hyr6pwv77CXuUhO
            89nugvqD7Va6sH0bugFrnqx5jEisl1bFETbXY+t+4W7JJKB+RRfPMEsx8birXHXU
            aAEJAhDQHOf8Hjhdv28bZXsqHFiHo2bHuK2eoFg+wA3sLzZ+wJOe3ZHnGCg4vEsj
            oHv6z+qCpCZ6pRf5wcdq0JlvyqfBk1r0FyRSlAs5hhLCCdyhwWbGYoSKjJUlA/1U
            UwFrYD6+d1zE
            =KJGh
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    encrypted_regex: ^(stringData)$
    version: 3.9.4
