# --------------------
# bentopdf
#   - Repo:           https://github.com/Alamino/BentoPDF
#   - Image:          ghcr.io/alam00000/bentopdf-simple:2.8.4
#   - Chart Defaults: https://github.com/afonsoc12/homelab/blob/master/kubernetes/charts/homelab-svc/values.yaml
# --------------------
---
replicas: 1

image:
  repository: ghcr.io/alam00000/bentopdf-simple
  tag: 2.8.4

strategy:
  type: Recreate

ports:
  - containerPort: 8080
    service: true

service:
  enabled: true

ingress:
  enabled: true
  authelia: false
  className: "nginx"
  annotations: {}
  tls:
    - secretName: local-wildcard-cert
  hosts:
    - host: pdf.local.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
