# Default values for external-service.

# Labels applied to all templates
labels:
  host: hoarder

# External server configuration
server:
  ip: "{{ .Values.ips_tailscale.hoarder }}"
  port: 8080

# Ingress configuration
ingress:
  enabled: true
  authelia: true
  tls:
  - secretName: srv-wildcard-cert
  hosts:
    - host: hoarder.srv.{{ .Values.domain }}
      paths:
        - path: /
          pathType: Prefix
