---
# --------------------
# calibre
#   - Project: https://calibre-ebook.com/
# --------------------
services:
  calibre:
    image: ghcr.io/linuxserver/calibre:9.13.0
    container_name: calibre
    restart: "no"
    ports:
      - "8082:8080/tcp"
      - "8081:8081/tcp"
    environment:
      PASSWORD: "${PASSWORD}"
      CLI_ARGS: ""
      PUID: "99"
      PGID: "100"
      UMASK: "022"
    volumes:
      - "/mnt/user/media:/media"
      - "/mnt/user/appdata/calibre:/config"
