#ENC[AES256_GCM,data:nWeaeuKN9YZBv6Gp3nwcZ0JC89FXN0fV9EHWp/rrVCkTG2mEr2sgU3gcgRCvvts4q89tQ8VQ8y7io1klDMEx22NbZCvkKHoU,iv:gue4oR6iayW5b08+BsZhu4k+zxer2WNkQhP7XYtPJ5A=,tag:qMLqPsB9SOVxW5D2xw4CNw==,type:comment]
PASSWORD: ENC[AES256_GCM,data:v35VICpeg64=,iv:X5gBwV9N1UbA2RAU+0QWN91JHFAu0hqhwkDWKZ2wbTY=,tag:+wnu3c+lHtsj+z70p46r5Q==,type:str]
sops:
    lastmodified: "2026-08-20T10:00:02Z"
    mac: ENC[AES256_GCM,data:uBVnsGhNeL26P+KpV5w6ESC5xgTV21YN8xMOO/nS5be3lk06NCwpwqIS0L008TZGxV1w2H2ApUKTYwbrcruLzjyj1v0R1G9ct8pXYfgoH4OR71LZG1q2IVKvCMqc+gEmxP5a+OEjzlK2yS1UDBUYiU7txUJBZIDiu/Luijrrtd0=,iv:Quc058DQQvFwNztyT0qsFeXa82ZiYmmGxT6zmy555gc=,tag:i3iXgGng1zREBu4NsckSvw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-20T10:00:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5NT/LvuRqeGAQ/+L694fUMErHuhRAmfQm87vxFr/YeX7+mOrAsCT4fKwoy+
            XrFBfz7xz7EkdEZVEgkgWxBAiSvQEIpDrDEKfoeS8rPxZYt2y0thldFBe2xAQ1+9
            o7M5WWoscBarAYepQR4+Om+drzW4UlWwKm3w9weaJH9ilJ0TZFPTEDonjtv2gsgk
            q0BV5M+ldSRtn+FLmrJAnV9DhRLMlwHuOGj5Ug41OAMRS731VuRVn5itbNcKToR1
            gOV44jMqX+h7zH+JSVIrcQLJ84J86umLvXp2C657vfkUgcPclBWN8/1qc+/BhCD7
            wvduWcwAAOvUVeV40UJupKim9O+eYDcgRQBBr0iyRGKFkqMU98zZFySJB8m7kxLu
            4Gn1rMBt96PnNmZ/DjqW6zE4uf+57LpP0lz9DeqE0QS1ElbhfsmREQ0fBJuldycb
            YfuSdRNT54xPSgTkBoShi3mdWdWKZLE4XngyWw/28xgwOMqRkSq/eVUTK4KAXxl8
            tzRYt57lhu1iTDEtpE4ZIpHqTwFk6Unmc3krRYtSdAPABqo4pg9jYIoiIxUQwem7
            qr5Xuni0/8kAoh9VTVPzFjJy6TR0k1xfDt24sJD43kJwLLYEx645seoJfhMZqrQi
            ejU3qSY5K0NelTnnHtWZsZijAIPohT8FN2WogVL/CEEMh9pjLUQkYyJBd7q735LU
            aAEJAhCKdC3/s4mYnEHmmVJj9hgaiuI09OSjaPwTrBiqP25Xr6/olyQNCDkiDwd/
            HXKpLSDO+2DlnBoKcMjQvORQA9ihgF2fHPS6ajzFiB8pi847Pr4aNP7JhevwlCLS
            xEe/3ZSX9h/J
            =Wevo
            -----END PGP MESSAGE-----
          fp: 47E4999BED565F9874AA0E7C05DA03D000FC10D1
    unencrypted_suffix: _unencrypted
    version: 3.13.2
